#!/bin/bash

# Try multiple times to apt update and install

try_count=0
while ! apt-get update; do
    echo "Waiting 5 seconds"
    if [ $try_count -lt 10 ] ; then
        sleep 5
    else
        echo "Giving up."
        break
    fi
    try_count=$((try_count+1))
done

try_count=0
while ! apt-get install -y python; do
    echo "Waiting 5 seconds"
    if [ $try_count -lt 10 ] ; then
        sleep 5
    else
        echo "Giving up."
        break
    fi
    try_count=$((try_count+1))
done


status-set maintenance "Installed" || true
