#!/bin/bash
set -eux

status-set maintenance "Installing" || true
if ifconfig lxdbr0 2>&1 | grep -q "HWaddr"; then
    status-set maintenance "Configuring LXD" || true
    $JUJU_CHARM_DIR/scripts/setup-lxd.sh
fi

RELEASE=$(lsb_release -sc)

status-set maintenance "Adding /etc/apt/preferences.d/proposed-updates" || true
cat > /etc/apt/preferences.d/proposed-updates << EOF
Package: *
Pin: release a=$RELEASE-proposed
Pin-Priority: 400
EOF

status-set maintenance "Removing sshguard" || true
sudo apt-get remove sshguard || true
status-set maintenance "installing firewall packages" || true
apt-get update
apt-get install -y ufw
status-set maintenance "Installed" || true
