apiVersion: v1
kind: ConfigMap
metadata:
  name: juju-controller-config
  labels:
    app: juju-controller
data:
  agent.conf: |
    # format 2.0
    tag: machine-0
    datadir: /var/lib/juju
    logdir: /var/log/juju
    metricsspooldir: /var/lib/juju/metricspool
    nonce: user-admin:bootstrap
    jobs:
    - JobManageModel
    upgradedToVersion: 2.5-beta1.1
    cacert: |
      -----BEGIN CERTIFICATE-----
      MIIDrDCCApSgAwIBAgIUcxEbwMv177lg2pTqqfkuBvE+6rEwDQYJKoZIhvcNAQEL
      BQAwbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
      Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkZjU5OWNlNDAtNjkyYS00NzAw
      LTg2ZmYtYzkyN2E1ZTlhOTNmMB4XDTE4MDgyNzAyMTE1M1oXDTI4MDkwMzAyMTE1
      MlowbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
      Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkZjU5OWNlNDAtNjkyYS00NzAw
      LTg2ZmYtYzkyN2E1ZTlhOTNmMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
      AQEAr/wI4stwkPIaw+2EVQwHbqeGX4LQPaEJGbwubmAuQPKAIZGqKqWGXdY6+Ixd
      GFLapXORWImw9w+XP7Fc562TXGVB8VNVGGUQRzfUs0FMvjKQ78CM3kxNA0r+mA6P
      IDBU/mrRR2C9U2/PDDMf4zBRUUWbjQQfqGNEm5/F8eGOJDwOompXXnh1puXhucDZ
      Of+xdaatlb9HKwwfK8INboPmkAL0JpF1LXVnOn8AMYnFFYohHBTC+3Wta2Rn4tNX
      Qq6APCSfHYCopVlG0GsrDLeRLHYoreQmiyw1+YatS31MaGiGqnnkeVJPMa9x0Sy5
      SdUoKSDYK3dYo/GzTilVbNyRdQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
      VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUEZBjiZf5sTTAKkXaBMLbcnEbw8EwDQYJ
      KoZIhvcNAQELBQADggEBAImvg8SmBeFf5u33U+LvfClY63YDwGCT+pzpzUrVI3iJ
      UIqUD+c+7oGSkDbIYESepBqYzDPyhT7zlUJKPaQVwAGqz6BT7MNgImPuAuLFk0ur
      up054Jr+8ozybqKFW89/eHahjdufrNRplHZfcn5cXqbjflxsntk7ptIhy2l3plet
      iDELkvN8bvQ1L9RyFdKxaQnXGLMp8GJ6xPhEuooyWjmfQUZf2QB5+tUfeMfYaD6i
      VR2mo3QJx3nC/Q0BRCfAjpRXxzlX6ws5ynx9H9mbEcCJVIwklkd8/A16A6K+g073
      UyXxQANHHzmA8BaTB7d3p/nYH2xidgWNMtz6rmGrZX8=
      -----END CERTIFICATE-----
    statepassword: qGdzS97iwCqo5L/j+QB+9IR1
    controller: controller-d5481262-e1ad-44e3-83d5-9e66c0611d23
    model: model-9a776575-c053-430c-8059-ce5abce17b7a
    apiaddresses:
    - 127.0.0.1:17070
    apipassword: qGdzS97iwCqo5L/j+QB+9IR1
    oldpassword: dbacffbe75cd8c70d81fe7738d9e8493
    loggingconfig: <root>=DEBUG;unit=DEBUG
    values:
      AGENT_SERVICE_NAME: jujud-machine-0
      CONTAINER_TYPE: ""
      NUMA_CTL_PREFERENCE: "false"
      PROVIDER_TYPE: ec2
    controllercert: |
      -----BEGIN CERTIFICATE-----
      MIIDyjCCArKgAwIBAgIUGuZBN2YbwpmxDpuhTJQisVVYjf8wDQYJKoZIhvcNAQEL
      BQAwbjENMAsGA1UEChMEanVqdTEuMCwGA1UEAwwlanVqdS1nZW5lcmF0ZWQgQ0Eg
      Zm9yIG1vZGVsICJqdWp1LWNhIjEtMCsGA1UEBRMkZjU5OWNlNDAtNjkyYS00NzAw
      LTg2ZmYtYzkyN2E1ZTlhOTNmMB4XDTE4MDkwNTA3MDk0MloXDTI4MDkxMjA3MDk0
      MlowGzENMAsGA1UEChMEanVqdTEKMAgGA1UEAwwBKjCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAKJAcMBtwpF6c2DdN0p47OFIHJVskNhZjGKMZuiwk+LC
      PQEYV1UkyJ/b68AIUZpITZ4I4h8zanhfDDOj/SNIZRh2YdAnGnkKsDd8RpCws8W6
      YwHG4cFjk6J35EFRj3Gxw28UGSxocKSFgBNAg6OIu2Hh6JLxrB0Z/27xOsBuFBpi
      a6u48s8exISESPqVyFPcPa7E1TOxqPaAmbhjuYJZ99rBHSO4CzoApoWsUNOvG5jZ
      9BDpagUKQHE3xvaOXPz7/N+kBR7DPJyMjcKT/KjdM0/ja3kyXI41GxUTLHgJvEYj
      liswxxTNF2DgHot0QHB6eKV427ELMA1QhO9mCYQ5biECAwEAAaOBsjCBrzAOBgNV
      HQ8BAf8EBAMCA6gwEwYDVR0lBAwwCgYIKwYBBQUHAwEwHQYDVR0OBBYEFJWf3GAI
      61a+FVAbXttJ8I8NCsaRMB8GA1UdIwQYMBaAFBGQY4mX+bE0wCpF2gTC23JxG8PB
      MEgGA1UdEQRBMD+CCGFueXRoaW5ngg5qdWp1LWFwaXNlcnZlcoIManVqdS1tb25n
      b2Rigglsb2NhbGhvc3SHBA3udPWHBKwfBskwDQYJKoZIhvcNAQELBQADggEBAFxg
      ylrXo4R5XoIwQ7c2ZNNbV4YsYbtPj1WGWgbv/t7hIDlY0hnAlLHOczuBilgPYZz9
      v2HNy2NxAAzQOhD23+U4aOKh0HQiJSZLZCdhjjcUZ3m/xeNIx6mby6OP4guZ3B8e
      GXj2g5dUNSOcW4QbKIG191YD+bGSPgiLmfhrLOJlXuguLmVHdJ6kJiZPMn624Fvm
      ucqwDrKkhet8x9AgkG9W39c6M/I0SWGtmZZ6TXUYrc5WJGhsoFKZ2RsxRVHG+4LQ
      aEvDWaQluEkuYP/kbVHzZ+cG2fprUbj8knDfJqu2wMYz6irk4ANpUIaEtBMPsQBt
      7kM4S61VoABZEmnpm9c=
      -----END CERTIFICATE-----
    controllerkey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAokBwwG3CkXpzYN03Snjs4UgclWyQ2FmMYoxm6LCT4sI9ARhX
      VSTIn9vrwAhRmkhNngjiHzNqeF8MM6P9I0hlGHZh0CcaeQqwN3xGkLCzxbpjAcbh
      wWOTonfkQVGPcbHDbxQZLGhwpIWAE0CDo4i7YeHokvGsHRn/bvE6wG4UGmJrq7jy
      zx7EhIRI+pXIU9w9rsTVM7Go9oCZuGO5gln32sEdI7gLOgCmhaxQ068bmNn0EOlq
      BQpAcTfG9o5c/Pv836QFHsM8nIyNwpP8qN0zT+NreTJcjjUbFRMseAm8RiOWKzDH
      FM0XYOAei3RAcHp4pXjbsQswDVCE72YJhDluIQIDAQABAoIBAF8XFz2f1j0+n6ow
      W/w4fNPXWHE2bHlvmfgTwygyfKmUHv6qTlynLzGJSVSFS5X5NAwftq6Eiqy7P8Jw
      JKZuAlng35iHols4KWiLXCvmc6W5g9cBwUN+4YKBc3PYohIHFbve8pX1K7cwSox9
      7eiE9RT7ujuMicuQdgSGOmGW4g9HmlhZ22HvGJWa+4hPTcMZYH05F0SuT+HexjeF
      JnVyat00/qEhEhBZrH7jCHzrFPalslDpioXOfRWYHzOBoZI4CuHWxIBW/dP9raUz
      7AuAD+s3KX3woBtH6/O9mQA9zE5G4tMTh+3FEpQ/Thxx7zIzG8A6JHWzY0hIZxzB
      Alc7YAECgYEAz0Leg6o0nt50PPvFkJOTJBdQl3zVCUdxdLg0byvOVn0ETQ7HVd3J
      aI1TWmlm7Y5XxT9VsF3WYE28PthRubWoBodgGPBX/XjGCXg12Jv1LACq4F/AJLvr
      onHV+lfiiuJoIydzqaAQ+IBOwc+Pk/Ce9ureKW4mwGzsJgNBe4c9iyECgYEAyGf/
      r+x6XquvKyw6/7ptDeWjd3t3FylJQBXzVMxdhOHLUTKHVqjcDRdWM2GWPFU05QML
      4Xz3Pmp8CiS5Hxcx9oFrAtr0iIk3CGZ76YV1F7r9CFe7FKZ6IbGQuzU3Vr2F8qNm
      IPW3yuot/xj6UVwjGofnTqAtmw1IMCcAY5+KgwECgYEAmu5jo4yyNSgZQBT8xGxs
      i4gaKIOaRItxVkz0dT4Lyj893dR0Uc2u50btziIIXQAQwFPt3B7pR6gUVe4ieW4/
      olHEFiBjxghoEWAY8Ej05uXA1mT9HviS1iW+TJsxr5w7ODwfi+cpiHlxZhOgQniW
      fAFp/RJoSWOiy2+XnZ2k9cECgYAAuL8m9wcJyDx9P0+HFDjIUAdiqsMnBjMJVAro
      R0Qe8mE1DaWHHlyMf4UD8loEJZpnKLemPDj3tJJ1xuQTxJWdeaHVBMzUoQndseDI
      Wn6tczLuEMLPtDnEXUtUIUDtwwj0crovbDMZO/amcISWPmqx8cNXeSQw5r9XzQwn
      T6/EAQKBgELuxwka9FMTH/popl+vdVpfZmBPoFdaT8NfcKNV6bqGjxa3fI6SPoLB
      7zARlb4w7O8XKu4o3QmZsAwo0c1aTOSNt/bHE2+8errNQhX1ThvB/THj258LKvTW
      4e3HRnzbZRbcTSKlgzpX2yYdHRUQ+lO6Pc4YL25VOm1XzMnrG2Wi
      -----END RSA PRIVATE KEY-----
    caprivatekey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEAr/wI4stwkPIaw+2EVQwHbqeGX4LQPaEJGbwubmAuQPKAIZGq
      KqWGXdY6+IxdGFLapXORWImw9w+XP7Fc562TXGVB8VNVGGUQRzfUs0FMvjKQ78CM
      3kxNA0r+mA6PIDBU/mrRR2C9U2/PDDMf4zBRUUWbjQQfqGNEm5/F8eGOJDwOompX
      Xnh1puXhucDZOf+xdaatlb9HKwwfK8INboPmkAL0JpF1LXVnOn8AMYnFFYohHBTC
      +3Wta2Rn4tNXQq6APCSfHYCopVlG0GsrDLeRLHYoreQmiyw1+YatS31MaGiGqnnk
      eVJPMa9x0Sy5SdUoKSDYK3dYo/GzTilVbNyRdQIDAQABAoIBAGH/uLcK0Ql2OJ9o
      kauGglEFaxee0fWvylCRcU23s6opIF8RLbCH8nYoyTgFegYEhYti+spSCsDZ5sDq
      NLEzAH+QR5Nqc1WdWd4+4excba7wm7NXB1r3JF+0EGh+mwcywvHWa+oSnftrpOHH
      SneKPY5Dc+aoKDTt6pO6+lDC6ROVjXhKYmKmbvJyKh/1Lotm31ekwYZLvyOi5t9z
      Kskmi6FeuAKDZcSMS8/nlBl4M13rFFQyQ+aq4qNwFngPD8B0QLz5BYJi86Mn+yrF
      doCT4c6BMsXCdQt7T/7lVptWRpXpSwzIwMCS1wUy4bY5WDp/abJc8FqgrUKE2V/V
      JSQjYaECgYEAy2X3evFO1hw8rFPhjrQCQcPx/OfeMgvO7dr1ntZfZZWa/Uo4sXL4
      h6BVT99zLNqtAj3pTyi94rnAFUJnKOTTJagwkSC+tEZSe0w9+OfyRigDCTKrmRAE
      OyWocCxrAHn/2otgh/kF06cPFu/RoK/+ACtbfgmT8vb1JTsPTtAkIg0CgYEA3X8h
      jKQ1OKT6rD8X0Zf1aAQ5wANNRghV/GM2Nh/C/px9zFt2qoSmWwmqRkI4EA9++aAF
      z6NymNalaSK67dQBNekl54mA6E/vBSEjoD7VntcAbmyy7olNXyD2wiuy3NpTplHf
      X9hJV8YDX+NVZaMUzoOMzxOpjhmPBZXqFnwAGwkCgYBA3uaNeYTxWNQpCh+4ScUm
      gH4fcTw2rflzdxA7dpe6aHqkKhXm0opdh09uSBAN0Di5rFFLA+178E5I+YK5UjHd
      osTKpKzuBjesR2bEigWFRqGhP13nVWpkCuCr1h7Sahal9yn0dAHdvTxczmQHYdoa
      57koe5mKNiV9mFaLhmrfyQKBgQCQe6No2JyW7JdP0IA7CkLcrRT2ubCoZDuivRzZ
      xXIvH+m3alpH9OuHKxDVb9CeOV18e/QOc/IG3M1dfXguN0Lq5cEB/eIGqE2kLO/O
      Ue6LBHiVj3ZQv2OnEBumoVa1Vf2G2pU5Mh71kIcW/3XvLKgf5hPt6EeMGAQBgr8G
      F7EB8QKBgGGhHmRO5QDJhL6fqnc6z0DL78O/hGGYPqN7pjCwgyvPWagMrZKENXY5
      gd4hJmPxCBthMswdF9qKm8LRnb/3FrmgBTsbFoDs1qZpuvfkbqFGk/QlvOrAylWA
      ICxEI9P1aFYRyHHMmFC/FQRWx/VniQQAhj854NHoNPy90zYkFd6c
      -----END RSA PRIVATE KEY-----
    apiport: 17070
    stateport: 37017
    sharedsecret: 4V91rmxX9WO6FGRhLXSZPfdTE1vtqxH8L800C3kYsxDEDoHiKO8H6tneRuqTyRoZ2ChtsjjNM6YC4Nq+YwTBBY0CYFJM+vA79nxW6M9u2K7OEEAMzh1wJ9MNqG1MXGb/ZAk+Ie1TpVzTG2Kei9RUmjrNU/wMcBEBM88CmE8eNwupmO+bFy7YN+qXNGn9dOy+Ii66fDnze+neNX5umc/1DAcJ7CPYEGob+jC16Zmm2QVjeXuOLH8C4Kg33nzgA/Uvjv2lqIzFtdvEaPWXKuqgB/pMUFbjyxn8JtYdzEkzpNomzAugb6Z5o74O3nzGT6FoWV5bkFrTnTpu62/yuGiycfzowYfVwZ6w6fTrGTJDfupejyL3AGOX0sYNlNR7VkEImpYH1/1us+T1o8c/+9EmVSzho0kBpLEnagNHqSF+gwNgsg9KrWn/W4UV1TX89lsPbVKlNRaOcDOkDryz+slpUN9/+GWpvprSjdO1jLBw346l//xYakymDF29466IxNHSfxiAv2vFDamHTRivt0uqdl6RBPHtE0OvC0Ui9EtcIId0ukhqVYh99mgiunlEun6JjzTam8JK+fjZdQ9l1FhmuI+E5Qxq/QLPTF4oQN4JTisSinuNY6gma4Vt95gSTNq/JD9EXUf9/uLZq/dFeFFMOl2Fx4x4gCUuf8mvBlDfc7futMmFaywYZBobP0qbRWboV/by/JHvSAMvDn/3ooXmkm6qXI3JCj94XJts1T/i6Uaz3eNLSAf12efoVB1dQurt3BZBO2fRuUV0Ed352zqUXMtFwvY+bTkDQIEcjVCULdFewSnvJsxyvqWWCyTnJGOjjsUFfYzvKRblJ5y3X5UWU+SodTe2/8EzbTC8hctuc6n648gIxH7d6iFE/kJ+DG5FNphWANgG/spH3s17BdJjJKmhCYFUyeWPnQlwhoSZVugTn/A7M+4EWJgflGT1E2MksCtYfdbseVer+h+zj+0woSJ59q8ydWcj3ud0Z9pJ3kgEJnYOu4wtlGy/nvRGYbcS
    systemidentity: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEA1Dm6Al9LAUtksxc+AIBiQjFnJpkLNq/3B+X5UQcaLzAtGvFG
      SLBIYEEI/V7zweP2kpHFGTEPuQoRVzdseWAN0+JBgSoG2JUd87sIwBU7Y/c+KhMx
      u8q+do6NpPqsCjV2QoqeYV1IxASf/KxqAigE51KWUl5oQ6kZD+rlFJ0D8Bx1EBw0
      Xx9mRoGlLUKpsuDwqdOKgdJP6OgryCD1G8Jc1/lkdpTVhpSmd2iTbfqqmG0wPQq6
      IvdqvEwjiSdrz+/4RPO4umEgMFDQlgiZYncwWc+CT/rbWwHNWWMVHFp0GFA2xrOB
      zHakH3kB2yxwBOedCVRnyWYPSj5kXvUQm3hdmQIDAQABAoIBAHMtoTYIYbyiHlTU
      GGJNSwaBqWnZRay4c2ll9plzMVLK4q/soihxA9a5dReNoN1pyzhgxIeXiOD0BdU/
      zy9QYjDMaqCfHngM9eSBbY5R95mZZbOQFz3EGvpdA6K2KQihWz1h3fMZnZRErk+D
      g0UIUyD4QX0Sn6OY8nEhGpLFZI265msb1y2lEJfPWmTxQA6ay6e/8oqUycpZ8K+x
      gDz+w+ujO4sGIqRVtYTC7vnLLgCCFbNdkHan/tpflA/2sepqzXGiT3OB9SiXUPt1
      10pd73FvJJV5KMN1v4fcL7LaIlyKiuHrxDST5doZkJpo+Gda6l5Kfh8AZQ0pk4pY
      PG+piMECgYEA2TWMshgRGtWFeHFLzR8LHuSKrKjWCfvwI6xAAZl0VL/mAf8lllDt
      kSy+oQPcNs+rYEpLgpTRgFrYAy0JeEWA8lcLpS8JcB4yGeQkcRXAmeZxZd3nDSEh
      bFBORvsWhpnKVAssfwfXR1eguzDsLrf9/mIm8+Eey0V+UejbhdMcif8CgYEA+iBU
      wtBabY0Vm/KU0yKrmN0KB84bkKulf3XNfV2w8nv7nCyRlNAjCgu5z+Pig1yfGsNH
      E/DHcegWKte4mObuN9GxtpGNDztfXU+cZKRP6OjXNz6eAohtFSmWTjHHDpy3lMt8
      mjNZCjm98U2X/Iw5/SIEmM4l1xhWWbeKdwiTKGcCgYA7gGjfbKpa4H0kplyufz+L
      oe2/KK0hpQt+qjQKfCAbC0qV53BDgj3iFBDQiP8tYKxAv3l59wyBDeG41QCQGvIc
      8O12vbDnLs5ou0+kTuIpBrCvyB8AQMAoLMOUvDnKe5yqczkoP1yg5YdZYCiDD9Ib
      eoXTLytBYfMdux1Pxqo9vwKBgDnzY6//NfRLy8Xl3jVMwxUXoUtNpXVPT3jIgmOZ
      YXXM4+67JL+luXiKXvKbic+FlhdNRxqHnq31Z61lbY9/cZHdM59o+ZWd2+pyl3l5
      2EnOKI7UIyfTE/LjP7++KLBp/t6qhqPzYZ3M4wUVRTFuC8FqMEZ2/K1pJhiDPcF2
      ayHhAoGAIaRxScWB7te3Y5sIqXrjQ0EBe7O+V1WwwgmGLEG95Rq1haafu6kDvLWD
      v4+3QCEVEw2lKj8IHFb8QPq2rz6Zy+mAM8nVMtS/jf01rh+LN1K1K2xnDcFyQDhy
      9YxZn4X4ZH1/4RJD+sQ6Raz1ln8Xtw1G9AR87qWdSdMU8K4n4Es=
      -----END RSA PRIVATE KEY-----
    mongoversion: "0.0"
    mongomemoryprofile: low

