apiVersion: v1
kind: Secret
metadata:
  metadata:
  name: juju-controller-mongo-admin
  labels:
    app: juju-controller
type: Opaque
data:
  username: bWFjaGluZS0w
  password: aXpSRVA3Y3hucnlMWDJnd0VVZTN6bDQw
