#!/bin/bash

export PATH=$PWD/plugin:$PATH
unitstatus=$(status-get)

status-set $unitstatus "list: listing workload processes in state"

result=$(info 2>&1)
rc=$?
if [ "$rc" == "0" ]; then
    action-set output="$result"
else
    status-set $unitstatus "list: failed ($rc - $result)"
fi
