#!/bin/bash
#
#    loadbalancer-relation-changed - hook for when loadbalancer peer relation changes
#
#    Copyright (C) 2012  Marco Ceppi
#    Author: Marco Ceppi <marco@ceppi.net>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

source inc/common

secret_key=`relation-get secret-key`

if [ "$secret_key" = "" ]; then
	if [ -f ".wp-secret" ]; then
		relation-set secret-key=`cat .wp-secret`
	fi
else
	echo $secret_key > .wp-secret
fi

if [ -f "$config_info_path" ]; then
	secret_key=`cat .wp-secret`
	sed -i -e "s/define('SECRET_KEY',.*/define('SECRET_KEY', '$secret_key')\;/" $config_info_path
fi
