# Configuration file for Dependabot.
#
# The rules are as follows:
#
# - For golang dependencies we will only update golang.org/x/* dependencies and
#   they will always go to the 2.9 branch as it may contain security fixes.
# - For pip/uv dependencies are generally targeted at docs and thus will go to
#   the 3.6 branch.
# - We'll ignore any dependencies in the testcharms directory as they are not
#   part of the main codebase.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
    assignees:
      - "SimonRichardson"
      - "anvial"
  - package-ecosystem: "gomod"
    directory: "/"
    exclude-paths:
      - "testcharms/**"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-name: "golang.org/x/*"
    assignees:
      - "SimonRichardson"
      - "anvial"
    target-branch: "2.9" # these should always go to 2.9 as it may contain security fixes
  - package-ecosystem: "pip"
    directory: "/"
    exclude-paths:
      - "testcharms/**"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "tmihoc"
      - "anvial"
    target-branch: "3.6"
  - package-ecosystem: "uv"
    directory: "/"
    exclude-paths:
      - "testcharms/**"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - "tmihoc"
      - "anvial"
    target-branch: "3.6"
