actions: 10069
add-cloud: 10162
add-credential: 10136
add-k8s: 10049
add-machine: 10071
add-model: 10145
add-secret: 11144
add-secret-backend: 10062
add-space: 10117
add-ssh-key: 10238
add-storage: 10159
add-unit: 10141
add-user: 10193
agree: 10161
agreements: 10064
attach-resource: 10124
attach-storage: 10126
autoload-credentials: 10230
bind: 10244
bootstrap: 10132
cancel-task: 10053
change-user-password: 10118
charm-resources: 10099
clouds: 10182
collect-metrics: 10085
config: 10139
constraints: 10060
consume: 10213
controller-config: 10237
controller-config-keys: 7059
controllers: 10152
create-backup: 10197
create-storage-pool: 10093
credentials: 10054
dashboard: 10091
debug-code: 10048
debug-hook: 10229
debug-hooks: 10242
debug-log: 10116
default-credential: 10055
default-region: 10082
deploy: 10074
destroy-controller: 10113
destroy-model: 10190
detach-storage: 10089
diff-bundle: 10142
disable-command: 10205
disable-user: 10198
disabled-commands: 10220
documentation: 10101
download: 10134
download-backup: 10240
enable-command: 10111
enable-destroy-controller: 10086
enable-user: 10241
exec: 10195
export-bundle: 10046
expose: 10109
find: 10187
find-offers: 10097
firewall-rules: 10061
grant: 10196
grant-cloud: 10164
grant-secret: 11290
help: 10185
help-tool: 10050
hook-tools/action-fail: 15022
hook-tools/action-get: 15023
hook-tools/action-log: 15024
hook-tools/action-set: 15025
hook-tools/add-metric: 15026
hook-tools/application-version-set: 15027
hook-tools/close-port: 15028
hook-tools/config-get: 15029
hook-tools/credential-get: 15030
hook-tools/goal-state: 15031
hook-tools/index: 15021
hook-tools/is-leader: 15032
hook-tools/juju-log: 15033
hook-tools/juju-reboot: 15034
hook-tools/leader-get: 15039
hook-tools/leader-set: 15040
hook-tools/network-get: 15041
hook-tools/open-port: 15043
hook-tools/opened-ports: 15042
hook-tools/payload-register: 15044
hook-tools/payload-status-set: 15045
hook-tools/payload-unregister: 15046
hook-tools/relation-get: 15049
hook-tools/relation-ids: 15050
hook-tools/relation-list: 15051
hook-tools/relation-set: 15052
hook-tools/resource-get: 15053
hook-tools/secret-add: 15054
hook-tools/secret-get: 15055
hook-tools/secret-grant: 15056
hook-tools/secret-ids: 15057
hook-tools/secret-info-get: 15058
hook-tools/secret-remove: 15059
hook-tools/secret-revoke: 15060
hook-tools/secret-set: 15061
hook-tools/state-delete: 15062
hook-tools/state-get: 15063
hook-tools/state-set: 15064
hook-tools/status-get: 15065
hook-tools/status-set: 15066
hook-tools/storage-add: 15067
hook-tools/storage-get: 15068
hook-tools/storage-list: 15069
hook-tools/unit-get: 15070
import-filesystem: 10047
import-ssh-key: 10167
index: 10045
info: 10103
integrate: 10207
kill-controller: 10233
list-actions: 10232
list-agreements: 10200
list-charm-resources: 10234
list-clouds: 10199
list-controllers: 10079
list-credentials: 10150
list-disabled-commands: 10094
list-firewall-rules: 10114
list-machines: 10181
list-models: 10107
list-offers: 10170
list-operations: 10158
list-payloads: 10070
list-regions: 10131
list-resources: 10056
list-secret-backends: 10072
list-secrets: 10108
list-spaces: 10100
list-ssh-keys: 10133
list-storage: 10138
list-storage-pools: 10211
list-subnets: 10076
list-users: 10154
login: 10157
logout: 10183
machines: 10078
metrics: 10143
migrate: 10121
model-config: 10096
model-constraints: 10137
model-default: 10178
model-defaults: 10057
models: 10090
move-to-space: 10192
offer: 10080
offers: 10051
operations: 10203
payloads: 10120
refresh: 10189
regions: 10112
register: 10160
relate: 10140
reload-spaces: 10063
remove-application: 10067
remove-cloud: 10216
remove-credential: 10201
remove-k8s: 10098
remove-machine: 10163
remove-offer: 10235
remove-relation: 10110
remove-saas: 10087
remove-secret: 11414
remove-secret-backend: 10194
remove-space: 10084
remove-ssh-key: 10119
remove-storage: 10066
remove-storage-pool: 10068
remove-unit: 10125
remove-user: 10130
rename-space: 10135
resolve: 10146
resolved: 10144
resources: 10218
resume-relation: 10123
retry-provisioning: 10209
revoke: 10077
revoke-cloud: 10104
revoke-secret: 11291
run: 10052
scale-application: 10171
scp: 10128
secret-backends: 10149
secrets: 10214
set-application-base: 10174
set-constraints: 10210
set-credential: 10169
set-default-credentials: 10180
set-default-region: 10092
set-firewall-rule: 10151
set-meter-status: 10166
set-model-constraints: 10208
show-action: 10219
show-application: 10177
show-cloud: 10215
show-controller: 10156
show-credential: 10105
show-credentials: 10147
show-machine: 10243
show-model: 10191
show-offer: 10168
show-operation: 10083
show-secret: 10172
show-secret-backend: 10059
show-space: 10095
show-status-log: 10204
show-storage: 10184
show-task: 10129
show-unit: 10239
show-user: 10212
spaces: 10236
ssh: 10153
ssh-keys: 10202
status: 10173
storage: 10075
storage-pools: 10228
subnets: 10186
suspend-relation: 10179
switch: 10102
sync-agent-binary: 10106
trust: 10088
unexpose: 10221
unregister: 10165
update-cloud: 10081
update-credential: 10065
update-credentials: 10231
update-k8s: 10155
update-public-clouds: 10115
update-secret: 11413
update-secret-backend: 10176
update-storage-pool: 10217
upgrade-controller: 10058
upgrade-machine: 10188
upgrade-model: 10073
users: 10175
version: 10127
wait-for: 10122
wait-for_application: 11181
wait-for_machine: 11183
wait-for_model: 11182
wait-for_unit: 11184
whoami: 10148
