---
apiVersion: v1
kind: Namespace
metadata:
  name: container-registry
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-claim
  namespace: container-registry
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
  namespace: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2.7.1
          env:
            - name: REGISTRY_HTTP_ADDR
              value: :5000
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/registry
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "yes"
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: /certs/registry.crt
            - name: REGISTRY_HTTP_TLS_KEY
              value: /certs/registry.key
          ports:
            - containerPort: 5000
              name: registry
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-data
            - mountPath: /certs
              name: tls-certs
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: registry-claim
        - name: tls-certs
          hostPath:
            path: /home/runner/certs
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: container-registry
spec:
  selector:
    app: registry
  clusterIP: 10.152.183.69
  ports:
    - name: "registry"
      port: 443
      targetPort: 5000
