#!/usr/bin/env python
from argparse import ArgumentParser
from contextlib import contextmanager
from textwrap import dedent

from jujuconfig import get_juju_home
from jujupy import (
    Environment,
    EnvJujuClient,
    JujuClientDevel,
    until_timeout,
    )
from deploy_stack import (
    bootstrap_from_env,
    check_token,
    dump_logs,
    get_machine_dns_name,
    get_random_string,
    update_env,
    )


def bootstrap_env(env):
    env.destroy_environment()
    juju_home = get_juju_home()
    try:
        bootstrap_from_env(juju_home, env)
        host = get_machine_dns_name(env, 0)
        return host
    except:
        env.destroy_environment()
        raise


@contextmanager
def dumping_env(client, host, log_dir):
    try:
        try:
            yield
        finally:
            dump_logs(client.env, host, log_dir)
    except:
        client.destroy_environment()
        raise


def prepare_dummy_env(client):
    client.deploy('local:dummy-source')
    client.deploy('local:dummy-sink')
    token = get_random_string()
    client.juju('set', ('dummy-source', 'token=%s' % token))
    client.juju('add-relation', ('dummy-source', 'dummy-sink'))
    client.juju('expose', ('dummy-sink',))
    return token


def assess_foreign(native, foreign, base_env, environment_name, log_dir):
    old_env = Environment.from_config(base_env, juju_path=native)
    update_env(old_env, environment_name, series='precise')
    old_env.config.pop('tools-metadata-url', None)
    new_client = JujuClientDevel.by_version(foreign)
    new_env = Environment(old_env.environment, new_client, old_env.config)
    foreign_client = EnvJujuClient.by_version(old_env, foreign)
    test_control_foreign(old_env, foreign_client, log_dir)


def test_control_foreign(env, foreign, log_dir):
    host = bootstrap_env(env)
    native = env.client.get_env_client(env)
    with dumping_env(foreign, host, log_dir):
        token = prepare_dummy_env(native)
        native.wait_for_started()
        check_token(env, token)
        check_series(foreign)
        foreign.juju('run', ('--all', 'uname -a'))
        dummy_source = foreign.get_juju_output('get', 'dummy-source')
        env_output = foreign.get_juju_output('get-env')
        foreign.juju('remove-relation', ('dummy-source', 'dummy-sink'))
        status = foreign.get_status()
        foreign.juju('unexpose', ('dummy-sink',))
        status = foreign.get_status()
        foreign.juju('deploy', ('local:dummy-sink', 'sink2'))
        foreign.wait_for_started()
        foreign.juju('add-relation', ('dummy-source', 'sink2'))
        status = foreign.get_status()
        foreign.juju('expose', ('sink2',))
        status = foreign.get_status()
        if 'sink2' not in status.status['services']:
            raise AssertionError('Sink2 missing')
        foreign.juju('destroy-service', ('sink2',))
        for ignored in until_timeout(30):
            status = foreign.get_status()
            if 'sink2' not in status.status['services']:
                break
        else:
            raise AssertionError('Sink2 not destroyed')
        foreign.juju('add-relation', ('dummy-source', 'dummy-sink'))
        status = foreign.get_status()
        foreign.juju('expose', ('dummy-sink',))
        status = foreign.get_status()
        foreign.juju('add-unit', ('dummy-sink',))
        status = foreign.get_status()
        foreign.juju('remove-unit', ('dummy-sink/1',))
        status = foreign.get_status()
        foreign.juju('add-machine', ('lxc',))
        status = foreign.wait_for_started()
        lxc_machine, = set(k for k, v in status.agent_items() if
                          k.endswith('/lxc/0'))
        lxc_holder = lxc_machine.split('/')[0]
        foreign.juju('remove-machine', (lxc_machine,))
        wait_until_removed(foreign, lxc_machine)
        foreign.juju('remove-machine', (lxc_holder,))
        status = wait_until_removed(foreign, lxc_holder)
    foreign.juju(
        'destroy-environment', (foreign.env.environment, '-y'),
        include_e=False)



def wait_until_removed(client, agent_id):
    for ignored in until_timeout(30):
        status = client.get_status()
        if agent_id not in dict(status.agent_items()):
            return status
    else:
        raise AssertionError('Machine not destroyed')


def get_agent_version(env):
    return env.client.get_env_option(env, 'agent-version')


def check_series(client):
    result = client.get_juju_output('ssh', '0', 'lsb_release', '-c')
    label, codename = result.rstrip().split('\t')
    if label != 'Codename:':
        raise AssertionError()
    expected_codename = client.env.config['default-series']
    if codename != expected_codename:
        raise AssertionError(
            'Series is {}, not {}'.format(codename, expected_codename))


def main():
    parser = ArgumentParser(description=dedent("""\
        Determine whether one juju version can control an environment created
        by another version.
    """))
    parser.add_argument('native', help='The native juju binary.')
    parser.add_argument('foreign', help='The foreign juju binary.')
    parser.add_argument('base_environment', help='The environment to base on.')
    parser.add_argument('environment_name', help='The new environment name.')
    parser.add_argument('log_dir', help='The directory to dump logs to.')
    args = parser.parse_args()
    assess_foreign(args.native, args.foreign, args.base_environment,
                   args.environment_name, args.log_dir)


if __name__ == '__main__':
    main()
