#!/bin/bash
set -eux


usage() {
    echo "usage: $0 [--jenkins-url URL] ADDRESS"
    echo "  -jenkins-url: The location of juju-ci's Jenkins."
    echo "  ADDRESS: The IP or DNS address the windows test machine."
    exit 1
}


: ${LOCAL_JENKINS_URL=$JENKINS_URL}
while [[ "${1-}" != "" && $1 =~ ^-.*  ]]; do
    case $1 in
        --jenkins-url)
            shift
            LOCAL_JENKINS_URL="$1"
            ;;
        --help)
            usage
            ;;
    esac
    shift
done

test $# -eq 1 || usage

# Remove previous tarballs and installers from the workspace
rm $WORKSPACE/*

HOST="$1"
TARFILE=$(python <<EOT
import json
import sys
import urllib2

build_data = urllib2.urlopen(
    '$LOCAL_JENKINS_URL/job/build-revision/lastSuccessfulBuild/api/json')
build_json = json.load(build_data)
for artifact in build_json['artifacts']:
    filename = artifact['fileName']
    if filename.endswith('.tar.gz'):
        break
else:
    sys.exit(1)
print filename
EOT
)
ARTIFACT=$LOCAL_JENKINS_URL/job/build-revision/lastSuccessfulBuild/artifact
wget -q $ARTIFACT/$TARFILE
VERSION=$(basename $TARFILE .tar.gz | cut -d '_' -f2)

set +e
CI_DIR="/cygdrive/c/Users/Administrator/ci"
scp -i $JUJU_HOME/staging-juju-rsa \
    -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" \
    $WORKSPACE/$TARFILE $RELEASE_TOOLS/winbuildtest.py \
    Administrator@$HOST:$CI_DIR/
if [ $? -ne 0 ]; then
    exit 1
fi
ssh -i $JUJU_HOME/staging-juju-rsa \
    -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" \
    Administrator@$HOST \
    '/cygdrive/c/python27/python \\Users\\Administrator\\ci\\winbuildtest.py' \
    $TARFILE
if [ $? -ne 0 ]; then
    exit 1
fi
scp -i $JUJU_HOME/staging-juju-rsa \
    -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" \
    Administrator@$HOST:$CI_DIR/juju-setup-$VERSION.exe $WORKSPACE/
EXIT_STATUS=$?
set -e
exit $EXIT_STATUS
