#!/bin/bash
source $SCRIPTS/common-startup.sh
if [ "$ENV" == "manual" ]; then
    prepare_manual
else
    DEPLOY_ARGS=""
fi
# Do the deployment for upgrade testing.
CHARM_PREFIX=${CHARM_PREFIX:-}
EXIT_STATUS=0
JUJU_REPOSITORY=$HOME/repository PATH=$NEW_PATH $SCRIPTS/deploy_stack.py \
  --charm-prefix "$CHARM_PREFIX" $DEPLOY_ARGS $ENV "$@" || EXIT_STATUS=$?
if [ $EXIT_STATUS -ne 0 ]; then
  dump_logs
fi
PATH=$NEW_PATH $SCRIPTS/destroy-environment $ENV
exit $EXIT_STATUS
