#!/usr/bin/env python
__metaclass__ = type

import os.path
import subprocess
import sys

from jujuconfig import NoSuchEnvironment
import jujupy
from deploy_stack import destroy_environment


def main():
    no_failures = True
    for env_name in sys.argv[1:]:
        try:
            env = jujupy.SimpleEnvironment.from_config(env_name)
        except NoSuchEnvironment as e:
            no_failures = False
            sys.stderr.write(str(e) + '\n')
            continue
        client = jujupy.EnvJujuClient.by_version(env)
        destroy_environment(client, os.environ.get('JOB_NAME'))
    sys.exit(0 if no_failures else 1)


if __name__ == '__main__':
    main()
