#!/usr/bin/env python
__metaclass__ = type

import os.path
import subprocess
import sys

import jujupy
from deploy_stack import destroy_environment


def main():
    for env_name in sys.argv[1:]:
        env = jujupy.SimpleEnvironment.from_config(env_name)
        client = jujupy.EnvJujuClient.by_version(env)
        destroy_environment(client, os.environ.get('JOB_NAME'))


if __name__ == '__main__':
    main()
