#!/usr/bin/env python
__metaclass__ = type

import sys

import jujupy


def main():
    for env in sys.argv[1:]:
        jujupy.Environment(env).destroy_environment()


if __name__ == '__main__':
    main()
