#!/bin/bash
set -eu
instance_ip=''
echo -n Waiting for IP address >&2
while [ -z "$instance_ip" ]; do
  sleep 1
  instance_ip=$(euca-describe-instances $1|sed '/^INSTANCE/!d'|cut -f 17)
  echo -n . >&2
done
echo >&2
echo $instance_ip
