#!/bin/bash
set -eu
instances=$(euca-describe-instances --filter instance-state-name=running\
  --filter tag:job_name=$JOB_NAME|grep '^INSTANCE'|cut -f 2)
if [ "$instances" != "" ]; then
  euca-terminate-instances $instances
fi
