#!/usr/bin/env python
import json
import os
import sys
import urllib2

local_jenkins = os.environ.get(
  'LOCAL_JENKINS_URL', os.environ.get('JENKINS_URL'))
build_data = urllib2.urlopen(
  '%s/job/build-revision/lastSuccessfulBuild/api/json' % local_jenkins)
build_json = json.load(build_data)
for artifact in build_json['artifacts']:
  filename = artifact['fileName']
  if filename.endswith('.tar.gz'):
    break
else:
  sys.exit(1)
print filename
