#!/usr/bin/env python
from argparse import ArgumentParser
import json
import os
import sys
import urllib2

def main():
    parser = ArgumentParser('Get the name of a build tarball.')
    parser.add_argument('build', help='The build to get the tarball for.',
                        default='lastSuccessfulBuild', nargs='?')
    build = parser.parse_args().build
    local_jenkins = os.environ.get(
        'LOCAL_JENKINS_URL', os.environ.get('JENKINS_URL'))
    build_data = urllib2.urlopen(
        '%s/job/build-revision/%s/api/json' % (local_jenkins, build))
    build_json = json.load(build_data)
    for artifact in build_json['artifacts']:
      filename = artifact['fileName']
      if filename.endswith('.tar.gz'):
        break
    else:
      sys.exit(1)
    print filename


if __name__ == '__main__':
    main()
