#! /usr/bin/env python


from argparse import ArgumentParser
import json
import os

def main():
    parser = ArgumentParser()
    parser.add_argument('file')
    args = parser.parse_args()
    with open(args.file) as file_obj:
        test_json = json.load(file_obj)
    metadata = test_json.setdefault('metadata', {})
    metadata['job_name'] = os.environ['JOB_NAME']
    metadata['build_number'] = os.environ['BUILD_NUMBER']
    metadata['build_url'] = os.environ['BUILD_URL']
    metadata['environments'] = {'local': {'substrate': 'Local Provider'}}
    with open(args.file, 'w') as file_obj:
        test_json = json.dump(test_json, file_obj, indent=2)

if __name__ == '__main__':
    main()
