#!/bin/bash
set -eu
export ENVS="test-release-aws test-release-canonistackk test-release-hp"
export SCRIPTS=~jenkins/ci-cd-scripts
CURRENT_JUJU_CORE=$(dpkg-query --showformat '${Package}=${Version}\n' -W juju-core)
source $SCRIPTS/make-recipe-and-package.bash $(bzr revno .) lp:juju-core
if ! $SCRIPTS/deploy_stack.py $ENVS; then
  for env in $ENVS; do
    juju destroy-environment -e $env -y || true
  done
  exit 1
fi
sudo dpkg -i $TESTING_DIR/juju-core*.deb
mkdir -p new-tools
source $SCRIPTS/assemble-public-tools.bash $PACKAGES new-tools
export GOPATH=$(dirname $(pwd))
source $SCRIPTS/publish-public-tools.bash TESTING ./juju-dist-testing
EXIT_STATUS=0
# Test upgrading an existing environment
if ! bash <<"EOT"
  set -e
  version=$(juju --version|sed -r 's/([^-]*).*/\1/')
  for env in $ENVS; do
    juju upgrade-juju --show-log -e $env
  done
  for env in $ENVS; do
    $SCRIPTS/wait_for_agent_update.py $env $version
  done
EOT
then
  EXIT_STATUS=1
else
  # test deploying on the new version
  for env in $ENVS; do
      juju destroy-environment -e $env -y
  done
  sleep 5
  if ! $SCRIPTS/deploy_stack.py $ENVS; then
    EXIT_STATUS=1
  fi
fi
sudo apt-get install -y --force-yes $CURRENT_JUJU_CORE
for env in $ENVS; do
    juju destroy-environment -e $env -y || true
done
exit $EXIT_STATUS
