#!/bin/bash
set -eux
: ${SCRIPTS:=$(readlink -f $(dirname $0))}
echo $0
export INSTANCE_TYPE=m1.large
export AMI_IMAGE=ami-bd6d40d4
machine_0_id=$($SCRIPTS/ec2-run-instance-get-id)
machine_1_id=$($SCRIPTS/ec2-run-instance-get-id)
machine_2_id=$($SCRIPTS/ec2-run-instance-get-id)
machine_0_ip=$($SCRIPTS/ec2-get-ip $machine_0_id)
machine_1_ip=$($SCRIPTS/ec2-get-ip $machine_1_id)
machine_2_ip=$($SCRIPTS/ec2-get-ip $machine_2_id)
export JUJU_HOME=$(pwd)/manual-provider-home
rm -f $JUJU_HOME/environments/manual.jenv
sed -i "s/bootstrap-host: .*/bootstrap-host: $machine_0_ip/" $JUJU_HOME/environments.yaml
$SCRIPTS/wait-for-ssh $machine_0_ip
juju bootstrap --show-log -e manual --upload-tools
$SCRIPTS/wait-for-ssh $machine_0_ip 8040
juju add-machine ssh:$machine_1_ip
juju add-machine ssh:$machine_2_ip
#echo euca-terminate-instances $machine_0_id $machine_1_id $machine_2_id

if $SCRIPTS/deploy_stack.py --already-bootstrapped manual; then
  exit_code=0
else
  exit_code=1
fi
rm $JUJU_HOME/environments/manual.jenv
euca-terminate-instances $machine_0_id $machine_1_id $machine_2_id
exit $exit_code
