#!/bin/bash
set -eux

: ${LOCAL_JENKINS_URL=$JENKINS_URL}
BUILD_PACKAGES=${BUILD_PACKAGES:-true}
TARFILE=$($SCRIPTS/get-tarfile-name)
VERSION=$(basename $TARFILE .tar.gz | cut -d '_' -f2)

OFFICIAL_VERSIONS="$STREAMS/juju-dist/proposed/tools/releases" 
if [[ -f $OFFICIAL_VERSIONS/juju-$VERSION-trusty-amd64.tgz ]]; then
    echo "$VERSION was published. This version is invalid to test."
    echo "Maybe juju's version needs updating?"
    exit 1
fi

if [[ $BUILD_PACKAGES == 'true' ]]; then
wget -q $LOCAL_JENKINS_URL/job/build-revision/lastSuccessfulBuild/artifact/$TARFILE

# Make source packages for all supported series.
if [[ $VERSION =~ ^1.(18|20|22).*$ ]]; then
    PURPOSE="stable"
else
    PURPOSE="devel"
fi
$RELEASE_TOOLS/make-source-packages.bash -t $PURPOSE $TARFILE \
    'Curtis Hovey <curtis.hovey@canonical.com>'

# Load the credentials to create instances in ec2.
set +x
source $JUJU_HOME/ec2rc
set -x

# Build binary packages for select series.
for dsc in $(find . -maxdepth 2 -name '*.dsc')
do
    series=$(echo "$dsc" | cut -d '~' -f 2 | cut -d '.' -f 1,2)
    if [[ $series == '12.04' ]]; then
        echo "Building precise amd64"
        $RELEASE_TOOLS/build-package-with-dsc.bash m1.large ami-36aa4d5e $dsc
    elif [[ $series == '13.10' ]]; then
        echo "Skipping Saucy"
    elif [[ $series == '14.04' ]]; then
        if [[ -n ${PPC_SSH_OPTIONS:-} ]]; then
            echo "Building trusty ppc64"
            set +e
            $RELEASE_TOOLS/build-package-with-dsc.bash ubuntu@stilson-07 \
                "$PPC_SSH_OPTIONS" $dsc
            set -e
        else
            echo "Skipping trusty ppc64"
        fi
        echo "Building trusty amd64"
        $RELEASE_TOOLS/build-package-with-dsc.bash m1.large ami-b027efd8 $dsc
        echo "Building trusty i386"
        if [[ -n ${I386_SSH_OPTIONS:-} ]]; then
            $RELEASE_TOOLS/build-package-with-dsc.bash ubuntu@i386-slave \
                    "$I386_SSH_OPTIONS" $dsc
        else
            $RELEASE_TOOLS/build-package-with-dsc.bash \
                m1.medium ami-81dee0e8 $dsc
        fi
        if [[ -n ${ARM_SSH_OPTIONS:-} ]]; then
            echo "Building trusty arm64"
            set +e
            $RELEASE_TOOLS/build-package-with-dsc.bash ubuntu@arm64-slave \
                "$ARM_SSH_OPTIONS" $dsc
            set -e
        else
            echo "Skipping trusty arm64"
        fi
    elif [[ $series == '14.10' ]]; then
        echo "Building utopic amd64"
        $RELEASE_TOOLS/build-package-with-dsc.bash ubuntu@utopic-slave \
                "$UTOPIC_SSH_OPTIONS" $dsc
    fi
done
fi

$RELEASE_TOOLS/assemble-streams.bash -t $WORKSPACE/ $VERSION $STREAMS
PUBLISH_ARGS="testing $STREAMS/juju-dist/testing cpc"
$RELEASE_TOOLS/publish-public-tools.bash $PUBLISH_ARGS || \
    $RELEASE_TOOLS/publish-public-tools.bash $PUBLISH_ARGS || \
        $RELEASE_TOOLS/publish-public-tools.bash $PUBLISH_ARGS
