#!/bin/bash
set -eux

: ${LOCAL_JENKINS_URL=$JENKINS_URL}
TARFILE=$($SCRIPTS/get-tarfile-name)
VERSION=$(basename $TARBALL .tar.gz | cut -d '_' -f2)
wget -q $LOCAL_JENKINS_URL/job/build-revision/lastSuccessfulBuild/artifact/$TARFILE

# Make source packages for all supported series.
$RELEASE_TOOLS/make-source-packages.bash testing $TARFILE \
    'Curtis Hovey <curtis.hovey@canonical.com>'

# Load the credentials to create instances in ec2.
set +x
source $JUJU_HOME/ec2rc
set -x

# Build binary packages for select series.
for dsc in $(find . -name '*.dsc')
do
    series=$(echo "$dsc" | cut -d '~' -f 2 | cut -d '.' -f 1,2)
    if [[ $series == '12.04' ]]; then
        echo "Building precise amd64"
        $RELEASE_TOOLS/build-package-with-dsc.bash localhost '' $dsc
    elif [[ $series == '13.10' ]]; then
        echo "Skipping Saucy"
    elif [[ $series == '14.04' ]]; then
        if [[ -n ${PPC_SSH_OPTIONS:-} ]]; then
            echo "Building trusty ppc64"
            $RELEASE_TOOLS/build-package-with-dsc.bash ubuntu@stilson-07 \
                "$PPC_SSH_OPTIONS" $dsc
        else
            echo "Skipping trusty ppc64"
        fi
        echo "Building trusty amd64"
        $RELEASE_TOOLS/build-package-with-dsc.bash m1.large ami-018c9568 $dsc
        echo "Building trusty i386"
        $RELEASE_TOOLS/build-package-with-dsc.bash m1.medium ami-81dee0e8 $dsc
        if [[ -n ${ARM_SSH_OPTIONS:-} ]]; then
            echo "Building trusty arm64"
            $RELEASE_TOOLS/build-package-with-dsc.bash ubuntu@arm64vm \
                "$ARM_SSH_OPTIONS" $dsc
        else
            echo "Skipping trusty arm64"
        fi
    elif [[ $series == '14.10' ]]; then
        echo "Building utopic amd64"
        $RELEASE_TOOLS/build-package-with-dsc.bash m1.large ami-f83ad690 $dsc
    fi
done

# Copy packages to the top of workspace so that they will be archives.
for package in $(find . -name '*.deb'); do
    mv $package $WORKSPACE/
done

mkdir -p new-tools
$RELEASE_TOOLS/assemble-public-tools.bash -t $WORKSPACE/ $VERSION new-tools
$RELEASE_TOOLS/publish-public-tools.bash testing new-tools/juju-dist-testing cpc
