#!/bin/bash
source $SCRIPTS/common-startup.sh
if [ "$ENV" == "manual" ]; then
    prepare_manual
fi
# Do the deployment for upgrade testing.
: ${UPGRADE=false}
if [ $UPGRADE != "true" ]; then
    export PATH=$NEW_PATH
fi
JUJU_REPOSITORY=$HOME/repository $SCRIPTS/deploy_job.py
