#!/bin/bash
: ${SCRIPTS=$(readlink -f $(dirname $0))}
bash $SCRIPTS/common-startup.sh
set -eux
juju_path=$(readlink -f $(dirname $(find extracted-bin -name juju)))
cmd="deploy_job.py $juju_path $ENV $CHARM_PREFIX $WORKSPACE $JOB_NAME"
if [ "${UPGRADE-}" == "true" ]; then
  cmd="$cmd --upgrade"
fi
if [ "${DEBUG-}" == "true" ]; then
  cmd="$cmd --debug"
fi
if [ "${SERIES-}" != "" ]; then
  cmd="$cmd --series $SERIES"
fi
unset ENV CHARM_PREFIX WORKSPACE UPGRADE SERIES
$cmd
