#!/bin/bash

# IMPORTANT: The ssh options are always remapped to $@ which preserves
# their tokenisation.

set -eux
: ${LOCAL_JENKINS_URL=$JENKINS_URL}
ssh_options='-o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null"'
remote_user="ubuntu"

if [[ $1 =~ .*@.* ]]; then
    is_ephemeral="false"
    remote_user=$(echo $1 | cut -d @ -f1)
    instance_name=$(echo $1 | cut -d @ -f2)
    shift
    eval "set -- $ssh_options $@"
else
    is_ephemeral="true"
    export INSTANCE_TYPE=$1
    export AMI_IMAGE=$2
    eval "set -- $ssh_options"
fi

if [[ $is_ephemeral == "true" ]]; then
    instance_id=$($SCRIPTS/ec2-run-instance-get-id)
    $SCRIPTS/ec2-tag-job-instances $instance_id
    set +x
    echo Starting instance $instance_id
    instance_name=$($SCRIPTS/ec2-get-name $instance_id)
    echo Instance has ip $instance_name
    sleep 30
    $SCRIPTS/wait-for-port $instance_name 22
fi

# Define common vars for remote scripts; do not make them evalaute
# what is known in this script to ensure the logs line order is sane.
tarfile_path=$(find $HOME/jobs/build-revision/lastStable/archive/ -name juju-core*.tar.gz)
tarfile=$(basename $tarfile_path)
juju_version=$(basename $tarfile .tar.gz)

set -x
set +e
DEPS="build-essential bzr distro-info-data git-core mercurial zip rsyslog-gnutls"
ssh "$@" $remote_user@$instance_name  <<EOT
set -eux
sudo apt-get update
if [[ $is_ephemeral == "true" ]]; then
    sudo apt-get upgrade -y
fi
if [[ \$(apt-cache madison juju-mongodb) =~ .*juju-mongodb.* ]]; then
    juju_db="juju-mongodb"
else
    juju_db="mongodb-server"
fi
if [[ \$(uname -p) =~  .*x86|armel|armhf.* ]]; then
    juju_compiler="golang"
else
    juju_compiler="gccgo-4.9 gccgo-go"
fi
sudo apt-get install -y $DEPS \$juju_db \$juju_compiler
EOT

scp "$@" $tarfile_path $remote_user@$instance_name:~/

ssh "$@" $remote_user@$instance_name <<EOT
set -eux
if [[ ! -f ~/.ssh/id_rsa ]]; then
    ssh-keygen -t rsa -b 2048 -N "" -f ~/.ssh/id_rsa
fi
export GOPATH=\$HOME/$juju_version
if [[ -d \$GOPATH ]]; then
  rm -r \$GOPATH
fi
tar -xzvf $tarfile
cd \$GOPATH/src/launchpad.net/juju-core
bzr whoami 'J. Random Hacker <jrandom@example.org>'
make build
make install
make check
EOT
EXIT_STATUS=$?

set -e

if [[ $is_ephemeral == "true" ]]; then
    $SCRIPTS/ec2-terminate-job-instances
fi

exit $EXIT_STATUS
