#!/bin/bash
set -eux
: ${LOCAL_JENKINS_URL=$JENKINS_URL}
export INSTANCE_TYPE=$1
export AMI_IMAGE=$2
tarfile=$($SCRIPTS/get-tarfile-name $revision_build)
instance_id=$($SCRIPTS/ec2-run-instance-get-id)
set +x
echo Starting instance $instance_id
instance_ip=$($SCRIPTS/ec2-get-ip $instance_id)
echo Instance has ip $instance_ip
sleep 30
$SCRIPTS/wait-for-ssh $instance_ip
set -x
set +e
ssh ubuntu@$instance_ip -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" <<EOT
set -eux
ssh-keygen -t rsa -b 2048 -N "" -f ~/.ssh/id_rsa
wget -q $JENKINS_URL/job/build-revision/$revision_build/artifact/$tarfile
tar -xzvf $tarfile
export GOPATH=\$HOME/$(echo $tarfile|sed -r 's/(.*).tar.gz/\1/')
cd \$GOPATH/src/launchpad.net/juju-core
sudo apt-get update
sudo apt-get install -y build-essential
make install-dependencies
bzr whoami 'J. Random Hacker <jrandom@example.org>'
make check
EOT
EXIT_STATUS=$?
set -e
euca-terminate-instances $instance_id
exit $EXIT_STATUS
