name: juju
version: 2.2-alpha1
summary: juju client
description: Through the use of charms, juju provides you with shareable, re-usable, and repeatable expressions of devops best practices.
confinement: classic
grade: devel

apps:
  juju:
    command: bin/juju

parts:
  juju:
    plugin: godeps
    go-importpath: github.com/juju/juju
    source: https://github.com/juju/juju.git
    source-type: git
    build-packages: [gcc]
    source-branch: develop
    #If you want, you can target a tag instead of a branch
    #source-tag: juju-2.0.2
    prime:
    - -bin/filetoconst
    - -bin/winuserdata
    #If this version of juju will have public streams, you can remove the agent as well
    #- -bin/jujud
