#!/bin/bash
set -eux


usage() {
    echo "usage: $0 ADDRESS"
    echo "  ADDRESS: The IP or DNS address the windows test machine."
    echo "  --juju-home: The location of cloud-city and staging-juju-rsa."
    exit 1
}

INSTALL_JUJU="false"
while [[ "${1-}" != "" && $1 =~ ^-.*  ]]; do
    case $1 in
        --juju-home)
            shift
            JUJU_HOME=$(cd $1; pwd)
            ;;
        --help)
            usage
            ;;
    esac
    shift
done


test $# -eq 1 || usage

HOST="$1"
: ${SCRIPTS=$(readlink -f $(dirname $0))}
export PATH="$SCRIPTS:$PATH"

SSH_OPTIONS="-i $JUJU_HOME/staging-juju-rsa \
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

retry_ssh() {
    for attempt in $(seq 3); do
        $@
        EXIT_STATUS=$?
        if [[ $EXIT_STATUS != "255" ]]; then
            # SSH didn't fail.
            break
        fi
        echo "SSH attempt $attempt failed."
    done
}

set -x
installer=$(
    $SCRIPTS/jujuci.py get build-win-client 'juju-setup-*.exe' ./)
echo "Downloaded $installer"
retry_ssh scp $SSH_OPTIONS \
    $SCRIPTS/deploy_stack.py $SCRIPTS/jujupy.py $SCRIPTS/jujuconfig.py \
    $SCRIPTS/remote.py $SCRIPTS/substrate.py $SCRIPTS/utility.py \
    $SCRIPTS/get_ami.py $installer \
    Administrator@$HOST:/cygdrive/c/Users/Administrator/ci/
if [ $? -ne 0 ]; then
    exit 1
fi

set +e
retry_ssh ssh $SSH_OPTIONS Administrator@$HOST <<EOT
/cygdrive/c/Users/Administrator/ci/$installer /verysilent
juju version
juju destroy-environment --force -y test-win-client
python \\\\Users\\\\Administrator\\\\ci\\\\deploy_stack.py test-win-client
EOT
exit $EXIT_STATUS
