#!/bin/bash
set -eu
CURRENT_JUJU_CORE=$(dpkg-query --showformat '${Package}=${Version}\n' -W juju-core)
source $SCRIPTS/make-release-tarball.bash $REVNO $BRANCH
source $SCRIPTS/make-package-with-tarball.bash $TARFILE
sudo dpkg -i $PACKAGE
mkdir -p new-tools
source $SCRIPTS/assemble-public-tools.bash $PACKAGE new-tools
source $SCRIPTS/publish-public-tools.bash TESTING ./juju-dist-testing
EXIT_STATUS=0
if ! $SCRIPTS/deploy_stack.py $ENVS; then
  EXIT_STATUS=1
fi
sudo apt-get install -y --force-yes $CURRENT_JUJU_CORE
for env in $ENVS; do
    $SCRIPTS/destroy-environment $env
done
exit $EXIT_STATUS
