#!/bin/bash
source $SCRIPTS/common-startup.sh
# Do the deployment for upgrade testing.
export JUJU_REPOSITORY=$HOME/repository
CHARM_PREFIX=${CHARM_PREFIX:-}
if ! $SCRIPTS/deploy_stack.py --charm-prefix "$CHARM_PREFIX" $ENV; then
  dump_logs
  $SCRIPTS/destroy-environment $ENV
  exit 1
fi
EXIT_STATUS=0

PATH=$NEW_PATH $SCRIPTS/upgrade-juju $ENV || EXIT_STATUS=$?
if [ $EXIT_STATUS -eq 0 ]; then
  PATH=$NEW_PATH $SCRIPTS/wait_for_agent_update.py $ENV || EXIT_STATUS=$?
fi

if [ $EXIT_STATUS -ne 0 ]; then
  dump_logs
fi
$SCRIPTS/destroy-environment $ENV
exit $EXIT_STATUS
