#!/usr/bin/env python
from __future__ import print_function

__metaclass__ = type

import sys

from deploy_stack import upgrade_juju
import jujupy

def main():
    for env in sys.argv[1:]:
        environment = jujupy.Environment.from_config(env)
        upgrade_juju(environment)

if __name__ == '__main__':
    main()
