#!/bin/bash
set -eu
export JUJU_HOME=$HOME/juju-ci
dump_logs(){
  artifacts_path=$WORKSPACE/artifacts
  mkdir -p $artifacts_path
  log_path=${artifacts_path}/all-machines-${ENV}.log
  if juju --show-log scp -e $ENV -- -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -i $JUJU_HOME/staging-juju-rsa 0:/var/log/juju/all-machines.log $log_path; then
    gzip $log_path
  fi
}
export JUJU_HOME=$HOME/juju-ci
export PACKAGE=$WORKSPACE/new-version.deb
set -x
rm * -rf
artifact=localhost:8080/job/prepare-new-version/lastSuccessfulBuild/artifact
wget -q $artifact/new-version.deb
# Determine BRANCH and REVNO
wget -q $artifact/buildvars.bash
source buildvars.bash
echo "Testing $BRANCH $REVNO on $ENV"
dpkg-deb -x $PACKAGE extracted-bin
export NEW_PATH=$(dirname $(find extracted-bin -name juju)):$PATH
# Try to ensure a clean environment
$SCRIPTS/destroy-environment $ENV

# Do the deployment for upgrade testing.
if ! $SCRIPTS/deploy_stack.py $ENV; then
  dump_logs
  $SCRIPTS/destroy-environment $ENV
  exit 1
fi
EXIT_STATUS=0

PATH=$NEW_PATH $SCRIPTS/upgrade-juju $ENV || EXIT_STATUS=$?
PATH=$NEW_PATH $SCRIPTS/wait_for_agent_update.py $ENV || EXIT_STATUS=$?

if [ $EXIT_STATUS -ne 0 ]; then
  dump_logs
fi
$SCRIPTS/destroy-environment $ENV
exit $EXIT_STATUS
