#!/bin/bash
set -eu
export JUJU_HOME=$HOME/juju-ci
dump_logs(){
  artifacts_path=$WORKSPACE/artifacts
  mkdir -p $artifacts_path
  for env in $ENVS; do
    log_path=${artifacts_path}/all-machines-${env}.log
    if juju --show-log scp -e $env -- -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -i $JUJU_HOME/staging-juju-rsa 0:/var/log/juju/all-machines.log $log_path; then
      gzip $log_path
    fi
  done
}
export JUJU_HOME=$HOME/juju-ci
export PACKAGE=$WORKSPACE/new-precise.deb
set -x
rm * -rf
artifact=localhost:8080/job/prepare-new-version/lastSuccessfulBuild/artifact
wget -q $artifact/new-precise.deb
# Determine BRANCH and REVNO
wget -q $artifact/buildvars.bash
source buildvars.bash
echo "Testing $BRANCH $REVNO on $ENVS"
dpkg-deb -x $PACKAGE extracted-bin
export NEW_PATH=$(dirname $(find extracted-bin -name juju)):$PATH
# Try to ensure a clean environment
$SCRIPTS/destroy-environment $ENVS

# Do the deployment for upgrade testing.
if ! $SCRIPTS/deploy_stack.py $ENVS; then
  dump_logs
  $SCRIPTS/destroy-environment $ENVS
  exit 1
fi
EXIT_STATUS=0

PATH=$NEW_PATH PACKAGE=$WORKSPACE/new-precise.deb $SCRIPTS/test-new-version || EXIT_STATUS=$?
if [ $EXIT_STATUS -ne 0 ]; then
  dump_logs
fi
$SCRIPTS/destroy-environment $ENVS
exit $EXIT_STATUS
