#!/usr/bin/env python
__metaclass__ = type

import sys

import jujupy

def main():
    for env in sys.argv[1:]:
        environment = jujupy.Environment.from_config(env)
        #environment.set_testing_tools_metadata_url()
        environment.upgrade_juju()

if __name__ == '__main__':
    main()
