#!/bin/bash

export PATH=$PWD/plugin:$PATH

name=$(action-get name)
status-set maintenance "launch: launching $name"

result=$(launch "$name" 2>&1)
rc=$?
if [ "$rc" == "0" ]; then
    action-set output="$result"
else
    status-set maintenance "launch: [$name] failed ($rc - $result)"
fi
