#!/bin/bash

export PATH=$PWD/plugin:$PATH

name=$(action-get name)
status=$(action-get status)
status-set maintenance "set-status: setting status for $name to $status"

result=$(proc-status-set "$name" "$status" 2>&1)
rc=$?
if [ "$rc" != "0" ]; then
    status-set maintenance "set-status: [$name] failed ($rc - $result)"
fi
