"options":
  "external_url":
    "type": "string"
    "description": "The FQDN for your GitLab unit"
    "default": !!null ""
  "http_port":
    "type": "string"
    "description": "The HTTP port"
    "default": "80"
  "ssh_host":
    "type": "string"
    "description": "Override the SSH Hostname"
    "default": !!null ""
  "time_zone":
    "type": "string"
    "description": "Override the default timezone(UTC)"
    "default": !!null ""
  "email_from":
    "type": "string"
    "description": "Email address used in the from field in mails send by GitLab"
    "default": !!null ""
  "from_email_name":
    "type": "string"
    "description": "The Name Used in the From field"
    "default": !!null ""
  "reply_to_email":
    "type": "string"
    "description": "Override the reply to email address"
    "default": !!null ""
  "smtp_enable":
    "type": "boolean"
    "description": "Enable SMTP sending"
    "default": !!bool "true"
  "smtp_address":
    "type": "string"
    "description": "SMTP Address"
    "default": !!null ""
  "smtp_port":
    "type": "string"
    "description": "SMTP Port"
    "default": !!null ""
  "smtp_user_name":
    "type": "string"
    "description": "SMTP Username"
    "default": !!null ""
  "smtp_password":
    "type": "string"
    "description": "SMTP Password"
    "default": !!null ""
  "smtp_domain":
    "type": "string"
    "description": "SMTP Domain"
    "default": !!null ""
  "smtp_enable_starttls_auto":
    "type": "boolean"
    "description": "Enable STARTTLS automatically"
    "default": !!bool "true"
  "smtp_tls":
    "type": "boolean"
    "description": "SMTP TLS"
    "default": !!bool "false"
  "incoming_email_enabled":
    "type": "boolean"
    "description": "Accept incoming email"
    "default": !!bool "false"
  "incoming_email_address":
    "type": "string"
    "description": "The email address including the `%{key}` placeholder that will\
      \ be replaced to reference the item being replied to. The `+%{key}` placeholder\
      \ is added after the user part, after a `+` character, before the `@`."
    "default": !!null ""
  "incoming_email_email":
    "type": "string"
    "description": "Incoming email address"
    "default": !!null ""
  "incoming_email_password":
    "type": "string"
    "description": "Incoming email password"
    "default": !!null ""
  "incoming_email_host":
    "type": "string"
    "description": "Incoming Email Host"
    "default": !!null ""
  "incoming_email_port":
    "type": "string"
    "description": "Incoming Email Port"
    "default": !!null ""
  "incoming_email_ssl":
    "type": "boolean"
    "description": "Incoming Email SSL"
    "default": !!bool "true"
  "incoming_email_start_tls":
    "type": "boolean"
    "description": "Incoming Email Start TLS"
    "default": !!bool "false"
  "incoming_email_mailbox_name":
    "type": "string"
    "description": "Incoming mailbox name"
    "default": !!null ""
