// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver (interfaces: ResourceServiceGetter,ResourceService)
//
// Generated by this command:
//
//	mockgen -typed -package apiserver -destination resource_service_mock_test.go github.com/juju/juju/apiserver ResourceServiceGetter,ResourceService
//

// Package apiserver is a generated GoMock package.
package apiserver

import (
	context "context"
	http "net/http"
	reflect "reflect"

	resource "github.com/juju/juju/core/resource"
	unit "github.com/juju/juju/core/unit"
	resource0 "github.com/juju/juju/domain/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceServiceGetter is a mock of ResourceServiceGetter interface.
type MockResourceServiceGetter struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServiceGetterMockRecorder
}

// MockResourceServiceGetterMockRecorder is the mock recorder for MockResourceServiceGetter.
type MockResourceServiceGetterMockRecorder struct {
	mock *MockResourceServiceGetter
}

// NewMockResourceServiceGetter creates a new mock instance.
func NewMockResourceServiceGetter(ctrl *gomock.Controller) *MockResourceServiceGetter {
	mock := &MockResourceServiceGetter{ctrl: ctrl}
	mock.recorder = &MockResourceServiceGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceServiceGetter) EXPECT() *MockResourceServiceGetterMockRecorder {
	return m.recorder
}

// Resource mocks base method.
func (m *MockResourceServiceGetter) Resource(arg0 *http.Request) (ResourceService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resource", arg0)
	ret0, _ := ret[0].(ResourceService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resource indicates an expected call of Resource.
func (mr *MockResourceServiceGetterMockRecorder) Resource(arg0 any) *MockResourceServiceGetterResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resource", reflect.TypeOf((*MockResourceServiceGetter)(nil).Resource), arg0)
	return &MockResourceServiceGetterResourceCall{Call: call}
}

// MockResourceServiceGetterResourceCall wrap *gomock.Call
type MockResourceServiceGetterResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceGetterResourceCall) Return(arg0 ResourceService, arg1 error) *MockResourceServiceGetterResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceGetterResourceCall) Do(f func(*http.Request) (ResourceService, error)) *MockResourceServiceGetterResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceGetterResourceCall) DoAndReturn(f func(*http.Request) (ResourceService, error)) *MockResourceServiceGetterResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockResourceService is a mock of ResourceService interface.
type MockResourceService struct {
	ctrl     *gomock.Controller
	recorder *MockResourceServiceMockRecorder
}

// MockResourceServiceMockRecorder is the mock recorder for MockResourceService.
type MockResourceServiceMockRecorder struct {
	mock *MockResourceService
}

// NewMockResourceService creates a new mock instance.
func NewMockResourceService(ctrl *gomock.Controller) *MockResourceService {
	mock := &MockResourceService{ctrl: ctrl}
	mock.recorder = &MockResourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceService) EXPECT() *MockResourceServiceMockRecorder {
	return m.recorder
}

// GetApplicationResourceID mocks base method.
func (m *MockResourceService) GetApplicationResourceID(arg0 context.Context, arg1 resource0.GetApplicationResourceIDArgs) (resource.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApplicationResourceID", arg0, arg1)
	ret0, _ := ret[0].(resource.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApplicationResourceID indicates an expected call of GetApplicationResourceID.
func (mr *MockResourceServiceMockRecorder) GetApplicationResourceID(arg0, arg1 any) *MockResourceServiceGetApplicationResourceIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApplicationResourceID", reflect.TypeOf((*MockResourceService)(nil).GetApplicationResourceID), arg0, arg1)
	return &MockResourceServiceGetApplicationResourceIDCall{Call: call}
}

// MockResourceServiceGetApplicationResourceIDCall wrap *gomock.Call
type MockResourceServiceGetApplicationResourceIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceGetApplicationResourceIDCall) Return(arg0 resource.UUID, arg1 error) *MockResourceServiceGetApplicationResourceIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceGetApplicationResourceIDCall) Do(f func(context.Context, resource0.GetApplicationResourceIDArgs) (resource.UUID, error)) *MockResourceServiceGetApplicationResourceIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceGetApplicationResourceIDCall) DoAndReturn(f func(context.Context, resource0.GetApplicationResourceIDArgs) (resource.UUID, error)) *MockResourceServiceGetApplicationResourceIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetResource mocks base method.
func (m *MockResourceService) GetResource(arg0 context.Context, arg1 resource.UUID) (resource0.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResource", arg0, arg1)
	ret0, _ := ret[0].(resource0.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource.
func (mr *MockResourceServiceMockRecorder) GetResource(arg0, arg1 any) *MockResourceServiceGetResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockResourceService)(nil).GetResource), arg0, arg1)
	return &MockResourceServiceGetResourceCall{Call: call}
}

// MockResourceServiceGetResourceCall wrap *gomock.Call
type MockResourceServiceGetResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceGetResourceCall) Return(arg0 resource0.Resource, arg1 error) *MockResourceServiceGetResourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceGetResourceCall) Do(f func(context.Context, resource.UUID) (resource0.Resource, error)) *MockResourceServiceGetResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceGetResourceCall) DoAndReturn(f func(context.Context, resource.UUID) (resource0.Resource, error)) *MockResourceServiceGetResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetUnitResource mocks base method.
func (m *MockResourceService) SetUnitResource(arg0 context.Context, arg1 resource.UUID, arg2 unit.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUnitResource", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUnitResource indicates an expected call of SetUnitResource.
func (mr *MockResourceServiceMockRecorder) SetUnitResource(arg0, arg1, arg2 any) *MockResourceServiceSetUnitResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUnitResource", reflect.TypeOf((*MockResourceService)(nil).SetUnitResource), arg0, arg1, arg2)
	return &MockResourceServiceSetUnitResourceCall{Call: call}
}

// MockResourceServiceSetUnitResourceCall wrap *gomock.Call
type MockResourceServiceSetUnitResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceSetUnitResourceCall) Return(arg0 error) *MockResourceServiceSetUnitResourceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceSetUnitResourceCall) Do(f func(context.Context, resource.UUID, unit.UUID) error) *MockResourceServiceSetUnitResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceSetUnitResourceCall) DoAndReturn(f func(context.Context, resource.UUID, unit.UUID) error) *MockResourceServiceSetUnitResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StoreResource mocks base method.
func (m *MockResourceService) StoreResource(arg0 context.Context, arg1 resource0.StoreResourceArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreResource", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreResource indicates an expected call of StoreResource.
func (mr *MockResourceServiceMockRecorder) StoreResource(arg0, arg1 any) *MockResourceServiceStoreResourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreResource", reflect.TypeOf((*MockResourceService)(nil).StoreResource), arg0, arg1)
	return &MockResourceServiceStoreResourceCall{Call: call}
}

// MockResourceServiceStoreResourceCall wrap *gomock.Call
type MockResourceServiceStoreResourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResourceServiceStoreResourceCall) Return(arg0 error) *MockResourceServiceStoreResourceCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResourceServiceStoreResourceCall) Do(f func(context.Context, resource0.StoreResourceArgs) error) *MockResourceServiceStoreResourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResourceServiceStoreResourceCall) DoAndReturn(f func(context.Context, resource0.StoreResourceArgs) error) *MockResourceServiceStoreResourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
