options:
  strdefault:
    default: "charm default"
    description: A string setting for charm with some default value.
    type: string
  strnodefault:
    description: A string settings for charm with no default value.
    type: string
  stroverwrite:
    default: "overwrite me"
    description: A string settings for charm with some default value to be overwritten at application deploy.
    type: string
  intdefault:
    default: 42
    description: An int setting for charm with some default value.
    type: int
  intnodefault:
    description: An int settings for charm with no default value.
    type: int
  intoverwrite:
    default: 111
    description: An int settings for charm with some default value to be overwritten at application deploy.
    type: int
  floatdefault:
    default: 4.2
    description: A float setting for charm with some default value.
    type: float
  floatnodefault:
    description: A float settings for charm with no default value.
    type: float
  floatoverwrite:
    default: 11.1
    description: A float settings for charm with some default value to be overwritten at application deploy.
    type: float
  booleandefault:
    default: true
    description: A boolean setting for charm with some default value.
    type: boolean
  booleannodefault:
    description: A boolean settings for charm with no default value.
    type: boolean
  booleanoverwrite:
    default: true
    description: A boolean settings for charm with some default value to be overwritten at application deploy.
    type: boolean
