#!/bin/bash

memcache_host=`relation-get private-address`
memcache_port=`relation-get port`
memcache_port=${memcache_port:-11211}

rm -f .memcache

cat > .memcache <<EOF
#!/bin/bash
CACHE_HOST=$memcache_host
CACHE_PORT=$memcache_port

EOF

source hooks/config-changed
