#!/bin/bash

set -xe

add-apt-repository ppa:charmers/charm-helpers
apt-get update && apt-get -y upgrade

apt-get -y install php5-memcache mysql-client pwgen php5 php5-fpm \
	php-apc mailutils php-mail sysstat php5-mysql php5-mcrypt php5-memcache \
	charm-helper-sh php5-curl rsync nfs-common git-core mktemp

modprobe nfs || true

juju-log "Making /mnt/tmp dir ..."
mkdir -p /mnt/tmp
chmod 1777 /mnt/tmp

juju-log "Making /mnt/logs ..."
mkdir -p /mnt/logs/php-fpm
chmod -R 1777 /mnt/logs

## dont make this an actual ramdisk until later when size can be safely tested
## just using plain disk cache for now
juju-log "Making Ramdisk mount point and config ..."
mkdir -p /mnt/ramdisk/proxy-cache
mkdir -p /mnt/ramdisk/phpfpm-cache
chmod -R 1777 /mnt/ramdisk

juju-log "Installing PHP-FPM pool configs ..."
rm -f /etc/php5/fpm/pool.d/*
install -o root -g root -m 0644 files/charm/php/php5-fpm_pool.d_www.conf /etc/php5/fpm/pool.d/www.conf
rsync -az /var/lib/php5 /mnt/ && rm -rf /var/lib/php5 && ln -s /mnt/php5 /var/lib/

juju-log "Creating random secret key ..."
if [ ! -f .wp-secret ]; then
	pwgen -s 10 1 > .wp-secret
fi

juju-log "Installing wp-cli to make this charm's life a little easier ..."
git clone https://github.com/wp-cli/wp-cli.git /usr/src/wp-cli
# other hooks call hooks/install and don't expect the CWD to change so
# run this section in a subshell
(
	cd /usr/src/wp-cli
	# 20120926: v0.6.0 is confirmed working, so use it rather than alpha.
	git reset --hard v0.6.0
	git submodule update --init
	utils/dev-build
)

juju-log "So, environment is setup. We'll wait for some hooks to fire off before we get all crazy"
