#!/bin/sh
echo $0

remote_unit=$(echo $JUJU_REMOTE_UNIT)
departing_unit=$(echo $JUJU_DEPARTING_UNIT)

if [ "${remote_unit}" = "${departing_unit}" ]; then
  echo "Remote unit ${remote_unit} is departing the relation"
else
  echo "Local unit is departing the relation"
fi
