options:
  proposed-packages:
    type: string
    default: ''
    description: |
      A space-separated list of packages to install from the proposed archive.
      they will be installed using apt-get install -r.
  extra-no-proxy:
    type: string
    default: ''
    description: |
      A space-separated list of extra sites to not proxy. localhost and the
      lxd bridge are always in the no-proxy list.
