#!/bin/bash
set -eux

message="$(config-get message)"
broken="$(config-get broken)"

if [ -z "$message" ] ; then
  message="use juju config to set message"
fi

status-set "active" "$message"

if [ "$broken" == "True" ] ; then
  exit 1
fi
