options:
  port:
    type: int
    default: 3128
    description: The port to listen for proxy requests.
  sitenames:
    type: string
    default: ''
    description: |
      A space separated list of domains to proxy. eg ubuntu.org canonical.com.
      When unset, all sites are proxied.
