#!/bin/bash
set -eux

status-set maintenance "Installing" || true
apt-get install -y squid3 squidclient

# Reassemble the conf so that the charms rules take precedence.
status-set maintenance "Connecting forwardproxy.conf" || true
echo "http_port 3129" > /etc/squid/forwardproxy.conf
mv /etc/squid/squid.conf /etc/squid/squid.conf.orig
echo "include /etc/squid/forwardproxy.conf" > /etc/squid/squid.conf
cat /etc/squid/squid.conf.orig | sed -e 's/^http_port/#http_port/' >> /etc/squid/squid.conf
service squid restart || service squid start
status-set maintenance "Installed" || true
