#!/bin/bash
num_entries=$1
key_len=$2
val_len=$3

echo "attempting to write a payload with ${num_entries} entries where keys have length ${key_len} and values have length ${val_len}"
(
  for key in `seq -f"%0${key_len}g" 1 ${num_entries}`; do
    echo "  ${key}: "`head -c ${val_len} /dev/zero | tr '\0' 'a'`;
  done;
) | state-set --file -
