options:
  lp-key:
    type: string
    default: ""
    description: "SSH key for accessing private code on launchpad."
  s3-proxy:
    type: string
    default: ""
    description: "Route s3 calls though a proxy. eg squid.internal:3128"

