#!/usr/bin/php
<?php
require_once('/usr/share/mediawiki/includes/Defines.php');
if ( file_exists('/etc/mediawiki/LocalSettings.php')
	&& file_exists('/etc/mediawiki/slaves.data')
) {
	$IP = '/usr/share/mediawiki';
	define('MEDIAWIKI', 1);
	chdir($IP);
	require('/etc/mediawiki/LocalSettings.php');
	$dbservers = array (
		array (
			'host'      => $wgDBserver,
			'dbname'    => $wgDBname,
			'user'      => $wgDBuser,
			'password'  => $wgDBpassword,
			'type'      => $wgDBtype,
			'flags'     => DBO_DEFAULT,
			'load'      => 0
		)
	);

	$arr = unserialize(file_get_contents('/etc/mediawiki/slaves.data'));
	$total_dbservers = array_merge($dbservers, $arr);
	$content = '<?php $wgDBservers = ' . var_export($total_dbservers, TRUE) . ';';
} else {
	$content = '<?php $wgDBservers = FALSE;';
}

# should be 0640 or rw-r-----
umask(0027);
file_put_contents('/etc/mediawiki/dbservers.php', $content);
chgrp('/etc/mediawiki/dbservers.php', 'www-data');
