#!/bin/sh
set -eux

status-set maintenance "Configuring Mediawiki"

wikiname=`config-get name`
skin=`config-get skin`
logo=`config-get logo`
admins=`config-get admins`
server_address=`config-get server_address`

if [ "`config-get --format json use_suffix`" = "true" ] ; then
    # Change root from /usr/share/mediawiki /to var/www
    imagepath="/var/www/images"
    scriptpath="/mediawiki"
else
    # Change root from /var/www to /usr/share/mediawiki
    imagepath="/usr/share/mediawiki/images"
    scriptpath=""
fi

if [ -n "$logo" ] ; then
    wgLogo=$(
    dldir=`mktemp -d logodir.XXXXXXXX`
    cd $dldir
    if wget $logo ; then
        file=`ls`
        mkdir -p $imagepath
        mv $file $imagepath
        chmod a+rx $imagepath
        chgrp www-data $imagepath/$file
        chmod g+r $imagepath/$file

        echo "/images/$file"
    fi
    cd /
    rm -rf $dldir
    )
fi

new_file=`mktemp /etc/mediawiki/config-settings.XXXXXXXXX.php`

if [ -n "$logo" ] ; then
    wgLogo="'$wgLogo'"
else
    wgLogo="null"
fi

cat > $new_file <<EOF
<?php
\$wgSitename="${wikiname}";
\$wgDefaultSkin="${skin}";
\$wgScriptPath="${scriptpath}";
\$wgLogo=$wgLogo;
EOF

if [ -n "$server_address" ] ; then
    echo "\$wgServer=\"${server_address}\";" >> $new_file
fi

if [ "`config-get --format json debug`" = "true" ] ; then
    cat >> $new_file <<EOF
\$wgDebugLogFile = "$CHARM_DIR/debug.log";
\$wgDebugComments = true;
\$wgShowExceptionDetails = true;
\$wgShowSQLErrors = true;
\$wgDebugDumpSql = true;
\$wgShowDBErrorBacktrace = true;
EOF
fi

chmod 0640 $new_file
chgrp www-data $new_file

cfile=/etc/mediawiki/config-settings.php
[ ! -f $cfile ] || mv -f $cfile $cfile.old
mv $new_file $cfile
[ ! -f $cfile.old ] || rm $cfile.old

cd /usr/share/mediawiki/maintenance

#added to prevent failure when no db relationship exists
if [ -f /etc/mediawiki/LocalSettings.php ]; then
    for admin in $admins ; do
        user=`echo $admin | cut -d: -f1`
        pass=`echo $admin | cut -d: -f2`
        # createAndPromote.php will exit non-zero if the user already exists.
        # Since this hook is set -e, it would exit immediately unless we used
        # ' || true' at the end. This lets us properly inform the user of the
        # error, versus having a failed config-changed hook with no message.
        user_count=`php createAndPromote.php --conf /etc/mediawiki/LocalSettings.php $user $pass 2>&1 | grep -c "account exists" || true`
        if [ $user_count -gt 0 ] ; then
            echo "ERROR: $user account already exists"
            exit 1
        fi
    done
fi

# Make sure any use_suffix changes are applied
service apache2 reload

application-version-set $(dpkg -s mediawiki | grep '^Version:' | awk -F':' '{print $3}' | cut -d+ -f1)

if [ -f "${CHARM_DIR}/db-connected" ]; then
    status-set active "Ready"
else
    status-set blocked "Database required"
fi

$CHARM_DIR/hooks/start
