#!/bin/bash

set -uxe

DISTRIB_CODENAME=$(lsb_release -cs)

status-set maintenance "Installing packages"

apt-get update -qq
apt-get --no-install-recommends -y -q install mediawiki php5-cli postfix python-mysqldb pwgen

# a bit hacky -- makes sure its there even if memcached is never related
touch /etc/mediawiki/memcached_settings.php
chmod 0644 /etc/mediawiki/memcached_settings.php
touch /etc/mediawiki/dbservers.php
chmod 0644 /etc/mediawiki/dbservers.php

[[ trusty == "$DISTRIB_CODENAME" ]] && a2enconf mediawiki || true

[[ precise == $DISTRIB_CODENAME ]] && \
    sed -i 's/\/var\/www/\/usr\/share\/mediawiki/' \
            /etc/apache2/sites-enabled/000-default || true
[[ trusty == $DISTRIB_CODENAME ]] && \
    sed -i 's/\/var\/www\/html/\/usr\/share\/mediawiki/' \
            /etc/apache2/sites-enabled/000-default.conf || true
