#!/usr/bin/php
<?php
require_once '/usr/share/mediawiki/includes/Defines.php';
$nodes = array();
$ret = 0;
exec('relation-list',$units,$ret);

if ( $ret ) {
	print 'relation-list failed\n';
	exit($ret);
}

global $argv;
if ( $argv[0] == 'slave-relation-departed' ) {
	$departing = getenv('JUJU_REMOTE_UNIT');
	echo "Filtering out departing node $departing\n";
	$newunits = array();
	foreach ( $units as $node ) {
		if ( trim($node) != trim($departing) ) {
		   $newunits[]=$node;
		}
	}
	$units = $newunits;
}

$dbservers = array();
foreach ( $units as $node ) {
	$relout = popen("relation-get --format json - $node", 'r');
	$json = stream_get_contents($relout);
	$node = json_decode($json);
	if ( $node->slave == 'True' ) {
		$dbservers[] = array(
			'host'      => $node->{'private-address'},
			'dbname'    => $node->database,
			'user'      => $node->user,
			'password'  => $node->password,
			'type'      => 'mysql',
			'load'      => 1,
			'flags'     => DBO_DEFAULT
		);
	}
}

if ( count($dbservers) < 1 ) {
	@unlink('/etc/mediawiki/slaves.data');
	exit(0);
}

# This file is only for root, desired mode is 0600
umask(0077);
file_put_contents('/etc/mediawiki/slaves.data', serialize($dbservers));
$home = dirname(__FILE__);
exec($home . '/combine-dbservers');
