#!/bin/bash

export PATH=$PWD/plugin:$PATH
ACTIVE_FILE=$PWD/.active

if [ -e $ACTIVE_FILE ]; then
    status-set maintenance "reading active file ($ACTIVE_FILE)"
    name=$(cat $ACTIVE_FILE)

    status-set maintenance "launching ${name}..."
    result=$(launch "$name" 2>&1)
    rc=$?
    if [ "$rc" = "0" ]; then
        status-set active "workload process ${name} launched ($result)"
    else
        status-set waiting "workload process ${name} failed to launch ($rc - $result)"
        rm $ACTIVE_FILE
        exit $rc
    fi
else
    status-set blocked 'not active; skipping...'
fi
