// Copyright 2026 Canonical Ltd.
// Licensed under the AGPLv3, see LICENCE file for details.
//
// GENERATED FILE - DO NOT EDIT
//
// Generated from:
//   Juju Version:   3.6.20

package cloudcred

var attr = map[string]bool{
	"azure,interactive,application-name":                     true,
	"azure,interactive,role-definition-name":                 true,
	"azure,interactive,subscription-id":                      true,
	"azure,managed-identity,managed-identity-path":           true,
	"azure,managed-identity,subscription-id":                 true,
	"azure,service-principal-secret,application-id":          true,
	"azure,service-principal-secret,application-object-id":   true,
	"azure,service-principal-secret,application-password":    false,
	"azure,service-principal-secret,managed-subscription-id": true,
	"azure,service-principal-secret,subscription-id":         true,
	"dummy,userpass,password":                                false,
	"dummy,userpass,username":                                true,
	"ec2,access-key,access-key":                              true,
	"ec2,access-key,secret-key":                              false,
	"ec2,instance-role,instance-profile-name":                true,
	"equinix,access-key,api-token":                           false,
	"equinix,access-key,project-id":                          true,
	"gce,jsonfile,file":                                      true,
	"gce,oauth2,client-email":                                true,
	"gce,oauth2,client-id":                                   true,
	"gce,oauth2,private-key":                                 false,
	"gce,oauth2,project-id":                                  true,
	"gce,service-account,service-account":                    true,
	"kubernetes,certificate,ClientCertificateData":           true,
	"kubernetes,certificate,Token":                           false,
	"kubernetes,certificate,rbac-id":                         true,
	"kubernetes,clientcertificate,ClientCertificateData":     true,
	"kubernetes,clientcertificate,ClientKeyData":             false,
	"kubernetes,clientcertificate,rbac-id":                   true,
	"kubernetes,oauth2,Token":                                false,
	"kubernetes,oauth2,rbac-id":                              true,
	"kubernetes,oauth2withcert,ClientCertificateData":        true,
	"kubernetes,oauth2withcert,ClientKeyData":                false,
	"kubernetes,oauth2withcert,Token":                        false,
	"kubernetes,userpass,password":                           false,
	"kubernetes,userpass,username":                           true,
	"lxd,certificate,client-cert":                            false,
	"lxd,certificate,client-key":                             false,
	"lxd,certificate,server-cert":                            false,
	"lxd,interactive,trust-password":                         false,
	"lxd,interactive,trust-token":                            true,
	"maas,oauth1,maas-oauth":                                 false,
	"oci,httpsig,fingerprint":                                true,
	"oci,httpsig,key":                                        true,
	"oci,httpsig,pass-phrase":                                false,
	"oci,httpsig,region":                                     true,
	"oci,httpsig,tenancy":                                    true,
	"oci,httpsig,user":                                       true,
	"openstack,access-key,access-key":                        true,
	"openstack,access-key,secret-key":                        false,
	"openstack,access-key,tenant-id":                         true,
	"openstack,access-key,tenant-name":                       true,
	"openstack,access-key,version":                           true,
	"openstack,userpass,domain-name":                         true,
	"openstack,userpass,password":                            false,
	"openstack,userpass,project-domain-name":                 true,
	"openstack,userpass,tenant-id":                           true,
	"openstack,userpass,tenant-name":                         true,
	"openstack,userpass,user-domain-name":                    true,
	"openstack,userpass,username":                            true,
	"openstack,userpass,version":                             true,
	"vsphere,userpass,password":                              false,
	"vsphere,userpass,user":                                  true,
	"vsphere,userpass,vmfolder":                              true,
}
