#!/bin/bash

set -e

# Setup connection to master instance once set
url=$(relation-get url)

if [ "x$url" = "x" ]; then
	juju-log "Master hasn't exported its url yet, exiting..."
	exit 0
fi

# Set the slave hostname to match the juju unit
# in the jenkins master instance
slavehost=`echo ${JUJU_UNIT_NAME} | sed s,/,-,`

juju-log "Configuring jenkins-slave with $url..."
sed -i -e "s!^JENKINS_HOSTNAME.*!JENKINS_HOSTNAME=${slavehost}!" \
       -e "s!^#*JENKINS_URL.*!JENKINS_URL=${url}!" \
        /etc/default/jenkins-slave

juju-log "Restarting jenkins-slave..."
# Startup the jenkins-slave service
stop jenkins-slave 2>/dev/null || true
start jenkins-slave

test -d /var/run/jenkins || sudo mkdir /var/run/jenkins
/usr/share/jenkins/bin/download-slave.sh "$url"
