#!/bin/bash -eux

value="$(action-get value)"

if [ -z "${value}" ]; then
    action-set echo.value="${value}"
    action-set outcome="failure"
    action-fail "echo value can't be empty"
fi

action-set echo.value="${value}"
action-set outcome="success"
