#!/bin/bash
total_timeout="$(action-get total-timeout)"
pause_timeout="$(action-get pause-timeout)"
chaos_dir="$(config-get chaos-dir)"
action-set result-map.total-timeout="${total_timeout}"
action-set result-map.pause-timeout="${pause_timeout}"
action-set result-map.chaos-dir=="${chaos_dir}"

# Run the Chaos Monkey
cmd="python ${chaos_dir}/runner.py"
if [ ${total_timeout}X != X ]; then
    cmd+=" --total_timeout ${total_timeout}"
fi
if [ ${pause_timeout}X != X ]; then
    cmd+=" --pause_timeout ${pause_timeout}"
fi
cmd+=" > ${chaos_dir}/log/resutls.log 2>&1"
action-set result-map.runner-cmd="${cmd}"
eval ${cmd}
if [ $? != 0 ]; then
    action-fail "Non-zero exit code from: ${cmd}"
fi

# Stage the results.log for retrieval with 'juju action fetch'.
action-set result-map.results=$(cat ${chaos_dir}/log/resutls.log)
