#!/bin/bash -eux
monkey_id='*'
chaos_dir="$(config-get chaos-dir)"
action_chaos_dir="$(action-get chaos-dir)"
[[ -n ${action_chaos_dir:-} ]] && chaos_dir=${action_chaos_dir}
action-set action-parameters.chaos-dir="${chaos_dir}"

target_dir="${chaos_dir}/chaos_monkey.${monkey_id}"

for dir in ${target_dir}; do
    key=${dir##*\/chaos_monkey\.}
    [[ -d $dir ]] && action-set monkey-ids.${key}=${dir}
done
