// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/deployment/charm (interfaces: Charm)
//
// Generated by this command:
//
//	mockgen -package bootstrap -destination internal_charm_mock_test.go github.com/juju/juju/domain/deployment/charm Charm
//

// Package bootstrap is a generated GoMock package.
package bootstrap

import (
	gomock "github.com/canonical/gomock/gomock"
	charm "github.com/juju/juju/domain/deployment/charm"
)

// MockCharm is a mock of Charm interface.
type MockCharm struct {
	ctrl     *gomock.Controller
	recorder *MockCharmMockRecorder
	isgomock struct{}
}

// MockCharmMockRecorder is the mock recorder for MockCharm.
type MockCharmMockRecorder struct {
	mock            *MockCharm
	actionsExpects  []*gomock.Call0_1[*charm.Actions]
	configExpects   []*gomock.Call0_1[*charm.ConfigSpec]
	manifestExpects []*gomock.Call0_1[*charm.Manifest]
	metaExpects     []*gomock.Call0_1[*charm.Meta]
	revisionExpects []*gomock.Call0_1[int]
	versionExpects  []*gomock.Call0_1[string]
}

// NewMockCharm creates a new mock instance.
func NewMockCharm(ctrl *gomock.Controller) *MockCharm {
	mock := &MockCharm{ctrl: ctrl}
	mock.recorder = &MockCharmMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharm) EXPECT() *MockCharmMockRecorder {
	return m.recorder
}

// Actions mocks base method.
func (m *MockCharm) Actions() *charm.Actions {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.actionsExpects, m.ctrl, m, "Actions")
}

// Actions indicates an expected call of Actions.
func (mr *MockCharmMockRecorder) Actions() *MockCharmActionsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[*charm.Actions](mr.mock.ctrl.T, mr.mock, "Actions")
	mr.actionsExpects = append(mr.actionsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmActionsCall is the typed call wrapper for Actions.
type MockCharmActionsCall = gomock.Call0_1[*charm.Actions]

// Config mocks base method.
func (m *MockCharm) Config() *charm.ConfigSpec {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.configExpects, m.ctrl, m, "Config")
}

// Config indicates an expected call of Config.
func (mr *MockCharmMockRecorder) Config() *MockCharmConfigCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[*charm.ConfigSpec](mr.mock.ctrl.T, mr.mock, "Config")
	mr.configExpects = append(mr.configExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmConfigCall is the typed call wrapper for Config.
type MockCharmConfigCall = gomock.Call0_1[*charm.ConfigSpec]

// Manifest mocks base method.
func (m *MockCharm) Manifest() *charm.Manifest {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.manifestExpects, m.ctrl, m, "Manifest")
}

// Manifest indicates an expected call of Manifest.
func (mr *MockCharmMockRecorder) Manifest() *MockCharmManifestCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[*charm.Manifest](mr.mock.ctrl.T, mr.mock, "Manifest")
	mr.manifestExpects = append(mr.manifestExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmManifestCall is the typed call wrapper for Manifest.
type MockCharmManifestCall = gomock.Call0_1[*charm.Manifest]

// Meta mocks base method.
func (m *MockCharm) Meta() *charm.Meta {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.metaExpects, m.ctrl, m, "Meta")
}

// Meta indicates an expected call of Meta.
func (mr *MockCharmMockRecorder) Meta() *MockCharmMetaCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[*charm.Meta](mr.mock.ctrl.T, mr.mock, "Meta")
	mr.metaExpects = append(mr.metaExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmMetaCall is the typed call wrapper for Meta.
type MockCharmMetaCall = gomock.Call0_1[*charm.Meta]

// Revision mocks base method.
func (m *MockCharm) Revision() int {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.revisionExpects, m.ctrl, m, "Revision")
}

// Revision indicates an expected call of Revision.
func (mr *MockCharmMockRecorder) Revision() *MockCharmRevisionCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[int](mr.mock.ctrl.T, mr.mock, "Revision")
	mr.revisionExpects = append(mr.revisionExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmRevisionCall is the typed call wrapper for Revision.
type MockCharmRevisionCall = gomock.Call0_1[int]

// Version mocks base method.
func (m *MockCharm) Version() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.versionExpects, m.ctrl, m, "Version")
}

// Version indicates an expected call of Version.
func (mr *MockCharmMockRecorder) Version() *MockCharmVersionCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "Version")
	mr.versionExpects = append(mr.versionExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmVersionCall is the typed call wrapper for Version.
type MockCharmVersionCall = gomock.Call0_1[string]
