"options":
  "user":
    "type": "string"
    "description": "The database user name."
    "default": "admin"
  "password":
    "type": "string"
    "description": "The database user password."
    "default": "password"
  "database":
    "type": "string"
    "description": "The database name."
    "default": "database"
  "root_password":
    "type": "string"
    "description": "The database root password."
    "default": "root"
  "mysql_port":
    "type": "string"
    "description": "The mysql port"
    "default": "3306"
  "query-cache-type":
    "default": "OFF"
    "type": "string"
    "description": "Query cache is usually a good idea, but can hurt concurrency.\
      \ Valid values are \"OFF\", \"ON\", or \"DEMAND\". http://dev.mysql.com/doc/refman/5.1/en/server-system-variables.html#sysvar_query_cache_type"
  "query-cache-size":
    "default": !!int "0"
    "type": "int"
    "description": "Override the computed version from dataset-size. Still works if\
      \ query-cache-type is \"OFF\" since sessions can override the cache type setting\
      \ on their own."
