#!/bin/bash
set -x

export PATH=$PWD/plugin:$PATH

name=$(action-get name)
status-set maintenance "untrack: removing $name from Juju's state"

result=$(workload-untrack "$name" 2>&1)
#result=$(juju-workload-testing-plugin destroy "$name" 2>&1)
rc=$?
if [ "$rc" != "0" ]; then
    status-set maintenance "untrack: [$name] failed ($rc - $result)"
fi
