#!/bin/bash
set -x

echo "hello in config-changed"

if storage-list awesome-fs | grep -q . && \
   storage-list epic-fs | grep -q .; then
    status-set active "All storage attached"
else
    status-set waiting "Waiting for storage"
fi