// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/apiserver/authentication (interfaces: EntityAuthenticator,AgentPasswordService)
//
// Generated by this command:
//
//	mockgen -typed -package stateauthenticator -destination authentication_mock_test.go github.com/juju/juju/apiserver/authentication EntityAuthenticator,AgentPasswordService
//

// Package stateauthenticator is a generated GoMock package.
package stateauthenticator

import (
	context "context"
	reflect "reflect"

	authentication "github.com/juju/juju/apiserver/authentication"
	machine "github.com/juju/juju/core/machine"
	unit "github.com/juju/juju/core/unit"
	state "github.com/juju/juju/state"
	gomock "go.uber.org/mock/gomock"
)

// MockEntityAuthenticator is a mock of EntityAuthenticator interface.
type MockEntityAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockEntityAuthenticatorMockRecorder
}

// MockEntityAuthenticatorMockRecorder is the mock recorder for MockEntityAuthenticator.
type MockEntityAuthenticatorMockRecorder struct {
	mock *MockEntityAuthenticator
}

// NewMockEntityAuthenticator creates a new mock instance.
func NewMockEntityAuthenticator(ctrl *gomock.Controller) *MockEntityAuthenticator {
	mock := &MockEntityAuthenticator{ctrl: ctrl}
	mock.recorder = &MockEntityAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntityAuthenticator) EXPECT() *MockEntityAuthenticatorMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockEntityAuthenticator) Authenticate(arg0 context.Context, arg1 authentication.AuthParams) (state.Entity, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", arg0, arg1)
	ret0, _ := ret[0].(state.Entity)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockEntityAuthenticatorMockRecorder) Authenticate(arg0, arg1 any) *MockEntityAuthenticatorAuthenticateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockEntityAuthenticator)(nil).Authenticate), arg0, arg1)
	return &MockEntityAuthenticatorAuthenticateCall{Call: call}
}

// MockEntityAuthenticatorAuthenticateCall wrap *gomock.Call
type MockEntityAuthenticatorAuthenticateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEntityAuthenticatorAuthenticateCall) Return(arg0 state.Entity, arg1 bool, arg2 error) *MockEntityAuthenticatorAuthenticateCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEntityAuthenticatorAuthenticateCall) Do(f func(context.Context, authentication.AuthParams) (state.Entity, bool, error)) *MockEntityAuthenticatorAuthenticateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEntityAuthenticatorAuthenticateCall) DoAndReturn(f func(context.Context, authentication.AuthParams) (state.Entity, bool, error)) *MockEntityAuthenticatorAuthenticateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAgentPasswordService is a mock of AgentPasswordService interface.
type MockAgentPasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentPasswordServiceMockRecorder
}

// MockAgentPasswordServiceMockRecorder is the mock recorder for MockAgentPasswordService.
type MockAgentPasswordServiceMockRecorder struct {
	mock *MockAgentPasswordService
}

// NewMockAgentPasswordService creates a new mock instance.
func NewMockAgentPasswordService(ctrl *gomock.Controller) *MockAgentPasswordService {
	mock := &MockAgentPasswordService{ctrl: ctrl}
	mock.recorder = &MockAgentPasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentPasswordService) EXPECT() *MockAgentPasswordServiceMockRecorder {
	return m.recorder
}

// MatchesMachinePasswordHashWithNonce mocks base method.
func (m *MockAgentPasswordService) MatchesMachinePasswordHashWithNonce(arg0 context.Context, arg1 machine.Name, arg2, arg3 string) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchesMachinePasswordHashWithNonce", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MatchesMachinePasswordHashWithNonce indicates an expected call of MatchesMachinePasswordHashWithNonce.
func (mr *MockAgentPasswordServiceMockRecorder) MatchesMachinePasswordHashWithNonce(arg0, arg1, arg2, arg3 any) *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchesMachinePasswordHashWithNonce", reflect.TypeOf((*MockAgentPasswordService)(nil).MatchesMachinePasswordHashWithNonce), arg0, arg1, arg2, arg3)
	return &MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall{Call: call}
}

// MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall wrap *gomock.Call
type MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall) Return(arg0, arg1 bool, arg2 error) *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall) Do(f func(context.Context, machine.Name, string, string) (bool, bool, error)) *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall) DoAndReturn(f func(context.Context, machine.Name, string, string) (bool, bool, error)) *MockAgentPasswordServiceMatchesMachinePasswordHashWithNonceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MatchesUnitPasswordHash mocks base method.
func (m *MockAgentPasswordService) MatchesUnitPasswordHash(arg0 context.Context, arg1 unit.Name, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchesUnitPasswordHash", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchesUnitPasswordHash indicates an expected call of MatchesUnitPasswordHash.
func (mr *MockAgentPasswordServiceMockRecorder) MatchesUnitPasswordHash(arg0, arg1, arg2 any) *MockAgentPasswordServiceMatchesUnitPasswordHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchesUnitPasswordHash", reflect.TypeOf((*MockAgentPasswordService)(nil).MatchesUnitPasswordHash), arg0, arg1, arg2)
	return &MockAgentPasswordServiceMatchesUnitPasswordHashCall{Call: call}
}

// MockAgentPasswordServiceMatchesUnitPasswordHashCall wrap *gomock.Call
type MockAgentPasswordServiceMatchesUnitPasswordHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentPasswordServiceMatchesUnitPasswordHashCall) Return(arg0 bool, arg1 error) *MockAgentPasswordServiceMatchesUnitPasswordHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentPasswordServiceMatchesUnitPasswordHashCall) Do(f func(context.Context, unit.Name, string) (bool, error)) *MockAgentPasswordServiceMatchesUnitPasswordHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentPasswordServiceMatchesUnitPasswordHashCall) DoAndReturn(f func(context.Context, unit.Name, string) (bool, error)) *MockAgentPasswordServiceMatchesUnitPasswordHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
