#!/bin/bash

install_success_file=/tmp/resolver.success

status_message="No install hook"
if [ -e ${install_success_file} ]; then
    status_message="Install hook succeeded"
fi

echo "${status_message}"
status-set active "${status_message}" || true
