#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 10
set controller_name [lindex $argv 1]
spawn juju login -u admin -c {*}$argv
match_max 100000
expect -exact "please enter password for admin on $controller_name: "
send -- "adminpass\r"
expect eof
