#!/usr/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 10
spawn juju change-user-password
match_max 100000
expect -exact "new password: "
send -- "adminpass\r"
expect -exact "\r
type new password again: "
send -- "adminpass\r"
expect eof
