#!/bin/bash

status-set maintenance 'Removing sshguard'
apt-get remove sshguard

status-set maintenance 'Starting webserver systemd process'

cat <<EOF >/etc/systemd/system/simple-server.service
[Unit]
Description=A simple webserver for Juju network tests

[Service]
ExecStart=${CHARM_DIR}/scripts/simple-server.py
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl start simple-server.service

open-port "8039/TCP"

status-set active
