#!/bin/bash
cd $JUJU_CHARM_DIR
pwd
mv "$(action-get filename)" dispatch
ls -la

# state operations are part of testing for the commit hook tool
state-get
state-delete one

action-set result-map.time-completed="$(date)" result-map.message="$(action-get filename) is now called dispatch"
action-set outcome="success"