#!/bin/bash

#TODO: Some of the python3 packs may not be available in precise.

sudo apt-get install python3-setuptools -y
sudo apt-add-repository ppa:juju/stable -y
sudo apt-get update

sudo apt-get install amulet python3 python3-requests python3-dev python3-pip -y
