// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/cmd/juju/application/deployer (interfaces: DeployerAPI,CharmReader,DeployConfigFlag)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/deploy_mock.go github.com/juju/juju/cmd/juju/application/deployer DeployerAPI,CharmReader,DeployConfigFlag
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	url "net/url"

	gomock "github.com/canonical/gomock/gomock"
	base "github.com/juju/juju/api/base"
	application "github.com/juju/juju/api/client/application"
	client "github.com/juju/juju/api/client/client"
	charm "github.com/juju/juju/api/common/charm"
	charms "github.com/juju/juju/api/common/charms"
	cmd "github.com/juju/juju/cmd/cmd"
	constraints "github.com/juju/juju/core/constraints"
	crossmodel "github.com/juju/juju/core/crossmodel"
	charm0 "github.com/juju/juju/domain/deployment/charm"
	resource "github.com/juju/juju/domain/deployment/charm/resource"
	params "github.com/juju/juju/rpc/params"
	names "github.com/juju/names/v6"
	httprequest "gopkg.in/httprequest.v1"
)

// MockDeployerAPI is a mock of DeployerAPI interface.
type MockDeployerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockDeployerAPIMockRecorder
	isgomock struct{}
}

// MockDeployerAPIMockRecorder is the mock recorder for MockDeployerAPI.
type MockDeployerAPIMockRecorder struct {
	mock                           *MockDeployerAPI
	aPICallExpects                 []*gomock.Call7_1[context.Context, string, int, string, string, any, any, error]
	addCharmExpects                []*gomock.Call4_2[context.Context, *charm0.URL, charm.Origin, bool, charm.Origin, error]
	addLocalCharmExpects           []*gomock.Call4_2[context.Context, *charm0.URL, charm0.Charm, bool, *charm0.URL, error]
	addMachinesExpects             []*gomock.Call2_2[context.Context, []params.AddMachineParams, []params.AddMachinesResult, error]
	addRelationExpects             []*gomock.Call3_2[context.Context, []string, []string, *params.AddRelationResults, error]
	addUnitsExpects                []*gomock.Call2_2[context.Context, application.AddUnitsParams, []string, error]
	applicationsInfoExpects        []*gomock.Call2_2[context.Context, []names.ApplicationTag, []params.ApplicationInfoResult, error]
	bakeryClientExpects            []*gomock.Call0_1[base.MacaroonDischarger]
	bestFacadeVersionExpects       []*gomock.Call1_1[string, int]
	charmInfoExpects               []*gomock.Call2_2[context.Context, string, *charms.CharmInfo, error]
	closeExpects                   []*gomock.Call0_1[error]
	connectControllerStreamExpects []*gomock.Call4_2[context.Context, string, url.Values, http.Header, base.Stream, error]
	connectStreamExpects           []*gomock.Call3_2[context.Context, string, url.Values, base.Stream, error]
	consumeExpects                 []*gomock.Call2_2[context.Context, crossmodel.ConsumeApplicationArgs, string, error]
	deployExpects                  []*gomock.Call2_1[context.Context, application.DeployArgs, error]
	deployFromRepositoryExpects    []*gomock.Call2_3[context.Context, application.DeployFromRepositoryArg, application.DeployInfo, []application.PendingResourceUpload, []error]
	exposeExpects                  []*gomock.Call3_1[context.Context, string, map[string]params.ExposedEndpoint, error]
	getAnnotationsExpects          []*gomock.Call2_2[context.Context, []string, []params.AnnotationsGetResult, error]
	getCharmURLOriginExpects       []*gomock.Call2_3[context.Context, string, *charm0.URL, charm.Origin, error]
	getConfigExpects               []*gomock.Call1V_2[context.Context, string, []map[string]any, error]
	getConstraintsExpects          []*gomock.Call1V_2[context.Context, string, []constraints.Value, error]
	getModelConstraintsExpects     []*gomock.Call1_2[context.Context, constraints.Value, error]
	grantOfferExpects              []*gomock.Call3V_1[context.Context, string, string, string, error]
	hTTPClientExpects              []*gomock.Call1_2[base.HTTPClientScope, *httprequest.Client, error]
	listCharmResourcesExpects      []*gomock.Call3_2[context.Context, string, charm.Origin, []resource.Resource, error]
	listSpacesExpects              []*gomock.Call1_2[context.Context, []params.Space, error]
	modelGetExpects                []*gomock.Call1_2[context.Context, map[string]any, error]
	modelTagExpects                []*gomock.Call0_2[names.ModelTag, bool]
	modelUUIDExpects               []*gomock.Call0_2[string, bool]
	offerExpects                   []*gomock.Call7_2[context.Context, string, string, []string, string, string, string, []params.ErrorResult, error]
	scaleApplicationExpects        []*gomock.Call2_2[context.Context, application.ScaleApplicationParams, params.ScaleApplicationResult, error]
	sequencesExpects               []*gomock.Call1_2[context.Context, map[string]int, error]
	setAnnotationExpects           []*gomock.Call2_2[context.Context, map[string]map[string]string, []params.ErrorResult, error]
	setCharmExpects                []*gomock.Call2_1[context.Context, application.SetCharmConfig, error]
	setConfigExpects               []*gomock.Call4_1[context.Context, string, string, map[string]string, error]
	setConstraintsExpects          []*gomock.Call3_1[context.Context, string, constraints.Value, error]
	simpleHTTPClientExpects        []*gomock.Call0_2[base.SimpleHTTPClient, error]
	statusExpects                  []*gomock.Call2_2[context.Context, *client.StatusArgs, *params.FullStatus, error]
}

// NewMockDeployerAPI creates a new mock instance.
func NewMockDeployerAPI(ctrl *gomock.Controller) *MockDeployerAPI {
	mock := &MockDeployerAPI{ctrl: ctrl}
	mock.recorder = &MockDeployerAPIMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeployerAPI) EXPECT() *MockDeployerAPIMockRecorder {
	return m.recorder
}

// APICall mocks base method.
func (m *MockDeployerAPI) APICall(ctx context.Context, objType string, version int, id, request string, arg5, response any) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch7_1(&m.recorder.aPICallExpects, m.ctrl, m, "APICall", ctx, objType, version, id, request, arg5, response)
}

// APICall indicates an expected call of APICall.
func (mr *MockDeployerAPIMockRecorder) APICall(ctx, objType, version, id, request, arg5, response any) *MockDeployerAPIAPICallCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall7_1[context.Context, string, int, string, string, any, any, error](mr.mock.ctrl.T, mr.mock, "APICall", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(objType), gomock.EnsureMatcher(version), gomock.EnsureMatcher(id), gomock.EnsureMatcher(request), gomock.EnsureMatcher(arg5), gomock.EnsureMatcher(response))
	mr.aPICallExpects = append(mr.aPICallExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIAPICallCall is the typed call wrapper for APICall.
type MockDeployerAPIAPICallCall = gomock.Call7_1[context.Context, string, int, string, string, any, any, error]

// AddCharm mocks base method.
func (m *MockDeployerAPI) AddCharm(arg0 context.Context, arg1 *charm0.URL, arg2 charm.Origin, arg3 bool) (charm.Origin, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_2(&m.recorder.addCharmExpects, m.ctrl, m, "AddCharm", arg0, arg1, arg2, arg3)
}

// AddCharm indicates an expected call of AddCharm.
func (mr *MockDeployerAPIMockRecorder) AddCharm(arg0, arg1, arg2, arg3 any) *MockDeployerAPIAddCharmCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_2[context.Context, *charm0.URL, charm.Origin, bool, charm.Origin, error](mr.mock.ctrl.T, mr.mock, "AddCharm", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1), gomock.EnsureMatcher(arg2), gomock.EnsureMatcher(arg3))
	mr.addCharmExpects = append(mr.addCharmExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIAddCharmCall is the typed call wrapper for AddCharm.
type MockDeployerAPIAddCharmCall = gomock.Call4_2[context.Context, *charm0.URL, charm.Origin, bool, charm.Origin, error]

// AddLocalCharm mocks base method.
func (m *MockDeployerAPI) AddLocalCharm(arg0 context.Context, arg1 *charm0.URL, arg2 charm0.Charm, arg3 bool) (*charm0.URL, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_2(&m.recorder.addLocalCharmExpects, m.ctrl, m, "AddLocalCharm", arg0, arg1, arg2, arg3)
}

// AddLocalCharm indicates an expected call of AddLocalCharm.
func (mr *MockDeployerAPIMockRecorder) AddLocalCharm(arg0, arg1, arg2, arg3 any) *MockDeployerAPIAddLocalCharmCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_2[context.Context, *charm0.URL, charm0.Charm, bool, *charm0.URL, error](mr.mock.ctrl.T, mr.mock, "AddLocalCharm", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1), gomock.EnsureMatcher(arg2), gomock.EnsureMatcher(arg3))
	mr.addLocalCharmExpects = append(mr.addLocalCharmExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIAddLocalCharmCall is the typed call wrapper for AddLocalCharm.
type MockDeployerAPIAddLocalCharmCall = gomock.Call4_2[context.Context, *charm0.URL, charm0.Charm, bool, *charm0.URL, error]

// AddMachines mocks base method.
func (m *MockDeployerAPI) AddMachines(ctx context.Context, machineParams []params.AddMachineParams) ([]params.AddMachinesResult, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.addMachinesExpects, m.ctrl, m, "AddMachines", ctx, machineParams)
}

// AddMachines indicates an expected call of AddMachines.
func (mr *MockDeployerAPIMockRecorder) AddMachines(ctx, machineParams any) *MockDeployerAPIAddMachinesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, []params.AddMachineParams, []params.AddMachinesResult, error](mr.mock.ctrl.T, mr.mock, "AddMachines", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(machineParams))
	mr.addMachinesExpects = append(mr.addMachinesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIAddMachinesCall is the typed call wrapper for AddMachines.
type MockDeployerAPIAddMachinesCall = gomock.Call2_2[context.Context, []params.AddMachineParams, []params.AddMachinesResult, error]

// AddRelation mocks base method.
func (m *MockDeployerAPI) AddRelation(ctx context.Context, endpoints, viaCIDRs []string) (*params.AddRelationResults, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.addRelationExpects, m.ctrl, m, "AddRelation", ctx, endpoints, viaCIDRs)
}

// AddRelation indicates an expected call of AddRelation.
func (mr *MockDeployerAPIMockRecorder) AddRelation(ctx, endpoints, viaCIDRs any) *MockDeployerAPIAddRelationCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, []string, []string, *params.AddRelationResults, error](mr.mock.ctrl.T, mr.mock, "AddRelation", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(endpoints), gomock.EnsureMatcher(viaCIDRs))
	mr.addRelationExpects = append(mr.addRelationExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIAddRelationCall is the typed call wrapper for AddRelation.
type MockDeployerAPIAddRelationCall = gomock.Call3_2[context.Context, []string, []string, *params.AddRelationResults, error]

// AddUnits mocks base method.
func (m *MockDeployerAPI) AddUnits(arg0 context.Context, arg1 application.AddUnitsParams) ([]string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.addUnitsExpects, m.ctrl, m, "AddUnits", arg0, arg1)
}

// AddUnits indicates an expected call of AddUnits.
func (mr *MockDeployerAPIMockRecorder) AddUnits(arg0, arg1 any) *MockDeployerAPIAddUnitsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, application.AddUnitsParams, []string, error](mr.mock.ctrl.T, mr.mock, "AddUnits", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.addUnitsExpects = append(mr.addUnitsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIAddUnitsCall is the typed call wrapper for AddUnits.
type MockDeployerAPIAddUnitsCall = gomock.Call2_2[context.Context, application.AddUnitsParams, []string, error]

// ApplicationsInfo mocks base method.
func (m *MockDeployerAPI) ApplicationsInfo(arg0 context.Context, arg1 []names.ApplicationTag) ([]params.ApplicationInfoResult, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.applicationsInfoExpects, m.ctrl, m, "ApplicationsInfo", arg0, arg1)
}

// ApplicationsInfo indicates an expected call of ApplicationsInfo.
func (mr *MockDeployerAPIMockRecorder) ApplicationsInfo(arg0, arg1 any) *MockDeployerAPIApplicationsInfoCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, []names.ApplicationTag, []params.ApplicationInfoResult, error](mr.mock.ctrl.T, mr.mock, "ApplicationsInfo", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.applicationsInfoExpects = append(mr.applicationsInfoExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIApplicationsInfoCall is the typed call wrapper for ApplicationsInfo.
type MockDeployerAPIApplicationsInfoCall = gomock.Call2_2[context.Context, []names.ApplicationTag, []params.ApplicationInfoResult, error]

// BakeryClient mocks base method.
func (m *MockDeployerAPI) BakeryClient() base.MacaroonDischarger {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.bakeryClientExpects, m.ctrl, m, "BakeryClient")
}

// BakeryClient indicates an expected call of BakeryClient.
func (mr *MockDeployerAPIMockRecorder) BakeryClient() *MockDeployerAPIBakeryClientCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[base.MacaroonDischarger](mr.mock.ctrl.T, mr.mock, "BakeryClient")
	mr.bakeryClientExpects = append(mr.bakeryClientExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIBakeryClientCall is the typed call wrapper for BakeryClient.
type MockDeployerAPIBakeryClientCall = gomock.Call0_1[base.MacaroonDischarger]

// BestFacadeVersion mocks base method.
func (m *MockDeployerAPI) BestFacadeVersion(facade string) int {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_1(&m.recorder.bestFacadeVersionExpects, m.ctrl, m, "BestFacadeVersion", facade)
}

// BestFacadeVersion indicates an expected call of BestFacadeVersion.
func (mr *MockDeployerAPIMockRecorder) BestFacadeVersion(facade any) *MockDeployerAPIBestFacadeVersionCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_1[string, int](mr.mock.ctrl.T, mr.mock, "BestFacadeVersion", gomock.EnsureMatcher(facade))
	mr.bestFacadeVersionExpects = append(mr.bestFacadeVersionExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIBestFacadeVersionCall is the typed call wrapper for BestFacadeVersion.
type MockDeployerAPIBestFacadeVersionCall = gomock.Call1_1[string, int]

// CharmInfo mocks base method.
func (m *MockDeployerAPI) CharmInfo(arg0 context.Context, arg1 string) (*charms.CharmInfo, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.charmInfoExpects, m.ctrl, m, "CharmInfo", arg0, arg1)
}

// CharmInfo indicates an expected call of CharmInfo.
func (mr *MockDeployerAPIMockRecorder) CharmInfo(arg0, arg1 any) *MockDeployerAPICharmInfoCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, *charms.CharmInfo, error](mr.mock.ctrl.T, mr.mock, "CharmInfo", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.charmInfoExpects = append(mr.charmInfoExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPICharmInfoCall is the typed call wrapper for CharmInfo.
type MockDeployerAPICharmInfoCall = gomock.Call2_2[context.Context, string, *charms.CharmInfo, error]

// Close mocks base method.
func (m *MockDeployerAPI) Close() error {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.closeExpects, m.ctrl, m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDeployerAPIMockRecorder) Close() *MockDeployerAPICloseCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[error](mr.mock.ctrl.T, mr.mock, "Close")
	mr.closeExpects = append(mr.closeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPICloseCall is the typed call wrapper for Close.
type MockDeployerAPICloseCall = gomock.Call0_1[error]

// ConnectControllerStream mocks base method.
func (m *MockDeployerAPI) ConnectControllerStream(ctx context.Context, path string, attrs url.Values, headers http.Header) (base.Stream, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_2(&m.recorder.connectControllerStreamExpects, m.ctrl, m, "ConnectControllerStream", ctx, path, attrs, headers)
}

// ConnectControllerStream indicates an expected call of ConnectControllerStream.
func (mr *MockDeployerAPIMockRecorder) ConnectControllerStream(ctx, path, attrs, headers any) *MockDeployerAPIConnectControllerStreamCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_2[context.Context, string, url.Values, http.Header, base.Stream, error](mr.mock.ctrl.T, mr.mock, "ConnectControllerStream", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(path), gomock.EnsureMatcher(attrs), gomock.EnsureMatcher(headers))
	mr.connectControllerStreamExpects = append(mr.connectControllerStreamExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIConnectControllerStreamCall is the typed call wrapper for ConnectControllerStream.
type MockDeployerAPIConnectControllerStreamCall = gomock.Call4_2[context.Context, string, url.Values, http.Header, base.Stream, error]

// ConnectStream mocks base method.
func (m *MockDeployerAPI) ConnectStream(ctx context.Context, path string, attrs url.Values) (base.Stream, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.connectStreamExpects, m.ctrl, m, "ConnectStream", ctx, path, attrs)
}

// ConnectStream indicates an expected call of ConnectStream.
func (mr *MockDeployerAPIMockRecorder) ConnectStream(ctx, path, attrs any) *MockDeployerAPIConnectStreamCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, url.Values, base.Stream, error](mr.mock.ctrl.T, mr.mock, "ConnectStream", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(path), gomock.EnsureMatcher(attrs))
	mr.connectStreamExpects = append(mr.connectStreamExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIConnectStreamCall is the typed call wrapper for ConnectStream.
type MockDeployerAPIConnectStreamCall = gomock.Call3_2[context.Context, string, url.Values, base.Stream, error]

// Consume mocks base method.
func (m *MockDeployerAPI) Consume(ctx context.Context, arg crossmodel.ConsumeApplicationArgs) (string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.consumeExpects, m.ctrl, m, "Consume", ctx, arg)
}

// Consume indicates an expected call of Consume.
func (mr *MockDeployerAPIMockRecorder) Consume(ctx, arg any) *MockDeployerAPIConsumeCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, crossmodel.ConsumeApplicationArgs, string, error](mr.mock.ctrl.T, mr.mock, "Consume", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(arg))
	mr.consumeExpects = append(mr.consumeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIConsumeCall is the typed call wrapper for Consume.
type MockDeployerAPIConsumeCall = gomock.Call2_2[context.Context, crossmodel.ConsumeApplicationArgs, string, error]

// Deploy mocks base method.
func (m *MockDeployerAPI) Deploy(arg0 context.Context, arg1 application.DeployArgs) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_1(&m.recorder.deployExpects, m.ctrl, m, "Deploy", arg0, arg1)
}

// Deploy indicates an expected call of Deploy.
func (mr *MockDeployerAPIMockRecorder) Deploy(arg0, arg1 any) *MockDeployerAPIDeployCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_1[context.Context, application.DeployArgs, error](mr.mock.ctrl.T, mr.mock, "Deploy", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.deployExpects = append(mr.deployExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIDeployCall is the typed call wrapper for Deploy.
type MockDeployerAPIDeployCall = gomock.Call2_1[context.Context, application.DeployArgs, error]

// DeployFromRepository mocks base method.
func (m *MockDeployerAPI) DeployFromRepository(ctx context.Context, arg application.DeployFromRepositoryArg) (application.DeployInfo, []application.PendingResourceUpload, []error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_3(&m.recorder.deployFromRepositoryExpects, m.ctrl, m, "DeployFromRepository", ctx, arg)
}

// DeployFromRepository indicates an expected call of DeployFromRepository.
func (mr *MockDeployerAPIMockRecorder) DeployFromRepository(ctx, arg any) *MockDeployerAPIDeployFromRepositoryCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_3[context.Context, application.DeployFromRepositoryArg, application.DeployInfo, []application.PendingResourceUpload, []error](mr.mock.ctrl.T, mr.mock, "DeployFromRepository", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(arg))
	mr.deployFromRepositoryExpects = append(mr.deployFromRepositoryExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIDeployFromRepositoryCall is the typed call wrapper for DeployFromRepository.
type MockDeployerAPIDeployFromRepositoryCall = gomock.Call2_3[context.Context, application.DeployFromRepositoryArg, application.DeployInfo, []application.PendingResourceUpload, []error]

// Expose mocks base method.
func (m *MockDeployerAPI) Expose(ctx context.Context, arg1 string, exposedEndpoints map[string]params.ExposedEndpoint) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.exposeExpects, m.ctrl, m, "Expose", ctx, arg1, exposedEndpoints)
}

// Expose indicates an expected call of Expose.
func (mr *MockDeployerAPIMockRecorder) Expose(ctx, arg1, exposedEndpoints any) *MockDeployerAPIExposeCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, map[string]params.ExposedEndpoint, error](mr.mock.ctrl.T, mr.mock, "Expose", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(arg1), gomock.EnsureMatcher(exposedEndpoints))
	mr.exposeExpects = append(mr.exposeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIExposeCall is the typed call wrapper for Expose.
type MockDeployerAPIExposeCall = gomock.Call3_1[context.Context, string, map[string]params.ExposedEndpoint, error]

// GetAnnotations mocks base method.
func (m *MockDeployerAPI) GetAnnotations(ctx context.Context, tags []string) ([]params.AnnotationsGetResult, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.getAnnotationsExpects, m.ctrl, m, "GetAnnotations", ctx, tags)
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockDeployerAPIMockRecorder) GetAnnotations(ctx, tags any) *MockDeployerAPIGetAnnotationsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, []string, []params.AnnotationsGetResult, error](mr.mock.ctrl.T, mr.mock, "GetAnnotations", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(tags))
	mr.getAnnotationsExpects = append(mr.getAnnotationsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIGetAnnotationsCall is the typed call wrapper for GetAnnotations.
type MockDeployerAPIGetAnnotationsCall = gomock.Call2_2[context.Context, []string, []params.AnnotationsGetResult, error]

// GetCharmURLOrigin mocks base method.
func (m *MockDeployerAPI) GetCharmURLOrigin(arg0 context.Context, arg1 string) (*charm0.URL, charm.Origin, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_3(&m.recorder.getCharmURLOriginExpects, m.ctrl, m, "GetCharmURLOrigin", arg0, arg1)
}

// GetCharmURLOrigin indicates an expected call of GetCharmURLOrigin.
func (mr *MockDeployerAPIMockRecorder) GetCharmURLOrigin(arg0, arg1 any) *MockDeployerAPIGetCharmURLOriginCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_3[context.Context, string, *charm0.URL, charm.Origin, error](mr.mock.ctrl.T, mr.mock, "GetCharmURLOrigin", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.getCharmURLOriginExpects = append(mr.getCharmURLOriginExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIGetCharmURLOriginCall is the typed call wrapper for GetCharmURLOrigin.
type MockDeployerAPIGetCharmURLOriginCall = gomock.Call2_3[context.Context, string, *charm0.URL, charm.Origin, error]

// GetConfig mocks base method.
func (m *MockDeployerAPI) GetConfig(ctx context.Context, appNames ...string) ([]map[string]any, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1V_2(&m.recorder.getConfigExpects, m.ctrl, m, "GetConfig", ctx, appNames...)
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockDeployerAPIMockRecorder) GetConfig(ctx any, appNames ...any) *MockDeployerAPIGetConfigCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(appNames))
	for i, a := range appNames {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall1V_2[context.Context, string, []map[string]any, error](mr.mock.ctrl.T, mr.mock, "GetConfig", gomock.EnsureMatcher(ctx), varArgs)
	mr.getConfigExpects = append(mr.getConfigExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIGetConfigCall is the typed call wrapper for GetConfig.
type MockDeployerAPIGetConfigCall = gomock.Call1V_2[context.Context, string, []map[string]any, error]

// GetConstraints mocks base method.
func (m *MockDeployerAPI) GetConstraints(ctx context.Context, appNames ...string) ([]constraints.Value, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1V_2(&m.recorder.getConstraintsExpects, m.ctrl, m, "GetConstraints", ctx, appNames...)
}

// GetConstraints indicates an expected call of GetConstraints.
func (mr *MockDeployerAPIMockRecorder) GetConstraints(ctx any, appNames ...any) *MockDeployerAPIGetConstraintsCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(appNames))
	for i, a := range appNames {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall1V_2[context.Context, string, []constraints.Value, error](mr.mock.ctrl.T, mr.mock, "GetConstraints", gomock.EnsureMatcher(ctx), varArgs)
	mr.getConstraintsExpects = append(mr.getConstraintsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIGetConstraintsCall is the typed call wrapper for GetConstraints.
type MockDeployerAPIGetConstraintsCall = gomock.Call1V_2[context.Context, string, []constraints.Value, error]

// GetModelConstraints mocks base method.
func (m *MockDeployerAPI) GetModelConstraints(ctx context.Context) (constraints.Value, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getModelConstraintsExpects, m.ctrl, m, "GetModelConstraints", ctx)
}

// GetModelConstraints indicates an expected call of GetModelConstraints.
func (mr *MockDeployerAPIMockRecorder) GetModelConstraints(ctx any) *MockDeployerAPIGetModelConstraintsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, constraints.Value, error](mr.mock.ctrl.T, mr.mock, "GetModelConstraints", gomock.EnsureMatcher(ctx))
	mr.getModelConstraintsExpects = append(mr.getModelConstraintsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIGetModelConstraintsCall is the typed call wrapper for GetModelConstraints.
type MockDeployerAPIGetModelConstraintsCall = gomock.Call1_2[context.Context, constraints.Value, error]

// GrantOffer mocks base method.
func (m *MockDeployerAPI) GrantOffer(ctx context.Context, user, access string, offerURLs ...string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3V_1(&m.recorder.grantOfferExpects, m.ctrl, m, "GrantOffer", ctx, user, access, offerURLs...)
}

// GrantOffer indicates an expected call of GrantOffer.
func (mr *MockDeployerAPIMockRecorder) GrantOffer(ctx, user, access any, offerURLs ...any) *MockDeployerAPIGrantOfferCall {
	mr.mock.ctrl.T.Helper()
	varArgs := make([]gomock.Matcher, len(offerURLs))
	for i, a := range offerURLs {
		varArgs[i] = gomock.EnsureMatcher(a)
	}
	call := gomock.NewCall3V_1[context.Context, string, string, string, error](mr.mock.ctrl.T, mr.mock, "GrantOffer", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(user), gomock.EnsureMatcher(access), varArgs)
	mr.grantOfferExpects = append(mr.grantOfferExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIGrantOfferCall is the typed call wrapper for GrantOffer.
type MockDeployerAPIGrantOfferCall = gomock.Call3V_1[context.Context, string, string, string, error]

// HTTPClient mocks base method.
func (m *MockDeployerAPI) HTTPClient(arg0 base.HTTPClientScope) (*httprequest.Client, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.hTTPClientExpects, m.ctrl, m, "HTTPClient", arg0)
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockDeployerAPIMockRecorder) HTTPClient(arg0 any) *MockDeployerAPIHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[base.HTTPClientScope, *httprequest.Client, error](mr.mock.ctrl.T, mr.mock, "HTTPClient", gomock.EnsureMatcher(arg0))
	mr.hTTPClientExpects = append(mr.hTTPClientExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIHTTPClientCall is the typed call wrapper for HTTPClient.
type MockDeployerAPIHTTPClientCall = gomock.Call1_2[base.HTTPClientScope, *httprequest.Client, error]

// ListCharmResources mocks base method.
func (m *MockDeployerAPI) ListCharmResources(ctx context.Context, curl string, origin charm.Origin) ([]resource.Resource, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.listCharmResourcesExpects, m.ctrl, m, "ListCharmResources", ctx, curl, origin)
}

// ListCharmResources indicates an expected call of ListCharmResources.
func (mr *MockDeployerAPIMockRecorder) ListCharmResources(ctx, curl, origin any) *MockDeployerAPIListCharmResourcesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, charm.Origin, []resource.Resource, error](mr.mock.ctrl.T, mr.mock, "ListCharmResources", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(curl), gomock.EnsureMatcher(origin))
	mr.listCharmResourcesExpects = append(mr.listCharmResourcesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIListCharmResourcesCall is the typed call wrapper for ListCharmResources.
type MockDeployerAPIListCharmResourcesCall = gomock.Call3_2[context.Context, string, charm.Origin, []resource.Resource, error]

// ListSpaces mocks base method.
func (m *MockDeployerAPI) ListSpaces(ctx context.Context) ([]params.Space, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.listSpacesExpects, m.ctrl, m, "ListSpaces", ctx)
}

// ListSpaces indicates an expected call of ListSpaces.
func (mr *MockDeployerAPIMockRecorder) ListSpaces(ctx any) *MockDeployerAPIListSpacesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []params.Space, error](mr.mock.ctrl.T, mr.mock, "ListSpaces", gomock.EnsureMatcher(ctx))
	mr.listSpacesExpects = append(mr.listSpacesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIListSpacesCall is the typed call wrapper for ListSpaces.
type MockDeployerAPIListSpacesCall = gomock.Call1_2[context.Context, []params.Space, error]

// ModelGet mocks base method.
func (m *MockDeployerAPI) ModelGet(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.modelGetExpects, m.ctrl, m, "ModelGet", ctx)
}

// ModelGet indicates an expected call of ModelGet.
func (mr *MockDeployerAPIMockRecorder) ModelGet(ctx any) *MockDeployerAPIModelGetCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, map[string]any, error](mr.mock.ctrl.T, mr.mock, "ModelGet", gomock.EnsureMatcher(ctx))
	mr.modelGetExpects = append(mr.modelGetExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIModelGetCall is the typed call wrapper for ModelGet.
type MockDeployerAPIModelGetCall = gomock.Call1_2[context.Context, map[string]any, error]

// ModelTag mocks base method.
func (m *MockDeployerAPI) ModelTag() (names.ModelTag, bool) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.modelTagExpects, m.ctrl, m, "ModelTag")
}

// ModelTag indicates an expected call of ModelTag.
func (mr *MockDeployerAPIMockRecorder) ModelTag() *MockDeployerAPIModelTagCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[names.ModelTag, bool](mr.mock.ctrl.T, mr.mock, "ModelTag")
	mr.modelTagExpects = append(mr.modelTagExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIModelTagCall is the typed call wrapper for ModelTag.
type MockDeployerAPIModelTagCall = gomock.Call0_2[names.ModelTag, bool]

// ModelUUID mocks base method.
func (m *MockDeployerAPI) ModelUUID() (string, bool) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.modelUUIDExpects, m.ctrl, m, "ModelUUID")
}

// ModelUUID indicates an expected call of ModelUUID.
func (mr *MockDeployerAPIMockRecorder) ModelUUID() *MockDeployerAPIModelUUIDCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[string, bool](mr.mock.ctrl.T, mr.mock, "ModelUUID")
	mr.modelUUIDExpects = append(mr.modelUUIDExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIModelUUIDCall is the typed call wrapper for ModelUUID.
type MockDeployerAPIModelUUIDCall = gomock.Call0_2[string, bool]

// Offer mocks base method.
func (m *MockDeployerAPI) Offer(ctx context.Context, modelUUID, arg2 string, endpoints []string, qualifier, offerName, descr string) ([]params.ErrorResult, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch7_2(&m.recorder.offerExpects, m.ctrl, m, "Offer", ctx, modelUUID, arg2, endpoints, qualifier, offerName, descr)
}

// Offer indicates an expected call of Offer.
func (mr *MockDeployerAPIMockRecorder) Offer(ctx, modelUUID, arg2, endpoints, qualifier, offerName, descr any) *MockDeployerAPIOfferCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall7_2[context.Context, string, string, []string, string, string, string, []params.ErrorResult, error](mr.mock.ctrl.T, mr.mock, "Offer", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(modelUUID), gomock.EnsureMatcher(arg2), gomock.EnsureMatcher(endpoints), gomock.EnsureMatcher(qualifier), gomock.EnsureMatcher(offerName), gomock.EnsureMatcher(descr))
	mr.offerExpects = append(mr.offerExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIOfferCall is the typed call wrapper for Offer.
type MockDeployerAPIOfferCall = gomock.Call7_2[context.Context, string, string, []string, string, string, string, []params.ErrorResult, error]

// ScaleApplication mocks base method.
func (m *MockDeployerAPI) ScaleApplication(arg0 context.Context, arg1 application.ScaleApplicationParams) (params.ScaleApplicationResult, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.scaleApplicationExpects, m.ctrl, m, "ScaleApplication", arg0, arg1)
}

// ScaleApplication indicates an expected call of ScaleApplication.
func (mr *MockDeployerAPIMockRecorder) ScaleApplication(arg0, arg1 any) *MockDeployerAPIScaleApplicationCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, application.ScaleApplicationParams, params.ScaleApplicationResult, error](mr.mock.ctrl.T, mr.mock, "ScaleApplication", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.scaleApplicationExpects = append(mr.scaleApplicationExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIScaleApplicationCall is the typed call wrapper for ScaleApplication.
type MockDeployerAPIScaleApplicationCall = gomock.Call2_2[context.Context, application.ScaleApplicationParams, params.ScaleApplicationResult, error]

// Sequences mocks base method.
func (m *MockDeployerAPI) Sequences(ctx context.Context) (map[string]int, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.sequencesExpects, m.ctrl, m, "Sequences", ctx)
}

// Sequences indicates an expected call of Sequences.
func (mr *MockDeployerAPIMockRecorder) Sequences(ctx any) *MockDeployerAPISequencesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, map[string]int, error](mr.mock.ctrl.T, mr.mock, "Sequences", gomock.EnsureMatcher(ctx))
	mr.sequencesExpects = append(mr.sequencesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPISequencesCall is the typed call wrapper for Sequences.
type MockDeployerAPISequencesCall = gomock.Call1_2[context.Context, map[string]int, error]

// SetAnnotation mocks base method.
func (m *MockDeployerAPI) SetAnnotation(ctx context.Context, annotations map[string]map[string]string) ([]params.ErrorResult, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.setAnnotationExpects, m.ctrl, m, "SetAnnotation", ctx, annotations)
}

// SetAnnotation indicates an expected call of SetAnnotation.
func (mr *MockDeployerAPIMockRecorder) SetAnnotation(ctx, annotations any) *MockDeployerAPISetAnnotationCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, map[string]map[string]string, []params.ErrorResult, error](mr.mock.ctrl.T, mr.mock, "SetAnnotation", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(annotations))
	mr.setAnnotationExpects = append(mr.setAnnotationExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPISetAnnotationCall is the typed call wrapper for SetAnnotation.
type MockDeployerAPISetAnnotationCall = gomock.Call2_2[context.Context, map[string]map[string]string, []params.ErrorResult, error]

// SetCharm mocks base method.
func (m *MockDeployerAPI) SetCharm(arg0 context.Context, arg1 application.SetCharmConfig) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_1(&m.recorder.setCharmExpects, m.ctrl, m, "SetCharm", arg0, arg1)
}

// SetCharm indicates an expected call of SetCharm.
func (mr *MockDeployerAPIMockRecorder) SetCharm(arg0, arg1 any) *MockDeployerAPISetCharmCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_1[context.Context, application.SetCharmConfig, error](mr.mock.ctrl.T, mr.mock, "SetCharm", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.setCharmExpects = append(mr.setCharmExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPISetCharmCall is the typed call wrapper for SetCharm.
type MockDeployerAPISetCharmCall = gomock.Call2_1[context.Context, application.SetCharmConfig, error]

// SetConfig mocks base method.
func (m *MockDeployerAPI) SetConfig(ctx context.Context, arg1, configYAML string, config map[string]string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_1(&m.recorder.setConfigExpects, m.ctrl, m, "SetConfig", ctx, arg1, configYAML, config)
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockDeployerAPIMockRecorder) SetConfig(ctx, arg1, configYAML, config any) *MockDeployerAPISetConfigCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_1[context.Context, string, string, map[string]string, error](mr.mock.ctrl.T, mr.mock, "SetConfig", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(arg1), gomock.EnsureMatcher(configYAML), gomock.EnsureMatcher(config))
	mr.setConfigExpects = append(mr.setConfigExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPISetConfigCall is the typed call wrapper for SetConfig.
type MockDeployerAPISetConfigCall = gomock.Call4_1[context.Context, string, string, map[string]string, error]

// SetConstraints mocks base method.
func (m *MockDeployerAPI) SetConstraints(ctx context.Context, arg1 string, arg2 constraints.Value) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.setConstraintsExpects, m.ctrl, m, "SetConstraints", ctx, arg1, arg2)
}

// SetConstraints indicates an expected call of SetConstraints.
func (mr *MockDeployerAPIMockRecorder) SetConstraints(ctx, arg1, arg2 any) *MockDeployerAPISetConstraintsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, constraints.Value, error](mr.mock.ctrl.T, mr.mock, "SetConstraints", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(arg1), gomock.EnsureMatcher(arg2))
	mr.setConstraintsExpects = append(mr.setConstraintsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPISetConstraintsCall is the typed call wrapper for SetConstraints.
type MockDeployerAPISetConstraintsCall = gomock.Call3_1[context.Context, string, constraints.Value, error]

// SimpleHTTPClient mocks base method.
func (m *MockDeployerAPI) SimpleHTTPClient() (base.SimpleHTTPClient, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_2(&m.recorder.simpleHTTPClientExpects, m.ctrl, m, "SimpleHTTPClient")
}

// SimpleHTTPClient indicates an expected call of SimpleHTTPClient.
func (mr *MockDeployerAPIMockRecorder) SimpleHTTPClient() *MockDeployerAPISimpleHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_2[base.SimpleHTTPClient, error](mr.mock.ctrl.T, mr.mock, "SimpleHTTPClient")
	mr.simpleHTTPClientExpects = append(mr.simpleHTTPClientExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPISimpleHTTPClientCall is the typed call wrapper for SimpleHTTPClient.
type MockDeployerAPISimpleHTTPClientCall = gomock.Call0_2[base.SimpleHTTPClient, error]

// Status mocks base method.
func (m *MockDeployerAPI) Status(arg0 context.Context, arg1 *client.StatusArgs) (*params.FullStatus, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.statusExpects, m.ctrl, m, "Status", arg0, arg1)
}

// Status indicates an expected call of Status.
func (mr *MockDeployerAPIMockRecorder) Status(arg0, arg1 any) *MockDeployerAPIStatusCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, *client.StatusArgs, *params.FullStatus, error](mr.mock.ctrl.T, mr.mock, "Status", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.statusExpects = append(mr.statusExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployerAPIStatusCall is the typed call wrapper for Status.
type MockDeployerAPIStatusCall = gomock.Call2_2[context.Context, *client.StatusArgs, *params.FullStatus, error]

// MockCharmReader is a mock of CharmReader interface.
type MockCharmReader struct {
	ctrl     *gomock.Controller
	recorder *MockCharmReaderMockRecorder
	isgomock struct{}
}

// MockCharmReaderMockRecorder is the mock recorder for MockCharmReader.
type MockCharmReaderMockRecorder struct {
	mock                  *MockCharmReader
	newCharmAtPathExpects []*gomock.Call1_3[string, charm0.Charm, *charm0.URL, error]
}

// NewMockCharmReader creates a new mock instance.
func NewMockCharmReader(ctrl *gomock.Controller) *MockCharmReader {
	mock := &MockCharmReader{ctrl: ctrl}
	mock.recorder = &MockCharmReaderMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCharmReader) EXPECT() *MockCharmReaderMockRecorder {
	return m.recorder
}

// NewCharmAtPath mocks base method.
func (m *MockCharmReader) NewCharmAtPath(arg0 string) (charm0.Charm, *charm0.URL, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_3(&m.recorder.newCharmAtPathExpects, m.ctrl, m, "NewCharmAtPath", arg0)
}

// NewCharmAtPath indicates an expected call of NewCharmAtPath.
func (mr *MockCharmReaderMockRecorder) NewCharmAtPath(arg0 any) *MockCharmReaderNewCharmAtPathCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_3[string, charm0.Charm, *charm0.URL, error](mr.mock.ctrl.T, mr.mock, "NewCharmAtPath", gomock.EnsureMatcher(arg0))
	mr.newCharmAtPathExpects = append(mr.newCharmAtPathExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockCharmReaderNewCharmAtPathCall is the typed call wrapper for NewCharmAtPath.
type MockCharmReaderNewCharmAtPathCall = gomock.Call1_3[string, charm0.Charm, *charm0.URL, error]

// MockDeployConfigFlag is a mock of DeployConfigFlag interface.
type MockDeployConfigFlag struct {
	ctrl     *gomock.Controller
	recorder *MockDeployConfigFlagMockRecorder
	isgomock struct{}
}

// MockDeployConfigFlagMockRecorder is the mock recorder for MockDeployConfigFlag.
type MockDeployConfigFlagMockRecorder struct {
	mock                     *MockDeployConfigFlag
	absoluteFileNamesExpects []*gomock.Call1_2[*cmd.Context, []string, error]
	readConfigPairsExpects   []*gomock.Call1_2[*cmd.Context, map[string]any, error]
}

// NewMockDeployConfigFlag creates a new mock instance.
func NewMockDeployConfigFlag(ctrl *gomock.Controller) *MockDeployConfigFlag {
	mock := &MockDeployConfigFlag{ctrl: ctrl}
	mock.recorder = &MockDeployConfigFlagMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeployConfigFlag) EXPECT() *MockDeployConfigFlagMockRecorder {
	return m.recorder
}

// AbsoluteFileNames mocks base method.
func (m *MockDeployConfigFlag) AbsoluteFileNames(ctx *cmd.Context) ([]string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.absoluteFileNamesExpects, m.ctrl, m, "AbsoluteFileNames", ctx)
}

// AbsoluteFileNames indicates an expected call of AbsoluteFileNames.
func (mr *MockDeployConfigFlagMockRecorder) AbsoluteFileNames(ctx any) *MockDeployConfigFlagAbsoluteFileNamesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[*cmd.Context, []string, error](mr.mock.ctrl.T, mr.mock, "AbsoluteFileNames", gomock.EnsureMatcher(ctx))
	mr.absoluteFileNamesExpects = append(mr.absoluteFileNamesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployConfigFlagAbsoluteFileNamesCall is the typed call wrapper for AbsoluteFileNames.
type MockDeployConfigFlagAbsoluteFileNamesCall = gomock.Call1_2[*cmd.Context, []string, error]

// ReadConfigPairs mocks base method.
func (m *MockDeployConfigFlag) ReadConfigPairs(ctx *cmd.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.readConfigPairsExpects, m.ctrl, m, "ReadConfigPairs", ctx)
}

// ReadConfigPairs indicates an expected call of ReadConfigPairs.
func (mr *MockDeployConfigFlagMockRecorder) ReadConfigPairs(ctx any) *MockDeployConfigFlagReadConfigPairsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[*cmd.Context, map[string]any, error](mr.mock.ctrl.T, mr.mock, "ReadConfigPairs", gomock.EnsureMatcher(ctx))
	mr.readConfigPairsExpects = append(mr.readConfigPairsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockDeployConfigFlagReadConfigPairsCall is the typed call wrapper for ReadConfigPairs.
type MockDeployConfigFlagReadConfigPairsCall = gomock.Call1_2[*cmd.Context, map[string]any, error]
