name: Send Mattermost notification
description: Send a message to a Mattermost channel

inputs:
  mm_token:
    description: Mattermost access token
    required: true
  mm_url:
    description: Mattermost server URL
    required: true
  channel:
    description: Mattermost channel to post the message to
    required: true
  message:
    description: Message to post
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        MM_URL: ${{ inputs.mm_url }}
        MM_TOKEN: ${{ inputs.mm_token }}
        CHANNEL: ${{ inputs.channel }}
        MESSAGE: ${{ inputs.message }}
      run: |
        curl https://releases.mattermost.com/mmctl/v10.11.6/linux_amd64.tar -Lo mmctl.tar
        tar -xvf mmctl.tar
        ./mmctl auth login "$MM_URL" --name Charmhub --access-token $MM_TOKEN
        ./mmctl post create $MM_CHANNEL --message "$MESSAGE"
