// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/domain/controllernode/service (interfaces: State,WatcherFactory)
//
// Generated by this command:
//
//	mockgen -package service -destination package_mock_test.go github.com/juju/juju/domain/controllernode/service State,WatcherFactory
//

// Package service is a generated GoMock package.
package service

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"
	agentbinary "github.com/juju/juju/core/agentbinary"
	watcher "github.com/juju/juju/core/watcher"
	eventsource "github.com/juju/juju/core/watcher/eventsource"
	controllernode "github.com/juju/juju/domain/controllernode"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock                                               *MockState
	addDqliteNodeExpects                               []*gomock.Call4_1[context.Context, string, uint64, string, error]
	addDqliteNodeIDExpects                             []*gomock.Call2_1[context.Context, string, error]
	getAPIAddressesForAgentsExpects                    []*gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]
	getAPIAddressesForClientsExpects                   []*gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]
	getAllCloudLocalAPIAddressesExpects                []*gomock.Call1_2[context.Context, []string, error]
	getControllerAPIAddressesForAgentsExpects          []*gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]
	getControllerAPIAddressesForClientsExpects         []*gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]
	getControllerIDsExpects                            []*gomock.Call1_2[context.Context, []string, error]
	namespaceForWatchAPIAddressesForAgentsExpects      []*gomock.Call0_1[string]
	namespaceForWatchAPIAddressesForClientsExpects     []*gomock.Call0_1[string]
	namespaceForWatchControllerNodeAPIAddressesExpects []*gomock.Call0_1[string]
	namespaceForWatchControllerNodesExpects            []*gomock.Call0_1[string]
	selectDatabaseNamespaceExpects                     []*gomock.Call2_2[context.Context, string, string, error]
	setAPIAddressesExpects                             []*gomock.Call2V_1[context.Context, map[string]controllernode.APIAddresses, *controllernode.APIAddresses, error]
	setRunningAgentBinaryVersionExpects                []*gomock.Call3_1[context.Context, string, agentbinary.Version, error]
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// AddDqliteNode mocks base method.
func (m *MockState) AddDqliteNode(ctx context.Context, controllerID string, nodeID uint64, addr string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch4_1(&m.recorder.addDqliteNodeExpects, m.ctrl, m, "AddDqliteNode", ctx, controllerID, nodeID, addr)
}

// AddDqliteNode indicates an expected call of AddDqliteNode.
func (mr *MockStateMockRecorder) AddDqliteNode(ctx, controllerID, nodeID, addr any) *MockStateAddDqliteNodeCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall4_1[context.Context, string, uint64, string, error](mr.mock.ctrl.T, mr.mock, "AddDqliteNode", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(controllerID), gomock.EnsureMatcher(nodeID), gomock.EnsureMatcher(addr))
	mr.addDqliteNodeExpects = append(mr.addDqliteNodeExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateAddDqliteNodeCall is the typed call wrapper for AddDqliteNode.
type MockStateAddDqliteNodeCall = gomock.Call4_1[context.Context, string, uint64, string, error]

// AddDqliteNodeID mocks base method.
func (m *MockState) AddDqliteNodeID(ctx context.Context, controllerID string) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_1(&m.recorder.addDqliteNodeIDExpects, m.ctrl, m, "AddDqliteNodeID", ctx, controllerID)
}

// AddDqliteNodeID indicates an expected call of AddDqliteNodeID.
func (mr *MockStateMockRecorder) AddDqliteNodeID(ctx, controllerID any) *MockStateAddDqliteNodeIDCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_1[context.Context, string, error](mr.mock.ctrl.T, mr.mock, "AddDqliteNodeID", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(controllerID))
	mr.addDqliteNodeIDExpects = append(mr.addDqliteNodeIDExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateAddDqliteNodeIDCall is the typed call wrapper for AddDqliteNodeID.
type MockStateAddDqliteNodeIDCall = gomock.Call2_1[context.Context, string, error]

// GetAPIAddressesForAgents mocks base method.
func (m *MockState) GetAPIAddressesForAgents(ctx context.Context) (map[string]controllernode.APIAddresses, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getAPIAddressesForAgentsExpects, m.ctrl, m, "GetAPIAddressesForAgents", ctx)
}

// GetAPIAddressesForAgents indicates an expected call of GetAPIAddressesForAgents.
func (mr *MockStateMockRecorder) GetAPIAddressesForAgents(ctx any) *MockStateGetAPIAddressesForAgentsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, map[string]controllernode.APIAddresses, error](mr.mock.ctrl.T, mr.mock, "GetAPIAddressesForAgents", gomock.EnsureMatcher(ctx))
	mr.getAPIAddressesForAgentsExpects = append(mr.getAPIAddressesForAgentsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetAPIAddressesForAgentsCall is the typed call wrapper for GetAPIAddressesForAgents.
type MockStateGetAPIAddressesForAgentsCall = gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]

// GetAPIAddressesForClients mocks base method.
func (m *MockState) GetAPIAddressesForClients(ctx context.Context) (map[string]controllernode.APIAddresses, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getAPIAddressesForClientsExpects, m.ctrl, m, "GetAPIAddressesForClients", ctx)
}

// GetAPIAddressesForClients indicates an expected call of GetAPIAddressesForClients.
func (mr *MockStateMockRecorder) GetAPIAddressesForClients(ctx any) *MockStateGetAPIAddressesForClientsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, map[string]controllernode.APIAddresses, error](mr.mock.ctrl.T, mr.mock, "GetAPIAddressesForClients", gomock.EnsureMatcher(ctx))
	mr.getAPIAddressesForClientsExpects = append(mr.getAPIAddressesForClientsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetAPIAddressesForClientsCall is the typed call wrapper for GetAPIAddressesForClients.
type MockStateGetAPIAddressesForClientsCall = gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]

// GetAllCloudLocalAPIAddresses mocks base method.
func (m *MockState) GetAllCloudLocalAPIAddresses(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getAllCloudLocalAPIAddressesExpects, m.ctrl, m, "GetAllCloudLocalAPIAddresses", ctx)
}

// GetAllCloudLocalAPIAddresses indicates an expected call of GetAllCloudLocalAPIAddresses.
func (mr *MockStateMockRecorder) GetAllCloudLocalAPIAddresses(ctx any) *MockStateGetAllCloudLocalAPIAddressesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []string, error](mr.mock.ctrl.T, mr.mock, "GetAllCloudLocalAPIAddresses", gomock.EnsureMatcher(ctx))
	mr.getAllCloudLocalAPIAddressesExpects = append(mr.getAllCloudLocalAPIAddressesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetAllCloudLocalAPIAddressesCall is the typed call wrapper for GetAllCloudLocalAPIAddresses.
type MockStateGetAllCloudLocalAPIAddressesCall = gomock.Call1_2[context.Context, []string, error]

// GetControllerAPIAddressesForAgents mocks base method.
func (m *MockState) GetControllerAPIAddressesForAgents(ctx context.Context) (map[string]controllernode.APIAddresses, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getControllerAPIAddressesForAgentsExpects, m.ctrl, m, "GetControllerAPIAddressesForAgents", ctx)
}

// GetControllerAPIAddressesForAgents indicates an expected call of GetControllerAPIAddressesForAgents.
func (mr *MockStateMockRecorder) GetControllerAPIAddressesForAgents(ctx any) *MockStateGetControllerAPIAddressesForAgentsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, map[string]controllernode.APIAddresses, error](mr.mock.ctrl.T, mr.mock, "GetControllerAPIAddressesForAgents", gomock.EnsureMatcher(ctx))
	mr.getControllerAPIAddressesForAgentsExpects = append(mr.getControllerAPIAddressesForAgentsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetControllerAPIAddressesForAgentsCall is the typed call wrapper for GetControllerAPIAddressesForAgents.
type MockStateGetControllerAPIAddressesForAgentsCall = gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]

// GetControllerAPIAddressesForClients mocks base method.
func (m *MockState) GetControllerAPIAddressesForClients(ctx context.Context) (map[string]controllernode.APIAddresses, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getControllerAPIAddressesForClientsExpects, m.ctrl, m, "GetControllerAPIAddressesForClients", ctx)
}

// GetControllerAPIAddressesForClients indicates an expected call of GetControllerAPIAddressesForClients.
func (mr *MockStateMockRecorder) GetControllerAPIAddressesForClients(ctx any) *MockStateGetControllerAPIAddressesForClientsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, map[string]controllernode.APIAddresses, error](mr.mock.ctrl.T, mr.mock, "GetControllerAPIAddressesForClients", gomock.EnsureMatcher(ctx))
	mr.getControllerAPIAddressesForClientsExpects = append(mr.getControllerAPIAddressesForClientsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetControllerAPIAddressesForClientsCall is the typed call wrapper for GetControllerAPIAddressesForClients.
type MockStateGetControllerAPIAddressesForClientsCall = gomock.Call1_2[context.Context, map[string]controllernode.APIAddresses, error]

// GetControllerIDs mocks base method.
func (m *MockState) GetControllerIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch1_2(&m.recorder.getControllerIDsExpects, m.ctrl, m, "GetControllerIDs", ctx)
}

// GetControllerIDs indicates an expected call of GetControllerIDs.
func (mr *MockStateMockRecorder) GetControllerIDs(ctx any) *MockStateGetControllerIDsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall1_2[context.Context, []string, error](mr.mock.ctrl.T, mr.mock, "GetControllerIDs", gomock.EnsureMatcher(ctx))
	mr.getControllerIDsExpects = append(mr.getControllerIDsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateGetControllerIDsCall is the typed call wrapper for GetControllerIDs.
type MockStateGetControllerIDsCall = gomock.Call1_2[context.Context, []string, error]

// NamespaceForWatchAPIAddressesForAgents mocks base method.
func (m *MockState) NamespaceForWatchAPIAddressesForAgents() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.namespaceForWatchAPIAddressesForAgentsExpects, m.ctrl, m, "NamespaceForWatchAPIAddressesForAgents")
}

// NamespaceForWatchAPIAddressesForAgents indicates an expected call of NamespaceForWatchAPIAddressesForAgents.
func (mr *MockStateMockRecorder) NamespaceForWatchAPIAddressesForAgents() *MockStateNamespaceForWatchAPIAddressesForAgentsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "NamespaceForWatchAPIAddressesForAgents")
	mr.namespaceForWatchAPIAddressesForAgentsExpects = append(mr.namespaceForWatchAPIAddressesForAgentsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateNamespaceForWatchAPIAddressesForAgentsCall is the typed call wrapper for NamespaceForWatchAPIAddressesForAgents.
type MockStateNamespaceForWatchAPIAddressesForAgentsCall = gomock.Call0_1[string]

// NamespaceForWatchAPIAddressesForClients mocks base method.
func (m *MockState) NamespaceForWatchAPIAddressesForClients() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.namespaceForWatchAPIAddressesForClientsExpects, m.ctrl, m, "NamespaceForWatchAPIAddressesForClients")
}

// NamespaceForWatchAPIAddressesForClients indicates an expected call of NamespaceForWatchAPIAddressesForClients.
func (mr *MockStateMockRecorder) NamespaceForWatchAPIAddressesForClients() *MockStateNamespaceForWatchAPIAddressesForClientsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "NamespaceForWatchAPIAddressesForClients")
	mr.namespaceForWatchAPIAddressesForClientsExpects = append(mr.namespaceForWatchAPIAddressesForClientsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateNamespaceForWatchAPIAddressesForClientsCall is the typed call wrapper for NamespaceForWatchAPIAddressesForClients.
type MockStateNamespaceForWatchAPIAddressesForClientsCall = gomock.Call0_1[string]

// NamespaceForWatchControllerNodeAPIAddresses mocks base method.
func (m *MockState) NamespaceForWatchControllerNodeAPIAddresses() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.namespaceForWatchControllerNodeAPIAddressesExpects, m.ctrl, m, "NamespaceForWatchControllerNodeAPIAddresses")
}

// NamespaceForWatchControllerNodeAPIAddresses indicates an expected call of NamespaceForWatchControllerNodeAPIAddresses.
func (mr *MockStateMockRecorder) NamespaceForWatchControllerNodeAPIAddresses() *MockStateNamespaceForWatchControllerNodeAPIAddressesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "NamespaceForWatchControllerNodeAPIAddresses")
	mr.namespaceForWatchControllerNodeAPIAddressesExpects = append(mr.namespaceForWatchControllerNodeAPIAddressesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateNamespaceForWatchControllerNodeAPIAddressesCall is the typed call wrapper for NamespaceForWatchControllerNodeAPIAddresses.
type MockStateNamespaceForWatchControllerNodeAPIAddressesCall = gomock.Call0_1[string]

// NamespaceForWatchControllerNodes mocks base method.
func (m *MockState) NamespaceForWatchControllerNodes() string {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.namespaceForWatchControllerNodesExpects, m.ctrl, m, "NamespaceForWatchControllerNodes")
}

// NamespaceForWatchControllerNodes indicates an expected call of NamespaceForWatchControllerNodes.
func (mr *MockStateMockRecorder) NamespaceForWatchControllerNodes() *MockStateNamespaceForWatchControllerNodesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[string](mr.mock.ctrl.T, mr.mock, "NamespaceForWatchControllerNodes")
	mr.namespaceForWatchControllerNodesExpects = append(mr.namespaceForWatchControllerNodesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateNamespaceForWatchControllerNodesCall is the typed call wrapper for NamespaceForWatchControllerNodes.
type MockStateNamespaceForWatchControllerNodesCall = gomock.Call0_1[string]

// SelectDatabaseNamespace mocks base method.
func (m *MockState) SelectDatabaseNamespace(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.selectDatabaseNamespaceExpects, m.ctrl, m, "SelectDatabaseNamespace", arg0, arg1)
}

// SelectDatabaseNamespace indicates an expected call of SelectDatabaseNamespace.
func (mr *MockStateMockRecorder) SelectDatabaseNamespace(arg0, arg1 any) *MockStateSelectDatabaseNamespaceCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, string, string, error](mr.mock.ctrl.T, mr.mock, "SelectDatabaseNamespace", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1))
	mr.selectDatabaseNamespaceExpects = append(mr.selectDatabaseNamespaceExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateSelectDatabaseNamespaceCall is the typed call wrapper for SelectDatabaseNamespace.
type MockStateSelectDatabaseNamespaceCall = gomock.Call2_2[context.Context, string, string, error]

// SetAPIAddresses mocks base method.
func (m *MockState) SetAPIAddresses(ctx context.Context, addresses map[string]controllernode.APIAddresses, general ...*controllernode.APIAddresses) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch2V_1(&m.recorder.setAPIAddressesExpects, m.ctrl, m, "SetAPIAddresses", ctx, addresses, general...)
}

// SetAPIAddresses indicates an expected call of SetAPIAddresses.
func (mr *MockStateMockRecorder) SetAPIAddresses(ctx, addresses any, general ...any) *MockStateSetAPIAddressesCall {
	mr.mock.ctrl.T.Helper()
	varArgs := gomock.EnsureVariadicMatcher(general)
	call := gomock.NewCall2V_1[context.Context, map[string]controllernode.APIAddresses, *controllernode.APIAddresses, error](mr.mock.ctrl.T, mr.mock, "SetAPIAddresses", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(addresses), varArgs)
	mr.setAPIAddressesExpects = append(mr.setAPIAddressesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateSetAPIAddressesCall is the typed call wrapper for SetAPIAddresses.
type MockStateSetAPIAddressesCall = gomock.Call2V_1[context.Context, map[string]controllernode.APIAddresses, *controllernode.APIAddresses, error]

// SetRunningAgentBinaryVersion mocks base method.
func (m *MockState) SetRunningAgentBinaryVersion(arg0 context.Context, arg1 string, arg2 agentbinary.Version) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.setRunningAgentBinaryVersionExpects, m.ctrl, m, "SetRunningAgentBinaryVersion", arg0, arg1, arg2)
}

// SetRunningAgentBinaryVersion indicates an expected call of SetRunningAgentBinaryVersion.
func (mr *MockStateMockRecorder) SetRunningAgentBinaryVersion(arg0, arg1, arg2 any) *MockStateSetRunningAgentBinaryVersionCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, agentbinary.Version, error](mr.mock.ctrl.T, mr.mock, "SetRunningAgentBinaryVersion", gomock.EnsureMatcher(arg0), gomock.EnsureMatcher(arg1), gomock.EnsureMatcher(arg2))
	mr.setRunningAgentBinaryVersionExpects = append(mr.setRunningAgentBinaryVersionExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockStateSetRunningAgentBinaryVersionCall is the typed call wrapper for SetRunningAgentBinaryVersion.
type MockStateSetRunningAgentBinaryVersionCall = gomock.Call3_1[context.Context, string, agentbinary.Version, error]

// MockWatcherFactory is a mock of WatcherFactory interface.
type MockWatcherFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherFactoryMockRecorder
	isgomock struct{}
}

// MockWatcherFactoryMockRecorder is the mock recorder for MockWatcherFactory.
type MockWatcherFactoryMockRecorder struct {
	mock                    *MockWatcherFactory
	newNotifyWatcherExpects []*gomock.Call3V_2[context.Context, string, eventsource.FilterOption, eventsource.FilterOption, watcher.NotifyWatcher, error]
}

// NewMockWatcherFactory creates a new mock instance.
func NewMockWatcherFactory(ctrl *gomock.Controller) *MockWatcherFactory {
	mock := &MockWatcherFactory{ctrl: ctrl}
	mock.recorder = &MockWatcherFactoryMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcherFactory) EXPECT() *MockWatcherFactoryMockRecorder {
	return m.recorder
}

// NewNotifyWatcher mocks base method.
func (m *MockWatcherFactory) NewNotifyWatcher(ctx context.Context, summary string, filterOption eventsource.FilterOption, filterOptions ...eventsource.FilterOption) (watcher.NotifyWatcher, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3V_2(&m.recorder.newNotifyWatcherExpects, m.ctrl, m, "NewNotifyWatcher", ctx, summary, filterOption, filterOptions...)
}

// NewNotifyWatcher indicates an expected call of NewNotifyWatcher.
func (mr *MockWatcherFactoryMockRecorder) NewNotifyWatcher(ctx, summary, filterOption any, filterOptions ...any) *MockWatcherFactoryNewNotifyWatcherCall {
	mr.mock.ctrl.T.Helper()
	varArgs := gomock.EnsureVariadicMatcher(filterOptions)
	call := gomock.NewCall3V_2[context.Context, string, eventsource.FilterOption, eventsource.FilterOption, watcher.NotifyWatcher, error](mr.mock.ctrl.T, mr.mock, "NewNotifyWatcher", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(summary), gomock.EnsureMatcher(filterOption), varArgs)
	mr.newNotifyWatcherExpects = append(mr.newNotifyWatcherExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockWatcherFactoryNewNotifyWatcherCall is the typed call wrapper for NewNotifyWatcher.
type MockWatcherFactoryNewNotifyWatcherCall = gomock.Call3V_2[context.Context, string, eventsource.FilterOption, eventsource.FilterOption, watcher.NotifyWatcher, error]
