// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/kubernetes/typed/admissionregistration/v1 (interfaces: AdmissionregistrationV1Interface,MutatingWebhookConfigurationInterface,ValidatingWebhookConfigurationInterface)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/admissionregistrationv1_mock.go -mock_names=MutatingWebhookConfigurationInterface=MockMutatingWebhookConfigurationV1Interface,ValidatingWebhookConfigurationInterface=MockValidatingWebhookConfigurationV1Interface k8s.io/client-go/kubernetes/typed/admissionregistration/v1 AdmissionregistrationV1Interface,MutatingWebhookConfigurationInterface,ValidatingWebhookConfigurationInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	gomock "github.com/canonical/gomock/gomock"
	v1 "k8s.io/api/admissionregistration/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	v11 "k8s.io/client-go/applyconfigurations/admissionregistration/v1"
	v12 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1"
	rest "k8s.io/client-go/rest"
)

// MockAdmissionregistrationV1Interface is a mock of AdmissionregistrationV1Interface interface.
type MockAdmissionregistrationV1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockAdmissionregistrationV1InterfaceMockRecorder
	isgomock struct{}
}

// MockAdmissionregistrationV1InterfaceMockRecorder is the mock recorder for MockAdmissionregistrationV1Interface.
type MockAdmissionregistrationV1InterfaceMockRecorder struct {
	mock                                     *MockAdmissionregistrationV1Interface
	mutatingWebhookConfigurationsExpects     []*gomock.Call0_1[v12.MutatingWebhookConfigurationInterface]
	rESTClientExpects                        []*gomock.Call0_1[rest.Interface]
	validatingAdmissionPoliciesExpects       []*gomock.Call0_1[v12.ValidatingAdmissionPolicyInterface]
	validatingAdmissionPolicyBindingsExpects []*gomock.Call0_1[v12.ValidatingAdmissionPolicyBindingInterface]
	validatingWebhookConfigurationsExpects   []*gomock.Call0_1[v12.ValidatingWebhookConfigurationInterface]
}

// NewMockAdmissionregistrationV1Interface creates a new mock instance.
func NewMockAdmissionregistrationV1Interface(ctrl *gomock.Controller) *MockAdmissionregistrationV1Interface {
	mock := &MockAdmissionregistrationV1Interface{ctrl: ctrl}
	mock.recorder = &MockAdmissionregistrationV1InterfaceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmissionregistrationV1Interface) EXPECT() *MockAdmissionregistrationV1InterfaceMockRecorder {
	return m.recorder
}

// MutatingWebhookConfigurations mocks base method.
func (m *MockAdmissionregistrationV1Interface) MutatingWebhookConfigurations() v12.MutatingWebhookConfigurationInterface {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.mutatingWebhookConfigurationsExpects, m.ctrl, m, "MutatingWebhookConfigurations")
}

// MutatingWebhookConfigurations indicates an expected call of MutatingWebhookConfigurations.
func (mr *MockAdmissionregistrationV1InterfaceMockRecorder) MutatingWebhookConfigurations() *MockAdmissionregistrationV1InterfaceMutatingWebhookConfigurationsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[v12.MutatingWebhookConfigurationInterface](mr.mock.ctrl.T, mr.mock, "MutatingWebhookConfigurations")
	mr.mutatingWebhookConfigurationsExpects = append(mr.mutatingWebhookConfigurationsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAdmissionregistrationV1InterfaceMutatingWebhookConfigurationsCall is the typed call wrapper for MutatingWebhookConfigurations.
type MockAdmissionregistrationV1InterfaceMutatingWebhookConfigurationsCall = gomock.Call0_1[v12.MutatingWebhookConfigurationInterface]

// RESTClient mocks base method.
func (m *MockAdmissionregistrationV1Interface) RESTClient() rest.Interface {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.rESTClientExpects, m.ctrl, m, "RESTClient")
}

// RESTClient indicates an expected call of RESTClient.
func (mr *MockAdmissionregistrationV1InterfaceMockRecorder) RESTClient() *MockAdmissionregistrationV1InterfaceRESTClientCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[rest.Interface](mr.mock.ctrl.T, mr.mock, "RESTClient")
	mr.rESTClientExpects = append(mr.rESTClientExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAdmissionregistrationV1InterfaceRESTClientCall is the typed call wrapper for RESTClient.
type MockAdmissionregistrationV1InterfaceRESTClientCall = gomock.Call0_1[rest.Interface]

// ValidatingAdmissionPolicies mocks base method.
func (m *MockAdmissionregistrationV1Interface) ValidatingAdmissionPolicies() v12.ValidatingAdmissionPolicyInterface {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.validatingAdmissionPoliciesExpects, m.ctrl, m, "ValidatingAdmissionPolicies")
}

// ValidatingAdmissionPolicies indicates an expected call of ValidatingAdmissionPolicies.
func (mr *MockAdmissionregistrationV1InterfaceMockRecorder) ValidatingAdmissionPolicies() *MockAdmissionregistrationV1InterfaceValidatingAdmissionPoliciesCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[v12.ValidatingAdmissionPolicyInterface](mr.mock.ctrl.T, mr.mock, "ValidatingAdmissionPolicies")
	mr.validatingAdmissionPoliciesExpects = append(mr.validatingAdmissionPoliciesExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAdmissionregistrationV1InterfaceValidatingAdmissionPoliciesCall is the typed call wrapper for ValidatingAdmissionPolicies.
type MockAdmissionregistrationV1InterfaceValidatingAdmissionPoliciesCall = gomock.Call0_1[v12.ValidatingAdmissionPolicyInterface]

// ValidatingAdmissionPolicyBindings mocks base method.
func (m *MockAdmissionregistrationV1Interface) ValidatingAdmissionPolicyBindings() v12.ValidatingAdmissionPolicyBindingInterface {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.validatingAdmissionPolicyBindingsExpects, m.ctrl, m, "ValidatingAdmissionPolicyBindings")
}

// ValidatingAdmissionPolicyBindings indicates an expected call of ValidatingAdmissionPolicyBindings.
func (mr *MockAdmissionregistrationV1InterfaceMockRecorder) ValidatingAdmissionPolicyBindings() *MockAdmissionregistrationV1InterfaceValidatingAdmissionPolicyBindingsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[v12.ValidatingAdmissionPolicyBindingInterface](mr.mock.ctrl.T, mr.mock, "ValidatingAdmissionPolicyBindings")
	mr.validatingAdmissionPolicyBindingsExpects = append(mr.validatingAdmissionPolicyBindingsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAdmissionregistrationV1InterfaceValidatingAdmissionPolicyBindingsCall is the typed call wrapper for ValidatingAdmissionPolicyBindings.
type MockAdmissionregistrationV1InterfaceValidatingAdmissionPolicyBindingsCall = gomock.Call0_1[v12.ValidatingAdmissionPolicyBindingInterface]

// ValidatingWebhookConfigurations mocks base method.
func (m *MockAdmissionregistrationV1Interface) ValidatingWebhookConfigurations() v12.ValidatingWebhookConfigurationInterface {
	m.ctrl.T.Helper()
	return gomock.Dispatch0_1(&m.recorder.validatingWebhookConfigurationsExpects, m.ctrl, m, "ValidatingWebhookConfigurations")
}

// ValidatingWebhookConfigurations indicates an expected call of ValidatingWebhookConfigurations.
func (mr *MockAdmissionregistrationV1InterfaceMockRecorder) ValidatingWebhookConfigurations() *MockAdmissionregistrationV1InterfaceValidatingWebhookConfigurationsCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall0_1[v12.ValidatingWebhookConfigurationInterface](mr.mock.ctrl.T, mr.mock, "ValidatingWebhookConfigurations")
	mr.validatingWebhookConfigurationsExpects = append(mr.validatingWebhookConfigurationsExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockAdmissionregistrationV1InterfaceValidatingWebhookConfigurationsCall is the typed call wrapper for ValidatingWebhookConfigurations.
type MockAdmissionregistrationV1InterfaceValidatingWebhookConfigurationsCall = gomock.Call0_1[v12.ValidatingWebhookConfigurationInterface]

// MockMutatingWebhookConfigurationV1Interface is a mock of MutatingWebhookConfigurationInterface interface.
type MockMutatingWebhookConfigurationV1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockMutatingWebhookConfigurationV1InterfaceMockRecorder
	isgomock struct{}
}

// MockMutatingWebhookConfigurationV1InterfaceMockRecorder is the mock recorder for MockMutatingWebhookConfigurationV1Interface.
type MockMutatingWebhookConfigurationV1InterfaceMockRecorder struct {
	mock                    *MockMutatingWebhookConfigurationV1Interface
	applyExpects            []*gomock.Call3_2[context.Context, *v11.MutatingWebhookConfigurationApplyConfiguration, v10.ApplyOptions, *v1.MutatingWebhookConfiguration, error]
	createExpects           []*gomock.Call3_2[context.Context, *v1.MutatingWebhookConfiguration, v10.CreateOptions, *v1.MutatingWebhookConfiguration, error]
	deleteExpects           []*gomock.Call3_1[context.Context, string, v10.DeleteOptions, error]
	deleteCollectionExpects []*gomock.Call3_1[context.Context, v10.DeleteOptions, v10.ListOptions, error]
	getExpects              []*gomock.Call3_2[context.Context, string, v10.GetOptions, *v1.MutatingWebhookConfiguration, error]
	listExpects             []*gomock.Call2_2[context.Context, v10.ListOptions, *v1.MutatingWebhookConfigurationList, error]
	patchExpects            []*gomock.Call5V_2[context.Context, string, types.PatchType, []byte, v10.PatchOptions, string, *v1.MutatingWebhookConfiguration, error]
	updateExpects           []*gomock.Call3_2[context.Context, *v1.MutatingWebhookConfiguration, v10.UpdateOptions, *v1.MutatingWebhookConfiguration, error]
	watchExpects            []*gomock.Call2_2[context.Context, v10.ListOptions, watch.Interface, error]
}

// NewMockMutatingWebhookConfigurationV1Interface creates a new mock instance.
func NewMockMutatingWebhookConfigurationV1Interface(ctrl *gomock.Controller) *MockMutatingWebhookConfigurationV1Interface {
	mock := &MockMutatingWebhookConfigurationV1Interface{ctrl: ctrl}
	mock.recorder = &MockMutatingWebhookConfigurationV1InterfaceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutatingWebhookConfigurationV1Interface) EXPECT() *MockMutatingWebhookConfigurationV1InterfaceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Apply(ctx context.Context, mutatingWebhookConfiguration *v11.MutatingWebhookConfigurationApplyConfiguration, opts v10.ApplyOptions) (*v1.MutatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.applyExpects, m.ctrl, m, "Apply", ctx, mutatingWebhookConfiguration, opts)
}

// Apply indicates an expected call of Apply.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Apply(ctx, mutatingWebhookConfiguration, opts any) *MockMutatingWebhookConfigurationV1InterfaceApplyCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, *v11.MutatingWebhookConfigurationApplyConfiguration, v10.ApplyOptions, *v1.MutatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Apply", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(mutatingWebhookConfiguration), gomock.EnsureMatcher(opts))
	mr.applyExpects = append(mr.applyExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceApplyCall is the typed call wrapper for Apply.
type MockMutatingWebhookConfigurationV1InterfaceApplyCall = gomock.Call3_2[context.Context, *v11.MutatingWebhookConfigurationApplyConfiguration, v10.ApplyOptions, *v1.MutatingWebhookConfiguration, error]

// Create mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Create(ctx context.Context, mutatingWebhookConfiguration *v1.MutatingWebhookConfiguration, opts v10.CreateOptions) (*v1.MutatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.createExpects, m.ctrl, m, "Create", ctx, mutatingWebhookConfiguration, opts)
}

// Create indicates an expected call of Create.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Create(ctx, mutatingWebhookConfiguration, opts any) *MockMutatingWebhookConfigurationV1InterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, *v1.MutatingWebhookConfiguration, v10.CreateOptions, *v1.MutatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Create", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(mutatingWebhookConfiguration), gomock.EnsureMatcher(opts))
	mr.createExpects = append(mr.createExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceCreateCall is the typed call wrapper for Create.
type MockMutatingWebhookConfigurationV1InterfaceCreateCall = gomock.Call3_2[context.Context, *v1.MutatingWebhookConfiguration, v10.CreateOptions, *v1.MutatingWebhookConfiguration, error]

// Delete mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Delete(ctx context.Context, name string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.deleteExpects, m.ctrl, m, "Delete", ctx, name, opts)
}

// Delete indicates an expected call of Delete.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Delete(ctx, name, opts any) *MockMutatingWebhookConfigurationV1InterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, v10.DeleteOptions, error](mr.mock.ctrl.T, mr.mock, "Delete", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(opts))
	mr.deleteExpects = append(mr.deleteExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceDeleteCall is the typed call wrapper for Delete.
type MockMutatingWebhookConfigurationV1InterfaceDeleteCall = gomock.Call3_1[context.Context, string, v10.DeleteOptions, error]

// DeleteCollection mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) DeleteCollection(ctx context.Context, opts v10.DeleteOptions, listOpts v10.ListOptions) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.deleteCollectionExpects, m.ctrl, m, "DeleteCollection", ctx, opts, listOpts)
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) DeleteCollection(ctx, opts, listOpts any) *MockMutatingWebhookConfigurationV1InterfaceDeleteCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, v10.DeleteOptions, v10.ListOptions, error](mr.mock.ctrl.T, mr.mock, "DeleteCollection", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(opts), gomock.EnsureMatcher(listOpts))
	mr.deleteCollectionExpects = append(mr.deleteCollectionExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceDeleteCollectionCall is the typed call wrapper for DeleteCollection.
type MockMutatingWebhookConfigurationV1InterfaceDeleteCollectionCall = gomock.Call3_1[context.Context, v10.DeleteOptions, v10.ListOptions, error]

// Get mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Get(ctx context.Context, name string, opts v10.GetOptions) (*v1.MutatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.getExpects, m.ctrl, m, "Get", ctx, name, opts)
}

// Get indicates an expected call of Get.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Get(ctx, name, opts any) *MockMutatingWebhookConfigurationV1InterfaceGetCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, v10.GetOptions, *v1.MutatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Get", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(opts))
	mr.getExpects = append(mr.getExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceGetCall is the typed call wrapper for Get.
type MockMutatingWebhookConfigurationV1InterfaceGetCall = gomock.Call3_2[context.Context, string, v10.GetOptions, *v1.MutatingWebhookConfiguration, error]

// List mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) List(ctx context.Context, opts v10.ListOptions) (*v1.MutatingWebhookConfigurationList, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.listExpects, m.ctrl, m, "List", ctx, opts)
}

// List indicates an expected call of List.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) List(ctx, opts any) *MockMutatingWebhookConfigurationV1InterfaceListCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, v10.ListOptions, *v1.MutatingWebhookConfigurationList, error](mr.mock.ctrl.T, mr.mock, "List", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(opts))
	mr.listExpects = append(mr.listExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceListCall is the typed call wrapper for List.
type MockMutatingWebhookConfigurationV1InterfaceListCall = gomock.Call2_2[context.Context, v10.ListOptions, *v1.MutatingWebhookConfigurationList, error]

// Patch mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v10.PatchOptions, subresources ...string) (*v1.MutatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch5V_2(&m.recorder.patchExpects, m.ctrl, m, "Patch", ctx, name, pt, data, opts, subresources...)
}

// Patch indicates an expected call of Patch.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Patch(ctx, name, pt, data, opts any, subresources ...any) *MockMutatingWebhookConfigurationV1InterfacePatchCall {
	mr.mock.ctrl.T.Helper()
	varArgs := gomock.EnsureVariadicMatcher(subresources)
	call := gomock.NewCall5V_2[context.Context, string, types.PatchType, []byte, v10.PatchOptions, string, *v1.MutatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Patch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(pt), gomock.EnsureMatcher(data), gomock.EnsureMatcher(opts), varArgs)
	mr.patchExpects = append(mr.patchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfacePatchCall is the typed call wrapper for Patch.
type MockMutatingWebhookConfigurationV1InterfacePatchCall = gomock.Call5V_2[context.Context, string, types.PatchType, []byte, v10.PatchOptions, string, *v1.MutatingWebhookConfiguration, error]

// Update mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Update(ctx context.Context, mutatingWebhookConfiguration *v1.MutatingWebhookConfiguration, opts v10.UpdateOptions) (*v1.MutatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.updateExpects, m.ctrl, m, "Update", ctx, mutatingWebhookConfiguration, opts)
}

// Update indicates an expected call of Update.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Update(ctx, mutatingWebhookConfiguration, opts any) *MockMutatingWebhookConfigurationV1InterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, *v1.MutatingWebhookConfiguration, v10.UpdateOptions, *v1.MutatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Update", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(mutatingWebhookConfiguration), gomock.EnsureMatcher(opts))
	mr.updateExpects = append(mr.updateExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceUpdateCall is the typed call wrapper for Update.
type MockMutatingWebhookConfigurationV1InterfaceUpdateCall = gomock.Call3_2[context.Context, *v1.MutatingWebhookConfiguration, v10.UpdateOptions, *v1.MutatingWebhookConfiguration, error]

// Watch mocks base method.
func (m *MockMutatingWebhookConfigurationV1Interface) Watch(ctx context.Context, opts v10.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.watchExpects, m.ctrl, m, "Watch", ctx, opts)
}

// Watch indicates an expected call of Watch.
func (mr *MockMutatingWebhookConfigurationV1InterfaceMockRecorder) Watch(ctx, opts any) *MockMutatingWebhookConfigurationV1InterfaceWatchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, v10.ListOptions, watch.Interface, error](mr.mock.ctrl.T, mr.mock, "Watch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(opts))
	mr.watchExpects = append(mr.watchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockMutatingWebhookConfigurationV1InterfaceWatchCall is the typed call wrapper for Watch.
type MockMutatingWebhookConfigurationV1InterfaceWatchCall = gomock.Call2_2[context.Context, v10.ListOptions, watch.Interface, error]

// MockValidatingWebhookConfigurationV1Interface is a mock of ValidatingWebhookConfigurationInterface interface.
type MockValidatingWebhookConfigurationV1Interface struct {
	ctrl     *gomock.Controller
	recorder *MockValidatingWebhookConfigurationV1InterfaceMockRecorder
	isgomock struct{}
}

// MockValidatingWebhookConfigurationV1InterfaceMockRecorder is the mock recorder for MockValidatingWebhookConfigurationV1Interface.
type MockValidatingWebhookConfigurationV1InterfaceMockRecorder struct {
	mock                    *MockValidatingWebhookConfigurationV1Interface
	applyExpects            []*gomock.Call3_2[context.Context, *v11.ValidatingWebhookConfigurationApplyConfiguration, v10.ApplyOptions, *v1.ValidatingWebhookConfiguration, error]
	createExpects           []*gomock.Call3_2[context.Context, *v1.ValidatingWebhookConfiguration, v10.CreateOptions, *v1.ValidatingWebhookConfiguration, error]
	deleteExpects           []*gomock.Call3_1[context.Context, string, v10.DeleteOptions, error]
	deleteCollectionExpects []*gomock.Call3_1[context.Context, v10.DeleteOptions, v10.ListOptions, error]
	getExpects              []*gomock.Call3_2[context.Context, string, v10.GetOptions, *v1.ValidatingWebhookConfiguration, error]
	listExpects             []*gomock.Call2_2[context.Context, v10.ListOptions, *v1.ValidatingWebhookConfigurationList, error]
	patchExpects            []*gomock.Call5V_2[context.Context, string, types.PatchType, []byte, v10.PatchOptions, string, *v1.ValidatingWebhookConfiguration, error]
	updateExpects           []*gomock.Call3_2[context.Context, *v1.ValidatingWebhookConfiguration, v10.UpdateOptions, *v1.ValidatingWebhookConfiguration, error]
	watchExpects            []*gomock.Call2_2[context.Context, v10.ListOptions, watch.Interface, error]
}

// NewMockValidatingWebhookConfigurationV1Interface creates a new mock instance.
func NewMockValidatingWebhookConfigurationV1Interface(ctrl *gomock.Controller) *MockValidatingWebhookConfigurationV1Interface {
	mock := &MockValidatingWebhookConfigurationV1Interface{ctrl: ctrl}
	mock.recorder = &MockValidatingWebhookConfigurationV1InterfaceMockRecorder{mock: mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatingWebhookConfigurationV1Interface) EXPECT() *MockValidatingWebhookConfigurationV1InterfaceMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Apply(ctx context.Context, validatingWebhookConfiguration *v11.ValidatingWebhookConfigurationApplyConfiguration, opts v10.ApplyOptions) (*v1.ValidatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.applyExpects, m.ctrl, m, "Apply", ctx, validatingWebhookConfiguration, opts)
}

// Apply indicates an expected call of Apply.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Apply(ctx, validatingWebhookConfiguration, opts any) *MockValidatingWebhookConfigurationV1InterfaceApplyCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, *v11.ValidatingWebhookConfigurationApplyConfiguration, v10.ApplyOptions, *v1.ValidatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Apply", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(validatingWebhookConfiguration), gomock.EnsureMatcher(opts))
	mr.applyExpects = append(mr.applyExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceApplyCall is the typed call wrapper for Apply.
type MockValidatingWebhookConfigurationV1InterfaceApplyCall = gomock.Call3_2[context.Context, *v11.ValidatingWebhookConfigurationApplyConfiguration, v10.ApplyOptions, *v1.ValidatingWebhookConfiguration, error]

// Create mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Create(ctx context.Context, validatingWebhookConfiguration *v1.ValidatingWebhookConfiguration, opts v10.CreateOptions) (*v1.ValidatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.createExpects, m.ctrl, m, "Create", ctx, validatingWebhookConfiguration, opts)
}

// Create indicates an expected call of Create.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Create(ctx, validatingWebhookConfiguration, opts any) *MockValidatingWebhookConfigurationV1InterfaceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, *v1.ValidatingWebhookConfiguration, v10.CreateOptions, *v1.ValidatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Create", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(validatingWebhookConfiguration), gomock.EnsureMatcher(opts))
	mr.createExpects = append(mr.createExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceCreateCall is the typed call wrapper for Create.
type MockValidatingWebhookConfigurationV1InterfaceCreateCall = gomock.Call3_2[context.Context, *v1.ValidatingWebhookConfiguration, v10.CreateOptions, *v1.ValidatingWebhookConfiguration, error]

// Delete mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Delete(ctx context.Context, name string, opts v10.DeleteOptions) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.deleteExpects, m.ctrl, m, "Delete", ctx, name, opts)
}

// Delete indicates an expected call of Delete.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Delete(ctx, name, opts any) *MockValidatingWebhookConfigurationV1InterfaceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, string, v10.DeleteOptions, error](mr.mock.ctrl.T, mr.mock, "Delete", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(opts))
	mr.deleteExpects = append(mr.deleteExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceDeleteCall is the typed call wrapper for Delete.
type MockValidatingWebhookConfigurationV1InterfaceDeleteCall = gomock.Call3_1[context.Context, string, v10.DeleteOptions, error]

// DeleteCollection mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) DeleteCollection(ctx context.Context, opts v10.DeleteOptions, listOpts v10.ListOptions) error {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_1(&m.recorder.deleteCollectionExpects, m.ctrl, m, "DeleteCollection", ctx, opts, listOpts)
}

// DeleteCollection indicates an expected call of DeleteCollection.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) DeleteCollection(ctx, opts, listOpts any) *MockValidatingWebhookConfigurationV1InterfaceDeleteCollectionCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_1[context.Context, v10.DeleteOptions, v10.ListOptions, error](mr.mock.ctrl.T, mr.mock, "DeleteCollection", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(opts), gomock.EnsureMatcher(listOpts))
	mr.deleteCollectionExpects = append(mr.deleteCollectionExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceDeleteCollectionCall is the typed call wrapper for DeleteCollection.
type MockValidatingWebhookConfigurationV1InterfaceDeleteCollectionCall = gomock.Call3_1[context.Context, v10.DeleteOptions, v10.ListOptions, error]

// Get mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Get(ctx context.Context, name string, opts v10.GetOptions) (*v1.ValidatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.getExpects, m.ctrl, m, "Get", ctx, name, opts)
}

// Get indicates an expected call of Get.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Get(ctx, name, opts any) *MockValidatingWebhookConfigurationV1InterfaceGetCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, string, v10.GetOptions, *v1.ValidatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Get", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(opts))
	mr.getExpects = append(mr.getExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceGetCall is the typed call wrapper for Get.
type MockValidatingWebhookConfigurationV1InterfaceGetCall = gomock.Call3_2[context.Context, string, v10.GetOptions, *v1.ValidatingWebhookConfiguration, error]

// List mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) List(ctx context.Context, opts v10.ListOptions) (*v1.ValidatingWebhookConfigurationList, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.listExpects, m.ctrl, m, "List", ctx, opts)
}

// List indicates an expected call of List.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) List(ctx, opts any) *MockValidatingWebhookConfigurationV1InterfaceListCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, v10.ListOptions, *v1.ValidatingWebhookConfigurationList, error](mr.mock.ctrl.T, mr.mock, "List", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(opts))
	mr.listExpects = append(mr.listExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceListCall is the typed call wrapper for List.
type MockValidatingWebhookConfigurationV1InterfaceListCall = gomock.Call2_2[context.Context, v10.ListOptions, *v1.ValidatingWebhookConfigurationList, error]

// Patch mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v10.PatchOptions, subresources ...string) (*v1.ValidatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch5V_2(&m.recorder.patchExpects, m.ctrl, m, "Patch", ctx, name, pt, data, opts, subresources...)
}

// Patch indicates an expected call of Patch.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Patch(ctx, name, pt, data, opts any, subresources ...any) *MockValidatingWebhookConfigurationV1InterfacePatchCall {
	mr.mock.ctrl.T.Helper()
	varArgs := gomock.EnsureVariadicMatcher(subresources)
	call := gomock.NewCall5V_2[context.Context, string, types.PatchType, []byte, v10.PatchOptions, string, *v1.ValidatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Patch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(name), gomock.EnsureMatcher(pt), gomock.EnsureMatcher(data), gomock.EnsureMatcher(opts), varArgs)
	mr.patchExpects = append(mr.patchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfacePatchCall is the typed call wrapper for Patch.
type MockValidatingWebhookConfigurationV1InterfacePatchCall = gomock.Call5V_2[context.Context, string, types.PatchType, []byte, v10.PatchOptions, string, *v1.ValidatingWebhookConfiguration, error]

// Update mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Update(ctx context.Context, validatingWebhookConfiguration *v1.ValidatingWebhookConfiguration, opts v10.UpdateOptions) (*v1.ValidatingWebhookConfiguration, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch3_2(&m.recorder.updateExpects, m.ctrl, m, "Update", ctx, validatingWebhookConfiguration, opts)
}

// Update indicates an expected call of Update.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Update(ctx, validatingWebhookConfiguration, opts any) *MockValidatingWebhookConfigurationV1InterfaceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall3_2[context.Context, *v1.ValidatingWebhookConfiguration, v10.UpdateOptions, *v1.ValidatingWebhookConfiguration, error](mr.mock.ctrl.T, mr.mock, "Update", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(validatingWebhookConfiguration), gomock.EnsureMatcher(opts))
	mr.updateExpects = append(mr.updateExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceUpdateCall is the typed call wrapper for Update.
type MockValidatingWebhookConfigurationV1InterfaceUpdateCall = gomock.Call3_2[context.Context, *v1.ValidatingWebhookConfiguration, v10.UpdateOptions, *v1.ValidatingWebhookConfiguration, error]

// Watch mocks base method.
func (m *MockValidatingWebhookConfigurationV1Interface) Watch(ctx context.Context, opts v10.ListOptions) (watch.Interface, error) {
	m.ctrl.T.Helper()
	return gomock.Dispatch2_2(&m.recorder.watchExpects, m.ctrl, m, "Watch", ctx, opts)
}

// Watch indicates an expected call of Watch.
func (mr *MockValidatingWebhookConfigurationV1InterfaceMockRecorder) Watch(ctx, opts any) *MockValidatingWebhookConfigurationV1InterfaceWatchCall {
	mr.mock.ctrl.T.Helper()
	call := gomock.NewCall2_2[context.Context, v10.ListOptions, watch.Interface, error](mr.mock.ctrl.T, mr.mock, "Watch", gomock.EnsureMatcher(ctx), gomock.EnsureMatcher(opts))
	mr.watchExpects = append(mr.watchExpects, call)
	mr.mock.ctrl.Track(call.Call)
	return call
}

// MockValidatingWebhookConfigurationV1InterfaceWatchCall is the typed call wrapper for Watch.
type MockValidatingWebhookConfigurationV1InterfaceWatchCall = gomock.Call2_2[context.Context, v10.ListOptions, watch.Interface, error]
