#!/bin/sh

PATH=/snap/bin:$PATH

# microk8s is required.
if ! which microk8s.kubectl; then
    echo "microk8s is not installed."
    exit 0
fi

if ! which timeout; then
    echo "timeout is not installed."
    exit 0
fi

timeout 2m sh <<EOT || echo true
container_cmd=microk8s.ctr
image_arg="--namespace k8s.io images"
if ! which $container_cmd; then
    container_cmd=microk8s.docker
    image_arg=image
    if ! which $container_cmd; then
        echo "Neither docker or ctr image control found."
        exit 0
    fi
fi

echo "Wait for microk8s to be ready if needed."
wait_result=$(microk8s.status --wait-ready --timeout 30 2>&1)
if [ $? -ne 0 ]; then
    echo "${wait_result}"
    exit 0
fi

juju_version=$(/snap/bin/juju version | rev | cut -d- -f3- | rev)
oci_image="docker.io/jujusolutions/jujud-operator:$juju_version"
mongo_image="docker.io/jujusolutions/juju-db:4.0"

echo "Going to cache images: $oci_image and $mongo_image."

# It's not an install/refresh blocker if we can't get the images.
echo "Pulling: $oci_image."
$container_cmd $image_arg list | grep $oci_image || $container_cmd $image_arg pull $oci_image || true

echo "Pulling: $mongo_image."
$container_cmd $image_arg list | grep $mongo_image || $container_cmd $image_arg pull $mongo_image || true
EOT
