#!/bin/bash -eux
monkey_id='*'
chaos_dir="$(config-get chaos-dir)"
action_chaos_dir="$(action-get chaos-dir)"
action_monkey_id="$(action-get monkey-id)"
[[ -n ${action_chaos_dir:-} ]] && chaos_dir=${action_chaos_dir}
[[ -n ${action_monkey_id:-} ]] && monkey_id=${action_monkey_id}
action-set action-parameters.chaos-dir="${chaos_dir}"
action-set action-parameters.monkey-id="${monkey_id}"

target_dir="${chaos_dir}/chaos_monkey.${monkey_id}"
for dir in ${target_dir}; do
    log="${dir}/log/results.log"
    key=${dir##*\/chaos_monkey\.}
    count=1
    while read line; do
        action-set ${key}-run-log.${count}="${line}"
        count=$((count + 1))
    done < ${log}
done
