#!/bin/bash -eux
total_timeout="$(action-get total-timeout)"
pause_timeout="$(action-get pause-timeout)"
dry_run="$(config-get dry-run)"
chaos_dir="$(config-get chaos-dir)"
action-set action-parameters.chaos-dir="${chaos_dir}"
action-set action-parameters.charm-dir="${CHARM_DIR}"
action-set action-parameters.dry-run="${dry_run}"
action-set action-parameters.monkey-id=$$
action-set action-parameters.pause-timeout="${pause_timeout}"
action-set action-parameters.total-timeout="${total_timeout}"

# Create a unique directory to run and log this monkeys actions.
target_dir=${chaos_dir}/chaos_monkey.$$
mkdir -p ${target_dir}/log
if [[ -d ${CHARM_DIR}/chaos-monkey ]]; then
    cp -a ${CHARM_DIR}/chaos-monkey ${target_dir}
fi

# Run the Chaos Monkey
cmd="python ${target_dir}/chaos-monkey/runner.py"
if [[ -n ${total_timeout:-} ]]; then
    cmd+=" --total_timeout ${total_timeout}"
fi
if [[ -n ${pause_timeout:-} ]]; then
    cmd+=" --pause_timeout ${pause_timeout}"
fi
action-set action-info.runner-cmd="${cmd}"
action-set action-info.runner-log="${target_dir}/log/resutls.log"
if [[ ${dry_run-} != True ]]; then
    nohup ${cmd} >> ${target_dir}/log/resutls.log 2>&1
    if [ $? != 0 ]; then
        action-fail "ERROR:Non-zero exit code from: ${cmd}"
    fi
fi
