#!/usr/bin/env python
import os
import subprocess
import sys


def main():
    substitutes = {
        '-m': ['-e'],
    }
    args = []
    forbidden_values = set()
    for val in substitutes.values():
        for subval in val:
            assert subval not in sys.argv, '{} not permitted.'.format(subval)
    env = dict(os.environ)
    for arg in sys.argv[1:]:
        arg = substitutes.get(arg, [arg])
        args.extend(arg)
    if '--version' in args:
        print '2.0-alpha2'
        return 0
    return subprocess.call([os.environ['REAL_JUJU']] + args, env=env)


if __name__ == '__main__':
    sys.exit(main())
