#!/bin/bash

set -x

RES_NAME="foo"

START_TIME=$(date +%s)
RES_PATH=$(2>&1 resource-get $RES_NAME)
if [ $? -ne 0 ]; then
  RES_GET_STDERR=$RES_PATH
  status-set blocked "[resource "'"'"$RES_NAME"'"'"] $RES_GET_STDERR"
  exit 0
fi

TOTAL=$(($(date +%s) - $START_TIME))
SIZE=$(du -b $RES_PATH | cut -f1)
status-set maintenance "Path: $RES_PATH Time: $TOTAL sec Size: $SIZE bytes"
