#!/bin/bash
set -e

export PEBBLE_SOCKET=/charm/containers/rootful/pebble.socket
juju-log "rootful=$(/charm/bin/pebble exec -- bash -c 'echo $UID')"

touch /charm/containers/rootful/ready
if [ -f "/charm/containers/rootless/ready" ]; then
    status-set active "Ready."
fi
