#!/bin/bash
# Install base OS packages required to build musl and link dqlite statically.
set -eu

apt-get update
apt-get install -y --no-install-recommends \
    bzip2 \
    ca-certificates \
    curl \
    gcc \
    git \
    libc6-dev \
    linux-libc-dev \
    make \
    wget
