#!/bin/bash
set -eux

mkdir -p /var/run/dummy-sink
token=$(relation-get token)
echo "$token" > /var/run/dummy-sink/token
if [[ -z $token ]]; then
  juju-log -l INFO "Waiting for token"
  status-set waiting "Waiting for token" || true
else
  juju-log -l INFO "Token is $token"
  status-set active "Token is $token" || true
fi
