#!/bin/bash
set -ue
. hooks/monitors.common.bash
if [ -r "$revoke_todo" ] ; then
    sed -e 's/^/REVOKE USAGE ON *.* FROM /;s/$/\;/;' < $revoke_todo
    sed -e 's/^/REVOKE USAGE ON *.* FROM /;s/$/\;/;' < $revoke_todo | $MYSQL
    rm -f $revoke_todo
fi
