#!/bin/bash

set -eu

source inc/common

if [ ! -f .memcache ]; then
	juju-log "I guess we've already done this..."
	exit 0
fi

rm -f .memcache

juju-log "Fairwell memcache, fairwell memcache"

. hooks/config-changed
