name: juju
version: 3.0-beta1
summary: Juju - a charmed Operator Lifecycle Manager for K8s and machines
description: |
 Juju is an Open Source Charmed Operator Framework. It helps you move from configuration management to application management and has two main components:

* **Charmed Operator Lifecycle Manager (OLM)** - a hybrid-cloud application management and orchestration system that helps you from Day 0 to Day 2. Deploy, configure, scale, **integrate**, maintain and manage Kubernetes native, container-native and VM-native applications -- and the relations between them.
   * **Charmed Operators, packaged as “Charms”**, are software that encapsulate a single application and all the code and know-how it takes to operate it on Kubernetes or machines.
* **Charmed Operator SDK** - a guide to help you build Charmed Operators for use with the Charmed OLM.

  **Learn more**

   - https://juju.is/
   - https://discourse.charmhub.io/
   - https://github.com/juju/juju

confinement: classic
grade: devel
base: core18

apps:
  juju:
    environment:
      # Make sure we access snap binaries first (i.e. juju-metadata lp:1759013)
      PATH: "$SNAP/bin:$SNAP/usr/bin:/snap/bin:$PATH"
    command: bin/juju
  fetch-oci:
    daemon: oneshot
    command: wrappers/fetch-oci
    start-timeout: 1m
    stop-timeout: 35s

parts:
  wrappers:
    plugin: dump
    source: snap/local
  juju:
    # TODO(hpidcock): move to upstream go plugin when it has the features we need.
    plugin: juju-go
    go-channel: 1.16/stable
    # The source can be your local tree or github
    # source: https://github.com/juju/juju.git
    # If you pull a remote, set source-depth to 1 to make the fetch shorter
    # source-depth: 1
    # source: file:///full/file/path
    # By default, reuse existing tree
    source: .
    # TODO(wallyworld) - uncomment source-type once LP:1860526 is fixed. 
    #source-type: git
    # You can grab a specific tag, commit, or branch
    # source-tag: juju-2.0.2
    # source-commit: a83896d913d7e43c960e441c1e41612116d92d46
    # source-branch: develop
    # apply patches before building
    go-packages:
      - github.com/juju/juju/cmd/juju
      # If you are releasing a build with public streams, you don't need to build the agent
      # Instead, you should use the released agent
      - github.com/juju/juju/cmd/jujuc
      - github.com/juju/juju/cmd/jujud
      - github.com/juju/juju/cmd/plugins/juju-metadata
      - github.com/juju/juju/cmd/plugins/juju-wait-for
    # go-external-strings is not supported by the standard go plugin.
    # these strings are filled in by CI.
    go-external-strings:
      github.com/juju/juju/version.GitCommit: ""
      github.com/juju/juju/version.GitTreeState: ""
      github.com/juju/juju/version.build: ""
    # go-static is not supported by the standard go plugin.
    go-static: true
    # go-strip is not supported by the standard go plugin.
    go-strip: true
    override-build: |
      snapcraftctl build

      mkdir -p $SNAPCRAFT_PART_INSTALL/bash_completions
      cp -a etc/bash_completion.d/juju* $SNAPCRAFT_PART_INSTALL/bash_completions/.
      # If you are releasing a build with public streams, copy in the agent directly
      # If needed, grab the agent from streams
      # curl http://streams.canonical.com/juju/tools/agent/$SNAPCRAFT_PROJECT_VERSION/juju-$SNAPCRAFT_PROJECT_VERSION-ubuntu-amd64.tgz | tar xz -C $SNAPCRAFT_PART_INSTALL/bin/
      jujud=$SNAPCRAFT_PART_INSTALL/bin/jujud
      version=$(jujud version)
      hash=$(sha256sum $jujud | cut -d " " -f 1)
      cat > jujud-versions.yaml <<EOF
      versions:
        - version: $version
          sha256: $hash
      EOF
      cp -a jujud-versions.yaml $SNAPCRAFT_PART_INSTALL/bin

hooks:
  connect-plug-peers: {}
  disconnect-plug-peers: {}
  post-refresh: {}

plugs:
  peers:
    interface: content
    content: microk8s
    target: $SNAP_COMMON/.peers
