options:
  # Will be tokens for each storage type.
  single-fs-token:
    type: string
    default: ''
    description: Token used to prove data stored is persistent
  multi-fs-token:
    type: string
    default: ''
    description: Token used to prove data stored is persistent
  single-blk-token:
    type: string
    default: ''
    description: TBA
  multi-blk-token:
    type: string
    default: ''
    description: TBA
