# Copyright 2020 juju-qa@canonical.com
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  thing:
    default: 🎁
    description: A thing used by the charm.
    type: string
  status:
    default: "hello"
    description: Temporary string for unit status
    type: string
  skill:
    default: 0
    description: Skill level.
    type: int
  foo-file:
    default: False
    description: Get resource and set log contents of foo-file as Info.
    type: boolean


