name: "CLA check"
on: [pull_request, workflow_dispatch, merge_group]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v2
