name: "Juju JAAS Smoke Test"
on:
  push:
    branches: ["[0-9].[0-9]+", "[0-9].[0-9]+.[0-9]+"]
  pull_request:
    branches-ignore: ["main"]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke:
    name: JAAS Smoke Test
    runs-on:
      - self-hosted
      - linux
      - x64
      - ${{ (github.repository_owner == 'juju' && 'aws') || (github.repository_owner == 'canonical' && 'noble') }}
      - large

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@16feee727cbdc83b6a014e6cc26fec4a79bcf30c # v2.2.0

      - name: "Squid"
        if: github.repository_owner != 'juju'
        run: ./.github/squid.sh

      - name: Install Dependencies
        shell: bash
        run: |
          set -euxo pipefail
          echo "/snap/bin" >> $GITHUB_PATH
          sudo DEBIAN_FRONTEND=noninteractive apt install -y expect

      - name: Checkout juju
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Setup env
        shell: bash
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install local Juju
        shell: bash
        run: |
          make go-install

      - name: Start JIMM, bootstrap a Juju controller and add it to JIMM.
        uses: canonical/jimm/.github/actions/test-server@feature/juju-4
        id: jaas
        with:
          jimm-version: v3.4.0-alpha2
          ghcr-pat: ${{ secrets.GITHUB_TOKEN }}
          dump-logs: true
          use-charmed-k8s-action: "false"

      - name: Create a model, deploy an application and run juju status
        run: |
          juju add-model foo && \
          juju deploy haproxy && \
          sleep 5 && \
          juju status
