name: CI

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    - "2.6"

jobs:
  static_analysis:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Go 1.12
      uses: cedrickring/golang-action/go1.12@1.3.0

    - name: Install deps
      run: |
        make dep

    - name: Run static analysis
      run: |
        make static-analysis
