#!/bin/bash

set -x

juju-log -l INFO "Install"
juju-log -l INFO "Data on drive: $(cat /srv/single-fs/test.txt)"

for unit in $(storage-list); do
    juju-log -l INFO "Storage details for ${unit}: $(storage-get -s $unit)"
done

# The storage-attached hook has fired so we can write some data there now.
status-set maintenance "Installed" || true
