#!/bin/sh
peer="$(snapctl get --slot :peers content)"
(
    SNAP_INSTANCE_NAME=${SNAP_INSTANCE_NAME:-$SNAP_NAME}
    echo "hook $0 $@"
    echo "connected to peer $peer"
    echo "$0 is starting $SNAP_INSTANCE_NAME.fetch-oci"
    snapctl start $SNAP_INSTANCE_NAME.fetch-oci
) >> $SNAP_COMMON/hook.log
