#!/bin/sh -eu

PATH=/snap/bin:$PATH

if ! which microk8s.kubectl; then
    echo "microk8s is not installed."
    exit 0
fi

container_cmd=microk8s.ctr
image_arg=images
if ! which $container_cmd; then
    container_cmd=microk8s.docker
    image_arg=image
    if ! which $container_cmd; then
        echo "Neither docker or ctr image control found."
        exit 0
    fi
fi

juju_version=$(/snap/bin/juju version | rev | cut -d- -f3- | rev)
oci_image="docker.io/jujusolutions/jujud-operator:$juju_version"
mongo_image="docker.io/jujusolutions/juju-db:4.0"

echo "Going to cache images: $oci_image and $mongo_image."

echo "Pulling: $oci_image."
$container_cmd -n k8s.io $image_arg pull $oci_image

echo "Pulling: $mongo_image."
$container_cmd -n k8s.io $image_arg pull $mongo_image
