#!/bin/sh
(
    echo "hook $0 $@" 
    mkdir -vp "$SNAP_COMMON/microk8s" || true
    echo "install hook $SNAP_NAME.fetch-oci is starting"
    snapctl start $SNAP_NAME.fetch-oci
    echo "image fetched successfully"
    echo "install hook $SNAP_NAME.fetch-oci is stopping"
    snapctl stop --disable $SNAP_NAME.fetch-oci
) >> $SNAP_COMMON/hook.log
